### ISSUE TITLE
Marshaller needs capability of polling for data on regular intervals 

### ISSUE THREAD

**Issue by jbrundage** [hpcc-systems/Visualization#1009]
@rpastrana needs this capability for a HeatMap customer demonstration in the near future

**Comment by mlzummo** [comment]
I can work on this as soon as I am done with the timeout/error callback additions to the marshaller.

@GordonSmith I have a bunch of questions for the timeout/error code ... and if i'm going to impl poling as well i got a bunch of questions about that as well.

@GordonSmith When are you going to be back and avail to chat?

**Comment by GordonSmith** [comment]
1.  DDL will need an indicator to say which viz needs to poll and how frequently.
2.  The marshaller will simply set up an interval handler for that viz at that frequency,

**Comment by mlzummo** [comment]
@GordonSmith @jbrundage this will need to be moved to greater than 1.10 (possibly 2)

**Comment by mlzummo** [comment]
@GordonSmith push to 1.12 or 2.0

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
