### ISSUE TITLE
HPCC Chart (long labels get cut off)

### ISSUE THREAD

**Issue by mzummo** [hpcc-systems/Visualization#1012]

**Comment by mlzummo** [comment]
![image](https://cloud.githubusercontent.com/assets/1057527/10375126/c040685a-6dc4-11e5-9d2c-a64a1be1bbe5.png)

**Comment by mlzummo** [comment]
also looks like stagger is making "science" move too

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
