### ISSUE TITLE
Add MegaChart as a compilation of existing widgets

### ISSUE THREAD

**Issue by jbrundage** [hpcc-systems/Visualization#1028]
Surface+Border+Text+Legend+Chart
  * Surface
    * Border
      * Left container = TextWidget = Y-Axis Title
      * Bottom container = TextWidget = X-Axis Title
      * Center container = Any chart widget
      * Right container = Legend widget attached to chart within Center container

**Comment by GordonSmith** [comment]
Looks about correct - I would also like to see a button on the surface for show/hide the legend - but that could be a v2 feature?

**Comment by GordonSmith** [comment]
I would also make the Surface the base class of the MegaChart (currently its the BorderLayout)
