### ISSUE TITLE
how do you run DDL/WU links though dermatology now?

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1032]

**Comment by GordonSmith** [comment]
1. Open http://rawgit.com/hpcc-systems/Visualization/master/demos/dermatology.html?src/marshaller/HTML
2. past in the DDL into the PP "ddlUrl"
3. Let me know if this is no longer working

**Comment by mlzummo** [comment]
how would i run this in dermatology:

rawgit.com/hpcc-systems/Visualization/candidate-1.8.0/demos/marshaller/index.html?Hostname=216.19.105.2&Port=18010&Protocol=https&Wuid=W20151012-090215&ResultName=selvamd1_timechart_Comp_Ins008_DDL

**Comment by GordonSmith** [comment]
If you must use dermatology to open that (rather than using demos/marshaller/index.html) you will need to reconstruct the DDL Url:
https://216.19.105.2:18010/WsWorkunits/WUResult?Wuid=W20151012-090215&ResultName=selvamd1_timechart_Comp_Ins008_DDL (or similar)

**Comment by mlzummo** [comment]
leave this question open im going to reference this alot in the future

**Comment by GordonSmith** [comment]
You can reference the closed issue equally easily?
