### ISSUE TITLE
GMap Unit Test Failing

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1045]

**Comment by mlzummo** [comment]
perhaps not ... will research more tomorrow

**Comment by GordonSmith** [comment]
Aha - this might explain why my PRs tend to pass - as I tend to submit them early in the 24 hour window.
It would be worthwhile adding some checks for the status return value as per:   https://developers.google.com/maps/documentation/business/articles/usage_limits and https://developers.google.com/maps/documentation/geocoding/intro#StatusCodes

**Comment by mlzummo** [comment]
@GordonSmith can we do that in another PR? ... i am not sure how to handle that just yet

**Comment by mlzummo** [comment]
how should status return values be handled (in the widget and in the unit tests)?

**Comment by mlzummo** [comment]
@GordonSmith i think this will suffice for fixing GMAP UT issue .. megacharts is failing now ...
