### ISSUE TITLE
Surface layout's exit method breaking PropertyEditor on dermatology.html

### ISSUE THREAD

**Issue by jbrundage** [hpcc-systems/Visualization#1055]

**Comment by jbrundage** [comment]
To experience this issue:
Attempt to change widget types after selecting "layout -> Surface" on dermatology.html
http://rawgit.com/hpcc-systems/Visualization/candidate-1.8.0/demos/dermatology.html?src/layout/Surface

**Comment by jbrundage** [comment]
@GordonSmith Is this line of code needed? Commenting it out fixes this issue.
https://github.com/hpcc-systems/Visualization/blame/master/src/layout/Surface.js#L141

**Comment by GordonSmith** [comment]
It may not be needed - test with the new leak checker?

**Comment by jbrundage** [comment]
@GordonSmith The issue doesn't occur with the #1160 PropertyEditor

**Comment by GordonSmith** [comment]
Assigning to myself as that code looks wrong to me...

**Comment by GordonSmith** [comment]
Resolved
