### ISSUE TITLE
perhaps look at replacing c3 with dc.js?

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1069]

**Comment by mlzummo** [comment]
one big reason is i don't like that alot of the params cant be updated after first render

**Comment by GordonSmith** [comment]
dc is more about crossfilter than the charts...

**Comment by mlzummo** [comment]
@GordonSmith will you greenlight doing it?

**Comment by mlzummo** [comment]
@GordonSmith I have also hit a snag with rendering Line graph in TimeX Axis (i can get it to work on a Hipiie example i have) but for our normal example with Price and lots of nulls i get a scatter chart instead

**Comment by GordonSmith** [comment]
dc charts - nope.  Crossfilter maybe, I use it ECL Watch for aggregating some of the stats...

If there is a specific chart ion DC you like, it would be trivial to re-code it in the Viz Framework.

**Comment by mlzummo** [comment]
https://groups.google.com/forum/#!topic/c3js/KHUD20RP_hs

**Comment by mlzummo** [comment]
https://groups.google.com/forum/#!forum/c3js
