### ISSUE TITLE
build refresh button into prop editor that will redraw chart from scratch applying new publish params

### ISSUE THREAD

**Issue by mzummo** [hpcc-systems/Visualization#1070]

**Comment by jbrundage** [comment]
Can you elaborate on "applying new publish params"?

**Comment by mlzummo** [comment]
@jbrundage ok for example c3 x axis label rotation doesnt work unless you load the param before first render() ... with this button it will read the publish params create a brand new widget and run render() for the first time everytime the button is clicked that way we can use/test those params without coding exampes from scratch

**Comment by GordonSmith** [comment]
I think its more a "reset" button...

**Comment by jbrundage** [comment]
@GordonSmith Can you think of a way to accomplish this while preserving all events tied to the chart?

**Comment by GordonSmith** [comment]
```
widget.target(null).target(div)
```
Might work?

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
