### ISSUE TITLE
Long Label XY Axis Test is corrupt

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#1087]
http://rawgit.com/hpcc-systems/Visualization/master/demos/test.html?chart

**Comment by mlzummo** [comment]
@GordonSmith how should it look in that small of a container? that's how i'd except it to look actually ... still need a margin fix as well

**Comment by GordonSmith** [comment]
![image](https://cloud.githubusercontent.com/assets/966863/10704091/50e74fb4-79cc-11e5-9b81-50e2f3f93b5a.png) - If the label is as long as the red elipse then yes I guess so...

**Comment by mlzummo** [comment]
@GordonSmith this needs closing, or new code adapted to the HPCC Charts (the method in HPCC Charts just wont allow for this to be easly fixed)
