### ISSUE TITLE
Table - Ability to perform more calculations (ex. % of column total, % or row total, % of grand total)

### ISSUE THREAD

**Issue by mzummo** [hpcc-systems/Visualization#1095]
Ability to perform more calculations (ex. % of column total, % or row total, % of grand total)

**Comment by dtsnell4** [comment]
@mlzummo Can you provide more details or examples of what calculations they are looking for?  I could do this but I'm not sure whats being asked for.

**Comment by jpellock** [comment]
Does this include sub totals and a pivot table where at design time attributes can be placed on columns? If so we'd like to raise the priority to High.

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
