### ISSUE TITLE
standardize having bar/column chart (i think we should only do column with orientation flag)

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1096]

**Comment by mlzummo** [comment]
also getting errors sometimes in Property Editor in multichart when selecting bar it cant find type bar

**Comment by GordonSmith** [comment]
I agree on standardizing - but I suspect it will have to be bar + column as not all implementations will support the orientation?

**Comment by mlzummo** [comment]
@GordonSmith in that case we would just require both the bar and column of whatever library and switch between the two depending on the orientation switch ... or we can have 2 widgets which just set a flag on the main column one? which do you prefer?

**Comment by GordonSmith** [comment]
I would keep it simple and its easy to have a bar + column for each project?
