### ISSUE TITLE
how to grab widget based on DDL name

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1097]
How can we grab a widget when using widgetwalker based on the unique id its provided in the DDL?

**Comment by mlzummo** [comment]
@GordonSmith could use this now for a team if we could add a name() along with id() thats already there that would be cool

**Comment by mlzummo** [comment]
inserting a name into the class as well could kill 2 birds with one stone too?

**Comment by GordonSmith** [comment]
When a widget is created via DDL it is given a name for the ID - you can use that ID to select it and get the Widget instance:
```
var widget = d3.select("#id").datum();
```

**Comment by mlzummo** [comment]
good to know (leave this issue open so i can reference this in the future) .. until we put it in the documentation atleast

**Comment by GordonSmith** [comment]
You can reference closed issues as easily as open ones...
