### ISSUE TITLE
Add Google Gantt Chart

### ISSUE THREAD

**Issue by dtsnell4** [hpcc-systems/Visualization#1106]
Add the new Google Gantt chart to the library.

**Comment by GordonSmith** [comment]
@dtsnell4 It might be worth while re-testing the google material charts to see if our previous issue has been resolved?

**Comment by dtsnell4** [comment]
@GordonSmith  I just tried it yesterday....  it has not been unfortunately.  Want to see if the Gantt chart has the same issue, as it is also v1.1.

**Comment by dtsnell4** [comment]
Additionally, there are a bunch of other charts in the Google library we don't have.  Do you think any of them would be useful to us? (Donut, annotation, interval, org charts, trendlines, histograms, gauges, candlestick, their own version of choropleths...

**Comment by dtsnell4** [comment]
FYI, this chart is also v1.1, so it has the same problem the other material charts have loading twice.

**Comment by GordonSmith** [comment]
We won't be able to take them until we fix the double load issue (which I think is a google + requirejs issue) - also for some of those I think we should be rolling our own (based off of some similar d3 examples).
