### ISSUE TITLE
thoughts about separating a widgets PPs into its own object? 

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1117]
would make stuff like combo chart easier to include just the Publish Params instead of the whole object if its not going to use it?

**Comment by mlzummo** [comment]
@GordonSmith bump

**Comment by GordonSmith** [comment]
I am not sure what you mean?  Are you saying put the __props_xxx into a .__pros.xxx type of shape?  If so its on a very old todo list...
