### ISSUE TITLE
Google charts- change "stacked" property to "isStacked"

### ISSUE THREAD

**Issue by dtsnell4** [hpcc-systems/Visualization#1127]
For Bar, Column and Area widgets

**Comment by GordonSmith** [comment]
I agree we should standardize on the name, but isStacked is too much like a question and not intuitive for a setter/getter...

**Comment by dtsnell4** [comment]
We can keep our publish param "stacked" (or whatever we decide) but Google's property is "isStacked", just needs to be translated.  Thats why the option doesn't work right now.
