### ISSUE TITLE
Table widget default to paginate if more than X num of rows

### ISSUE THREAD

**Issue by jbrundage** [hpcc-systems/Visualization#1140]
After speaking with Jo Prichard regarding Table widget performance issues. It would make sense to allow the Table to paginate if a table contains more than X num of rows.

DSP regularly returns very large tables resulting in performance issues. If we create a publish param containing the desired threshold for Table row count (beyond which the Table would default to paginate), this would help resolve performance issues.

**Comment by GordonSmith** [comment]
I saw the same thing with the "DataAnalyst" and defaulted pagination to on for that project.
