### ISSUE TITLE
amcharts lose selection on resize

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1144]

**Comment by mlzummo** [comment]
@GordonSmith loos like even with the coloring its still an issue will have to reapply selection after an update event (i dont think there is a manual way of calling slide out on a pie chart without firing the event again)

**Comment by GordonSmith** [comment]
@mlzummo I know I have to do that in the hpcc charts (recolor selection on update).

**Comment by mlzummo** [comment]
fixed as of 1.10

**Comment by Gor** [comment]
@mlzummo Gor its me man. Stop writing my nickname in your discussions please )
