### ISSUE TITLE
Combo Chart Discussion

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1149]
@dtsnell4 @jbrundage @GordonSmith 
should we create a graph/chart obj per "column" with defaults.

this would basically look like a few new objects based off a single base (kinda like the Axis obj)

or should we just load up a widget array with a bunch of charttypes and then read the individual widgets PPs and Data and build a combo based on that (which is i believe how u were going to do it with hpcc charts except you can actually render them on the XYAxis) (cant in the other libs)

**Comment by GordonSmith** [comment]
Work/design is underway
