### ISSUE TITLE
move selection bag out of Utility

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1150]

**Comment by GordonSmith** [comment]
What is the actual issue?

**Comment by mlzummo** [comment]
My first thoughts on utility was that it would consist of helper functions that could be generally used everywhere/anywhere (selection bag only works with HPCC Charts and thus doesnt fit the bill (IMO))

**Comment by mlzummo** [comment]
i rather see it as its own File in common

**Comment by GordonSmith** [comment]
My "thoughts" for when Utility got "too large" was to convert it to a folder with several files (within common) - I don't think its big enough to worry about splitting it up yet.
