### ISSUE TITLE
create js files which auto includes all of the VIZ non amd min files and dependencies based off a config

### ISSUE THREAD

**Issue by mzummo** [hpcc-systems/Visualization#1156]

**Comment by mlzummo** [comment]
and perhaps have a callback ... the way google does it?

**Comment by mlzummo** [comment]
and a config obj that says what we want to load (all if nothing specified?)

**Comment by mlzummo** [comment]
low priority right now

**Comment by mlzummo** [comment]
@GordonSmith going to see what you have for loader code first

**Comment by GordonSmith** [comment]
FYI - I tweaked the gulp file to also create non minified AMD bundles.

**Comment by mlzummo** [comment]
@GordonSmith can we make one big .js file too?

**Comment by GordonSmith** [comment]
We could do - except for the choropleth data files (or it would be 1 very very big file).e

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
