### ISSUE TITLE
Table:  Ability to embed a widget into a cell.

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#1161]
Common use case will be embedding another table inside a single cell (a child dataset).

**Comment by mlzummo** [comment]
Also form inputs

**Comment by mlzummo** [comment]
part of GH-724

**Comment by dtsnell4** [comment]
While this seems straight forward enough, I do not know what the data will look like providing the widget for a particular cell.  Can anyone provide a real world example of what the data() is going to look like?  How does the widget get passed in?  In regards to GH-724, what is a child dataset in this context?

**Comment by GordonSmith** [comment]
```
table.data([["math", 22, new TextBox().text("Hello"), 33]]);
```

**Comment by GordonSmith** [comment]
(we may not be able to support pagination with this option - not easily anyway)
