### ISSUE TITLE
if form does not have any data do not allow it to submit

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1178]

**Comment by mlzummo** [comment]
per @dineshshetye

**Comment by GordonSmith** [comment]
This should be a publish param as it will not be true for every case.

**Comment by mlzummo** [comment]
@GordonSmith sounds good thanks (can i default it to on) ... basically DSP is having problems where they git submit on blank data cause they havent set a value and its crashing the browser

**Comment by mlzummo** [comment]
looks like there is already a publish param for this -> omitBlank

**Comment by mlzummo** [comment]
also in the marshaller we need to make it so that if a filter is blank it doesnt draw the chart ....

**Comment by mlzummo** [comment]
need to add code so that the marshaller sets the target visiblility to false for blank filters
