### ISSUE TITLE
HPCC Charts (horizontal and vertical isnt correct for bar/column)?

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1182]
@GordonSmith 
let me know if i am wrong here but shouldn't the direction be the direction the bars go? Column = Veritcal, Bar = Horizontal? (if not i need to change a few things)

**Comment by GordonSmith** [comment]
Columns go up and down and are orientation==="horizontal" (as the traditional x-axis data is on the horizontal).
