### ISSUE TITLE
sorting labels (month/day strings)

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1185]
https://github.com/hpcc-systems/DSP/issues/536

also see PR

**Comment by GordonSmith** [comment]
@mlzummo What PR?

Also here is the correct way to sort Months:
```
  column
    .xAxisType("time")
    .xAxisTypeTimePattern("%m")  
  ;
```

**Comment by mlzummo** [comment]
@GordonSmith but that wont work when the data from hipie is coming back literally "January", "February" ... Monday, Tuesday, (tue) ...

**Comment by GordonSmith** [comment]
For full month  use "%B"
For full day use: "%A" 
https://github.com/mbostock/d3/wiki/Time-Formatting

**Comment by mlzummo** [comment]
@GordonSmith this is not working in C3... (the sorting atleast)....
