### ISSUE TITLE
zooming/grey space/ label (fixes)

### ISSUE THREAD

**Issue by mzummo** [hpcc-systems/Visualization#1186]
If a chart has lot of grey background (consider a dashboard which only has a pie chart). There user should be able to zoom in and expand the chart. basically they are looking for zoom functionality.

**Comment by GordonSmith** [comment]
Screenshot?

**Comment by mlzummo** [comment]
@dineshshetye bump

**Comment by mlzummo** [comment]
@GordonSmith push to 1.12 or 2.0

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
