### ISSUE TITLE
DSP CSS styles are affecting widgets and causing different results when the widgets are displayed outside of DSP

### ISSUE THREAD

**Issue by jbrundage** [hpcc-systems/Visualization#1190]

**Comment by jbrundage** [comment]
The bulk of the issues seems to be here:
https://dsp-qa.risk.regn.net/css/main.css

Between lines 2706 and 2829

**Comment by jbrundage** [comment]
@mlzummo

**Comment by GordonSmith** [comment]
@jbrundage Why is this a Viz Framework Issue?  If DSP want to style the widgets so they look and behave differently then that should be fine?

**Comment by jbrundage** [comment]
@GordonSmith DSP is being used to design Grid layout compositions that can be retrieved by other web tools. When the user customizes and saves the look/feel of their Grid. They expect their Grid to look the same when it is deserialized in another webapp.

**Comment by GordonSmith** [comment]
Ahh ok, I see why that would be an issue then!

**Comment by mlzummo** [comment]
have DSP export a CSS file along with everything that can be applied ontop?

**Comment by GordonSmith** [comment]
The web page that hosts the DSP generated dashboards should share the same CSS file.
