### ISSUE TITLE
Grid needs publish params to control look/feel while in designMode (for ACC)

### ISSUE THREAD

**Issue by jbrundage** [hpcc-systems/Visualization#1200]
ACC needs a version of Grid's designMode with these features:
- [x] Disabled canvas grid lines
- [x] Transparent drag handles (edges of Cells should be draggable with no visible handles)
- [x] No Cell transparency
- [x] Cell selection is disabled
- [ ] Click+Drag to move Cell should only work via empty areas of the Cell's title bar
- [x] Dragging an edge of a Cell beyond the Grid's edge should be disabled.
- [ ] While dragging a Cell's edge, if a collision with another Cell edge occurs that secondary Cell should intuitively resize to avoid Cell overlap.
- [ ] When dragging a Cell's title bar (to move the entire Cell rather than resize), if the Cell is dropped while overlapping another Cell that secondary Cell should intuitively resize to avoid Cell overlap.
- [ ] If the drop target is the title bar of an existing widget then the swapping of the two widgets should be offered

Here's a link to test:
http://rawgit.com/jbrundage/Visualization/Grid_Imps/demos/dermatology.html?src/layout/Grid&designMode=1&restrictDraggingOut=1

**Comment by GordonSmith** [comment]
I think I agree with all of those except I would add:
If the drop target is the title bar of an existing widget _then_ the swapping of the two widgets should be offered?

**Comment by jbrundage** [comment]
That makes sense

**Comment by jbrundage** [comment]
#1242 currently adds these features to Grid:
* Toggle canvas grid lines with **hideDesignGrid**
* Toggle drag handle visibility with **hideDragHandles**
* Control opacity of cells in design mode with **designModeOpacity**

**Comment by jbrundage** [comment]
#1242 now adds the ability to enable/disable cell selecting via **disableCellSelection**

**Comment by jbrundage** [comment]
#1242 now adds the publish param **restrictDraggingOut**, which prevents a moving (or resizing) dragCell beyond the edges of the Grid (if **true**)
