### ISSUE TITLE
google bar column trouble rendering certain data

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1218]
I am not sure why but it looks as if google itself has an issue rendering this data structure:

[["label","weight"],["X1",2],["X2",1],["X3",1]]

**Comment by GordonSmith** [comment]
Interesting add a unitTest for that case

**Comment by GordonSmith** [comment]
Assigning to @mlzummo until the unitTest is done (I will look then).

**Comment by mlzummo** [comment]
http://localhost:8080/demos/marshaller/index.html?Hostname=10.241.100.159&Port=8010&Protocol=http&Wuid=W20151113-134143&ResultName=middleax_parsefulladdresstest_Comp_Ins1159_DDL
