### ISSUE TITLE
render issues (1.8.2)

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1221]
![image](https://cloud.githubusercontent.com/assets/1057527/11345507/7faf1e68-91e5-11e5-9a0c-a298ca02c69a.png)

**Comment by mlzummo** [comment]
the right one could be a legend trying to show? and the layout of the megachart could be clipping the bottom?

**Comment by jbrundage** [comment]
@mlzummo this might be caused by the DSP's CSS interference?

**Comment by GordonSmith** [comment]
@jbrundage We put it down to the MegaChart not working 100% and rolled back to use the MultiChaty.

**Comment by jbrundage** [comment]
I see... I'll have to look into it

**Comment by jbrundage** [comment]
@GordonSmith This can be closed. This shouldn't be an issue with the MegaChart anymore.
