### ISSUE TITLE
need to standardize x/y axis (category/value axis)

### ISSUE THREAD

**Issue by mzummo** [hpcc-systems/Visualization#1236]
since the X axis can be on the "Y" we should really switch our verbage around and allow for positioning as to not confuse people.

**Comment by GordonSmith** [comment]
Yup...

How about data-axis and value-axis?

**Comment by mlzummo** [comment]
ok ... and what do those correspond to normally data = x value = y?

**Comment by GordonSmith** [comment]
Yes.

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
