### ISSUE TITLE
specify a simple array of colors which correspond directly to line/bar/pie section

### ISSUE THREAD

**Issue by mzummo** [hpcc-systems/Visualization#1241]
(so colors can be specified in derm. for DSP)

**Comment by GordonSmith** [comment]
FYI the Palette has support for creating new custom palettes on the fly - this issue would be simply publishing and using that ability.

**Comment by GordonSmith** [comment]
@mlzummo I suspect this is a DSP function?  IOW it should be able to create a new Palette and then use it for a given visualization.

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
