### ISSUE TITLE
property editor filter params and override tags

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1246]
{
	"amchart_Column": {
		"fillOpacity": ["Basic"]
	}
}

**Comment by GordonSmith** [comment]
@mlzummo - Is the goal here to change the meta tags prior to the first widget being created?  Or is it to change the meta tags on a per widget instance basis?

**Comment by mlzummo** [comment]
@GordonSmith the purpose is to just filter what params are going to be displayed under certain defined categories .. i figured the best way would be to override the widget prototype and change out the tags on a userdefined basis

**Comment by mlzummo** [comment]
this is on a per widget basis (it looks through all the widgets) except for propertyeditor

**Comment by mlzummo** [comment]
var themeSelectObj = {
            "Default":null,
            "Param Tag Override":{
                "chart_Column":{ 
                    "overrideTags":{ 
                        "stacked": ["Intermediate"]
                    }   
                }
            },
