### ISSUE TITLE
In Layout  Designer, the visualizations are “active”, which takes more memory, bandwidth, etc.  If these were just representations (wireframes) it would run much more quickly.

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1264]
we should render the widgets with just the testData in layout designer mode?

**Comment by jbrundage** [comment]
We could hide them like this...
`
div[draggable=true] .surfaceWidget {
    display: none;
}
`

And then display the FontAwesome icons in their place.

**Comment by mlzummo** [comment]
thats not a bad idea have like a default widget icon attached to the widget for dragging purposes?
i think there is like a barchart icon we can use?

**Comment by jbrundage** [comment]
Check this out...

http://rawgit.com/jbrundage/Visualization/GH-1264/demos/dermatology.html?src/layout/Grid&designMode=true


It would be even cooler if we could use certain icons for specific types of widgets.
