### ISSUE TITLE
common\Database.js hipieMapSortArray throws error when fieldByLabel returns undefined

### ISSUE THREAD

**Issue by jbrundage** [hpcc-systems/Visualization#1267]
fieldByLabel returns undefined if this.fields() is an empty array

**Comment by jbrundage** [comment]
https://github.com/hpcc-systems/Visualization/blob/master/src/common/Database.js#L39

**Comment by GordonSmith** [comment]
It may be hipieMapSortArray should check that fields exist before trying to sort them or upstream should check if data has been loaded before trying to sort?

**Comment by jbrundage** [comment]
That sounds reasonable, though I'm not sure what hipieMapSortArray is being used to sort

**Comment by mlzummo** [comment]
ill take a look at that

**Comment by mlzummo** [comment]
@GordonSmith i think this is fixed withyour fix
