### ISSUE TITLE
Having a widget in the data causes a circular reference in Property Editor.   

### ISSUE THREAD

**Issue by dtsnell4** [hpcc-systems/Visualization#1282]
In the new property editor, having a widget in the data (e.g. in a table) gives "Uncaught TypeError: Converting circular structure to JSON" due to JSON.stringify() at this line https://github.com/hpcc-systems/Visualization/blob/master/src/other/PropertyEditor.js#L428

**Comment by jbrundage** [comment]
@dtsnell4 Could you link to an example of this issue occuring?

**Comment by dtsnell4** [comment]
@jbrundage You need data with a widget in it.  Currently the only place is on my latest table branch but it will show you the problem. http://rawgit.com/dtsnell4/Visualization/GH-1161_Table_Child_Widgets/demos/dermatology.html?src/other/Table

This is really going to be a problem anywhere that JSON.stringify() is used.  Gordon showed me a nice way to deal with it using stringify's "replacer" function...  https://github.com/dtsnell4/Visualization/blob/GH-1161_Table_Child_Widgets/src/other/Table.js#L824

@GordonSmith would it be a good idea to make a global JSON.stringify() function somewhere with the replacer function in it?  I have no idea how often widgets in the data is going to be an issue in the future, but stringify is used quite a bit I'm sure.

**Comment by mlzummo** [comment]
@dtsnell4 we can place that in the utility module we have

**Comment by dtsnell4** [comment]
I agree in theory, but then the utility widget would need to be included everywhere its needed.

**Comment by mlzummo** [comment]
thats what we have been doing ...

**Comment by mlzummo** [comment]
i use it in amcharts

**Comment by dtsnell4** [comment]
For example in this situation, in PropertyEditor.js.  Should Utility.js be required here?  And if it should be required everywhere, why not just require it in Widget.js?

**Comment by mlzummo** [comment]
because you cant just require it in the base you have to require it in the same module you use it

**Comment by dtsnell4** [comment]
Closed via https://github.com/hpcc-systems/Visualization/pull/1237
