### ISSUE TITLE
Sorting table with fixed header throws exception

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#1292]
http://rawgit.com/hpcc-systems/Visualization/candidate-1.10.0/demos/dermatology.html?src/other/Table&fixedHeader=true

Sort the long column twice:  ```Uncaught TypeError: Cannot read property 'offsetWidth' of undefined```

**Comment by dtsnell4** [comment]
@GordonSmith I cannot reproduce this error.  Could there be something more?  Maybe it was fixed via a recent PR?

**Comment by GordonSmith** [comment]
Maybe it was fixed - or I was using my candidate branch by mistake.
