### ISSUE TITLE
dinesh_1111_02 not rendering in 1.10

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1305]
issue is caused becuase .data is blank being passed into the widget via the marshaller

**Comment by mlzummo** [comment]
i think this is caused by the new DB class

**Comment by GordonSmith** [comment]
Is it blank or an empty array?  .data([]) or .data("")

**Comment by mlzummo** [comment]
@GordonSmith its a empty array ... if you have any ideas let me know right now im back tracking through everyfunction (and there is a lot)

**Comment by GordonSmith** [comment]
Is it throwing an exception - if so should be easy enough to work out why?

**Comment by mlzummo** [comment]
@GordonSmith no exceptions, but the .db object has an empty array as well ...

**Comment by GordonSmith** [comment]
ok so its the marshaller that not getting the data into the widget correctly...

**Comment by mlzummo** [comment]
@GordonSmith correct

**Comment by mlzummo** [comment]
closing as working in current version of viz
