### ISSUE TITLE
The Maps for ACC need pins that can have icons/text applied to them

### ISSUE THREAD

**Issue by jbrundage** [hpcc-systems/Visualization#1306]

**Comment by GordonSmith** [comment]
@jbrundage - @mlzummo discussed this a bit before I went on vacation.  There are some "speed" considerations especially with the new maps, as they can zoom + scroll without re-rendering for the most part!  The new pins will need to do the same.

**Comment by jbrundage** [comment]
@GordonSmith Take a look at my code change and example in #1307. If we keep these things rendering in SVG it should address your above concerns.

**Comment by mlzummo** [comment]
need to add support for multiline text

**Comment by jbrundage** [comment]
@GordonSmith Can we target a closer milestone for this issue? I'll need it in the first steps of integration with ACC

**Comment by GordonSmith** [comment]
FYI 1.12.0-rc1 was released today and it only has one change the dynamic loader.

**Comment by jbrundage** [comment]
@GordonSmith This is the needed enhancement we discussed on the phone this morning.
