### ISSUE TITLE
1.10 issues (megachart and marshaller?)

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1308]
![image](https://cloud.githubusercontent.com/assets/1057527/12023674/b89525f2-ad69-11e5-83ce-7b12e0d21a2e.png)

**Comment by mlzummo** [comment]
clipping on bottom and has a column in the dataset

**Comment by mlzummo** [comment]
the clipping is caused by css issue

**Comment by GordonSmith** [comment]
@mlzummo Can you add a ref to the other issue and I will close this.

**Comment by mlzummo** [comment]
ref: https://github.com/hpcc-systems/DSP/issues/900
