### ISSUE TITLE
Table:  Doesn't shrink column width as cell data changes

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#1332]
Load a table:
```
  table
    .columns(["a", "b", "c"])
    .data([["aaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaa"]])
    .render()
    .data([["a", "a", "a"]])
    .render()
  ;
```
And the columns will still be "wide" to accommodate the previous values.

**Comment by jbrundage** [comment]
So the widths need to be recalculated within update, but not within every call to update.

It seems like widgets in general need the capability of flagging some publish parameters (or data in this case) as "widget needs to recalculate its dimensions" when that publish param (or data) value changes.

**Comment by GordonSmith** [comment]
Prior to having the ability to embed widgets, the cells would have just "shrunk" naturally - I will need to see what the performance is like simply recalculating during each update (they don't happen that often)
