### ISSUE TITLE
Marshaller vertex/text item(0) needs to be "blank" instead of saying undefined when empty

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1339]

**Comment by GordonSmith** [comment]
@mlzummo Does: https://github.com/hpcc-systems/Visualization/pull/1366  fix this?

**Comment by mlzummo** [comment]
this -> https://github.com/hpcc-systems/DSP/issues/906

**Comment by mlzummo** [comment]
9697184	2727274259	0	ACCORDIA LIFE AND ANNUITY COMPANY  still shows undefined and thats becuase the field is blank coming from hipie ... we can either make it so that ifs blank it shows blank instead of undefined ... or ... idk .... your call on @GordonSmith

**Comment by mlzummo** [comment]
function getVertex(item, origItem) {
            var id = "uid_" + item[0];
            var retVal = vertexMap[id];
            if (!retVal) {
                retVal = new graph.Vertex()
                    .faChar((context.icon && context.icon.faChar ? faCharFix(context.icon.faChar) : "\uf128"))
                    .text(item[1])
                ;
                retVal.__hpcc_uid = item[0];
                vertexMap[id] = retVal;
                vertices.push(retVal);
            }

**Comment by mlzummo** [comment]
item[1] is undefined becuase its blank in the data .... this is cuased by the mapping ... if we can make it blank that would be good

**Comment by mlzummo** [comment]
i would just do item[1] || ""

**Comment by mlzummo** [comment]
item looks like this:


["3954133078", undefined, undefined]
HipieDDL.js:275 ["613566594", undefined, undefined]
HipieDDL.js:275 ["1725326693", undefined, undefined]
HipieDDL.js:275 [3954133078, "AVIVA USA CORPORATION", 3]

and item[1] is the name where its suppose to display it ... but as u can see we have some that show undefined

**Comment by mlzummo** [comment]
![image](https://cloud.githubusercontent.com/assets/1057527/12563995/e9dc122a-c37a-11e5-933e-17dff50ac604.png)

**Comment by mlzummo** [comment]
@GordonSmith bump

**Comment by GordonSmith** [comment]
I can confirm that the data is "undefined" coming from the server (its not a mapping issue as such).
