### ISSUE TITLE
need to do form input regression 

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1350]

**Comment by GordonSmith** [comment]
@mlzummo Can you add a description to this issue report, so we know what the issue is?

**Comment by mlzummo** [comment]
the issue as of now for 2 left forms that control the pie if u type nothign in the second one and say Ciaz in the first it just shows the 1 pie wedge ... and if u do the second then it over-rides it ... but if u erase both an do it in the right order thing sseems to work correctly "the second box to the far left second to the left u would type Q1)  but we are only getting partial pie charts ( drea can show this much easier)
