### ISSUE TITLE
Cell's "indicateTheseIds" publish param doesn't adapt to element ID overrides from marshaller

### ISSUE THREAD

**Issue by jbrundage** [hpcc-systems/Visualization#1354]

**Comment by GordonSmith** [comment]
@jbrundage I am not sure I understand what the issue is?  Is it a 1.10 or beyond?

**Comment by jbrundage** [comment]
The IDs that are given to widget.indicateTheseIds( ... ) are the original "_w##" IDs. It seems that the IDs are overwritten by IDs provided in the DDL and/or serialization string.

The "indicateTheseIds" publish param was added in 1.8.0. The bug likely exists there as well.

**Comment by jbrundage** [comment]
"indicateTheseIds" should not be a publish param... it needs to be recalculated when deserializing
