### ISSUE TITLE
IE10 Performance Issues (Profiler Screen Shot)

### ISSUE THREAD

**Issue by jbrundage** [hpcc-systems/Visualization#1382]
IE10 is very sluggish

![image](https://cloud.githubusercontent.com/assets/1891935/12524760/67dcd808-c12d-11e5-8828-87fb73afb7f4.png)

**Comment by jbrundage** [comment]
The profile was run while clicking on a bar chart that creates another bar chart (in the DASH application)

**Comment by jbrundage** [comment]
@GordonSmith This event is firing hundreds of times per second in IE9 and IE10. It's causing some major performance issues.
https://github.com/hpcc-systems/Visualization/blob/master/src/common/Platform.js#L79

**Comment by GordonSmith** [comment]
This is "trick" which enables us to give the illusion of placing a regular HTML chart inside a SVG chart.

In practice this means a chart inside a SVG surface - so I suspect this  could be ompitimzed out for the majority of cases (we wouldn't see it in the profile normally as its a polyfil - which is also needed for the C3 charts).

**Comment by jbrundage** [comment]
@GordonSmith I see! But it's causing extreme performance issues in IE9 and IE10.

**Comment by GordonSmith** [comment]
It should really only come into play in the Graph Marshaller?
