### ISSUE TITLE
c3 pie/cell/grid widget not resizing c3 pie chart correctly on smaller window sizes

### ISSUE THREAD

**Issue by mzummo** [hpcc-systems/Visualization#1405]

**Comment by mlzummo** [comment]
firefox only

**Comment by mlzummo** [comment]
see if we can find a fix to get c3 to try to resize itself again ... ??

**Comment by mlzummo** [comment]
this actually has to do with the legend and the position on load ... it isnt calculating width correctly ... if u set it to show on bottom everything shows fine on the DASH panel ... loooking at other fixes

**Comment by mlzummo** [comment]
http://c3js.org/samples/legend_custom.html

**Comment by mlzummo** [comment]
https://github.com/masayuki0812/c3/pull/763

**Comment by GordonSmith** [comment]
@mlzummo Is this only an issue when C3 is showing its own legend?  Is the solution to only show the pie in the mega chart with our legend?

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
