### ISSUE TITLE
c3 (remove selection on data/column reload PP)?

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1406]

**Comment by mlzummo** [comment]
need a pp to clear selections?

**Comment by GordonSmith** [comment]
At the moment it removes old columns and meges new ones in (so the animation is nice) - is this going to ditch that?

**Comment by mlzummo** [comment]
@GordonSmith it be a Publish Param to just remove the selections so no it shouldnt

**Comment by GordonSmith** [comment]
This has been resolved.
