### ISSUE TITLE
IE9 (possibley 10) need to modify stye attr/pp so we dont get :"nullpx"

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1410]
IE9 (possibley 10) need to modify stye attr/pp so we dont get nullpx

**Comment by jbrundage** [comment]
@mlzummo Look @ this on monday :)

**Comment by GordonSmith** [comment]
I found some instances of this - turns out we are sending nullpx to all browsers, its just IE9/10 report them as errors which is why we see them!

**Comment by jbrundage** [comment]
@GordonSmith How should this be handled? My assumption is that each location where this may be a problem should be wrapped in a conditional.

**Comment by GordonSmith** [comment]
@jbrundage I would only fix where it is happening - the pattern I use is:
```
    .attr("someAttr", this.someProp_exists() ? this.someProp() + "px" : null);
```
But you are correct for any "optional" PP we should be checking if they are null prior to slapping a "px" onto the end...
