### ISSUE TITLE
gulp lint failing on use strict everywhere now locally (and other console log errors in UTests)

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1418]

**Comment by GordonSmith** [comment]
Update your npm repos.

**Comment by mlzummo** [comment]
src\chart\Column.js
  line 1  col 1  Use the function form of "use strict".

  ‼  1 warning


src\chart\Gantt.js
  line 1  col 1  Use the function form of "use strict".

  ‼  1 warning


src\chart\Line.js
  line 1  col 1  Use the function form of "use strict".

  ‼  1 warning


src\chart\MultiChart.js
  line 1  col 1  Use the function form of "use strict".

  ‼  1 warning


src\chart\MultiChartSurface.js
  line 1  col 1  Use the function form of "use strict".

  ‼  1 warning
