### ISSUE TITLE
Visualization Graph marshaller Modification in Load and Save functionality

### ISSUE THREAD

**Issue by prakash-sukumar** [hpcc-systems/Visualization#142]
@jchambers-ln The code modification which we discussed in the call with Gordon.
Code need to be implemented breaking down the load and save function into which it should accept the Json string and have an ability to insert the new chart into the canvas and once added it should have the ability to save the charts with new one.

**Comment by GordonSmith** [comment]
I am going to break this into two issues, this one will be:
* Allow user to get/set the serialization string for a given DDL/Marshaller instance.
* Allow the user to specify which attributes they want to serialize.

The other is here:  https://github.com/hpcc-systems/Visualization/issues/143

Note:  The serialize/deserialize support for widgets (whether created with a DDL or JavaScript)  is only for existing widgets - the serialzier won't be responsible for re-creating the widgets - that will still need to be done within the DDL or JavaScript.
