### ISSUE TITLE
PP for multichart/megachart disable dropdown for changing charts (or other buttons)?

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1428]

**Comment by mlzummo** [comment]
@GordonSmith

**Comment by mlzummo** [comment]
@GordonSmith this is for maggie and Ryan Blackwood

**Comment by mlzummo** [comment]
if we use a PP we dont have to worry about a marshaller coming in and redoing the data hide .... (could be part of the second serialization string thing we mentioned too?)

**Comment by GordonSmith** [comment]
@mlzummo They exist already:
![image](https://cloud.githubusercontent.com/assets/966863/12741211/46b42ab2-c972-11e5-80e9-e4624070e253.png)
