### ISSUE TITLE
database.js when mapping states FL vs FLorida

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1429]
function isUSState(cell) {
        return ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "AS", "DC", "FM", "GU", "MH", "MP", "PW", "PR", "VI"].indexOf(String(cell).toUpperCase()) >= 0;
    }

neeed to be able to map FL and Florida as the same state (in table coming from hippie Data) -> with or without preference to how it shows FL vs FLorida

**Comment by mlzummo** [comment]
@GordonSmith this is for maggie and Ryan Blackwood

**Comment by GordonSmith** [comment]
@mlzummo the above code is only used in my demo "DataAnalyst" as far as I know.  And they will need to use the two letter code for it to work with HIPIE

**Comment by mlzummo** [comment]
@GordonSmith can we reopen this and discuss this with the person who requested this option

**Comment by GordonSmith** [comment]
This is something which is trivial to do externally to the widget - and even easier to do at the data processing layer.
