### ISSUE TITLE
on dermatology getting this error sometimes:

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1431]

**Comment by mlzummo** [comment]
in propertyEXt:
http://localhost:8080/demos/dermatology.html?src/marshaller/HTML.wu&ddlUrl=http%3A%2F%2F10.241.100.157%3A8010%2FWsWorkunits%2FWUResult.json%3FWuid%3DW20160128-140334%26ResultName%3Dblacry01_nacciidrisk_Comp_Ins2100_DDL%26SuppressXmlSchema%3Dtrue&surfacePadding=0

**Comment by GordonSmith** [comment]
@mlzummo You fotgot to say what the error was and how to reproduce it.

**Comment by mlzummo** [comment]
@GordonSmith 

PropertyExt.js:34 Invalid value for 'paletteID':  undefined expected setMeta.checkedAssign @ PropertyExt.js:34(anonymous function) @ PropertyExt.js:197(anonymous function) @ HipieDDL.js:565(anonymous function) @ HipieDDL.js:760context.execCb @ require.js:1665Module.check @ require.js:874(anonymous function) @ require.js:1121(anonymous function) @ require.js:132(anonymous function) @ require.js:1171each @ require.js:57Module.emit @ require.js:1170Module.check @ require.js:925(anonymous function) @ require.js:1121(anonymous function) @ require.js:132(anonymous function) @ require.js:1171each @ require.js:57Module.emit @ require.js:1170Module.check @ require.js:925(anonymous function) @ require.js:1121(anonymous function) @ require.js:132(anonymous function) @ require.js:1171each @ require.js:57Module.emit @ require.js:1170Module.check @ require.js:925(anonymous function) @ require.js:1121(anonymous function) @ require.js:132(anonymous function) @ require.js:1171each @ require.js:57Module.emit @ require.js:1170Module.check @ require.js:925(anonymous function) @ require.js:1121(anonymous function) @ require.js:132(anonymous function) @ require.js:1171each @ require.js:57Module.emit @ require.js:1170Module.check @ require.js:925Module.enable @ require.js:1158Module.init @ require.js:782callGetModule @ require.js:1185context.completeLoad @ require.js:1559context.onScriptLoad @ require.js:1686
ChoroplethStates.js:63 Unknown US State:  ,912

**Comment by mlzummo** [comment]
@GordonSmith 
invalid value for 'paletteID':  undefined expected set as well ... probably just need a few if statements

**Comment by GordonSmith** [comment]
@mlzummo Can you retest with current version I am no longer seeing it and think it is now resolved...

**Comment by GordonSmith** [comment]
Please reopen if its still an issue.
