### ISSUE TITLE
C3 Charts Pending

### ISSUE THREAD

**Issue by prakash-sukumar** [hpcc-systems/Visualization#144]
Below charts are not available in C3 
•	Horizontal Bar / Column Chart
•	Table Widget 
•	Donut Chart
•	Gauge Chart  
•	Document Widget 
it needs to be implemented in C3.

**Comment by senthilkumar2githup** [comment]
C3 based Horizontal bar and Donut chart is sufficient.

**Comment by GordonSmith** [comment]
I don't think there is a C3 Table Chart?
Also I am not sure what you mean by "Document Widget"?

**Comment by prakash-sukumar** [comment]
Horizontal Bar / Column , Donut Charts need to be implemented in C3. other charts are not needed.
