### ISSUE TITLE
add showColumns() back to PE (true/fasle) for dermatology purpose

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1448]
PropEditor:
- [ ] re-enable columns, default to false.
- [ ] enable field by default.

**Comment by GordonSmith** [comment]
PropEditor:
- [ ] re-enable columns, default to false.
- [ ] enable field by default.

**Comment by GordonSmith** [comment]
Having fields default to true is a lot of noise in the derm tree, for occasional use.
