### ISSUE TITLE
Dash issue CAIDMFLDCFScoreDetail_MZ (integration)

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1450]
Uncaught TypeError: widget.publishedProperties is not a functiondiscover @ Persist.js:11
widgetWalker @ Persist.js:33(anonymous function) @ Persist.js:45widgetWalker @ Persist.js:44widgetWalker @ Persist.js:38widgetWalker @ Persist.js:38(anonymous function) @ Persist.js:57widgetArrayWalker @ Persist.js:56HTML.render @ HTML.js:78(anonymous function) @ sideeffects.js:74(anonymous function) @ Persist.js:266

i successfully created this dashboard and then resaved the layout and then this happened when trying to reopen

**Comment by mlzummo** [comment]
need to check and see if (orig issue happens with c3 pie with c3 pie fix too by saving it to use C3 on default in serialization string)

**Comment by GordonSmith** [comment]
Dash was created with old RC version 1.10.0 - please recreate and re-test

**Comment by mlzummo** [comment]
@GordonSmith this seemed to work second time around

**Comment by GordonSmith** [comment]
Was your cache old maybe?
