### ISSUE TITLE
how come WU/DDL forms dont use dropdowns for selecting data (pre select unique options to select)

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1451]

**Comment by GordonSmith** [comment]
More info - not sure I follow?

**Comment by mlzummo** [comment]
@jchambers-ln would be nice to have a dropdownlist instead of text fields on filters (so we know what values we can type in there) (unique vals)

**Comment by GordonSmith** [comment]
Hippie can populate that info for us (input type select)...
