### ISSUE TITLE
add showAllValueLabels to column chart on amchart ( so none are hidden if cant fit)

### ISSUE THREAD

**Issue by mzummo** [hpcc-systems/Visualization#1453]

**Comment by mlzummo** [comment]
so that all labels will show even if they cant phsyically fit (can adjust size of container then)

**Comment by mlzummo** [comment]
waiting to hear back from amcharts

**Comment by mlzummo** [comment]
need to check amcharts email and get new PR out

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
