### ISSUE TITLE
Utility needs a logging object

### ISSUE THREAD

**Issue by jbrundage** [hpcc-systems/Visualization#1455]
A logging object in utility could take a lot of pain out of the troubleshooting process (particularly within the marshaller and persist logic).

Ideally it would keep a log of actions with timestamps and render the results in a modal containing an interactive Gantt chart to display the details of each action.

**Comment by GordonSmith** [comment]
Make sure to use a common log format.  And it needs to be disabled by default, but easily enabled via URL switch (like __hpcc_debug)

**Comment by GordonSmith** [comment]
It does now
