### ISSUE TITLE
create new sideeffects and front/backend code for deleting and temp dropping serialization

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1456]

**Comment by GordonSmith** [comment]
1. It should also allow the user to specify which version of the framework to use.
2. They should also be able to reset on a per widget basis.
Note:  For 2 above - serialize the current dash to an obect - remove that widget from the serialization - deserialize it back (might even work!)

**Comment by GordonSmith** [comment]
Issue moved to [hpcc-systems/DSP #1321](https://github.com/hpcc-systems/DSP/issues/1321) via [**ZenHub.io**](https://www.zenhub.io/)
