### ISSUE TITLE
Table widget default styling - currently too much space is wasted

### ISSUE THREAD

**Issue by jbrundage** [hpcc-systems/Visualization#1465]
The Table widget pagination takes up too much space (it could optionally be moved into the Toolbar widget).

The styles in general could be tightened up to gain more real estate.

**Comment by GordonSmith** [comment]
@jbrundage It could be that pagination and table filtering could be combined into a new "look"?  (is pagination simply a special type of filter? - sounds life over engineering)

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
