### ISSUE TITLE
dash_filtertest_01 comms issue

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1466]
dash_filter_test_01

HipieDDL.js:1259 Comms Error:
DataSource.prototype.fetchData
TypeError: context._resultNameCache[item.from].filter is not a function
Comms.js:237 Request pending (55 sec):  http://172.23.40.63:9190/DSP/dev-dashboard/proxy-WUResult.do?jsonp=jsonp_ca…e&SuppressXmlSchema=true&Start=0&Count=-1&IP=216.19.105.2&PORT=18010&PATH=
Comms.js:237 Request pending (50 sec):  http://172.23.40.63:9190/DSP/dev-dashboard/proxy-WUResult.do?jsonp=jsonp_ca…e&SuppressXmlSchema=true&Start=0&Count=-1&IP=216.19.105.2&PORT=18010&PATH=

**Comment by mlzummo** [comment]
dash_filter_test_02 seems to work @dineshshetye whts the diff between the 2?

**Comment by mlzummo** [comment]
fixed

**Comment by jchambers-ln** [comment]
@mlzummo @GordonSmith is this fix in 1.10.6?
