### ISSUE TITLE
DSP BUG josephDemo2 (integration)

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1467]
even with just DDL no serialization string

Invalid value for 'paletteID':  undefined expected set propertyext.js: 34
Unknown Property:  charttype
Invalid value for 'orientation':  [object Object] expected set line 34
Unknown Property:  charttype
Invalid value for 'orientation':  [object Object] expected set line 34

**Comment by mlzummo** [comment]
@GordonSmith these are expected?

**Comment by GordonSmith** [comment]
Not expected no - but not necessarily real errors.

**Comment by GordonSmith** [comment]
Dup of:  https://github.com/hpcc-systems/Visualization/issues/1431
