### ISSUE TITLE
1.8 to 1.10 searialization compatability Google chart

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#1468]
in JosephDemo02 on integration the layoutsetting was defined using 1.8.4 Viz and under 1.8.4 it will load "Average Depature Delay By Airport" as a google chart as defined, however in the 1.10-rc7 on integration it is defaulting to amchart.

**Comment by GordonSmith** [comment]
@jbrundage Can you take a look, I am travelling today...

**Comment by mlzummo** [comment]
@jchambers-ln in my serialization string and in the DDL i see AMCHARTS as being defined (which is the default unless the serialization string is used to override) ... i can look at this more with you and take a look at the serialization string/saving

**Comment by mlzummo** [comment]
"title": "Average Depature Delay By Airport",
              "chartType": "AM_BAR",

**Comment by GordonSmith** [comment]
@jchambers-ln Can you confirm that your orig chart is actually a Google_Bar (or recreate in dev and let me view in my regression tool?)

**Comment by GordonSmith** [comment]
Please re-open if its still an issue.
