### ISSUE TITLE
1.8 to 1.10 difference

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#1469]
JosephDemo02 on integration 
 
on 1.8 you click "Average Departure Delay By Year" and then select a state in "Depature Delay" and "Average Arrival Delay by airport" is populated, then you click on a new year in "Average Departure Delay By Year" the the state stays selected in " "Depature Delay"  and "Average Arrival Delay by airport" is updated

on 1.10-rc7 you click "Average Departure Delay By Year" and then select a state in "Depature Delay" and "Average Arrival Delay by airport" is populated, but now if you choose a new year in "Average Departure Delay By Year" then you loose the state selection in "Depature Delay".

in the attached video I accidentally showed departure on 1.8 and arrival on 1.10 but the same thing occurs on departure on 1.10 so use the video to better describe what I am talking about. 

The configuration is "Average Departure Delay By Year" updates both "Depature Delay" and "Average Depature Delay By Airport" and  "Depature Delay" updates only "Average Depature Delay By Airport"
[Chambers, Joseph (RIS-ATL) - Friday, February 05, 2016 3.24.39 PM.zip](https://github.com/hpcc-systems/Visualization/files/119823/Chambers.Joseph.RIS-ATL.-.Friday.February.05.2016.3.24.39.PM.zip)

**Comment by GordonSmith** [comment]
@jchambers-ln I have made this an optional "feature" and defaulted it to the old behavior,
