### ISSUE TITLE
div heigh isnt being set correctly

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1471]
![image](https://cloud.githubusercontent.com/assets/1057527/12858456/4e3748ba-cc1e-11e5-973f-94a75f186f99.png)

**Comment by mlzummo** [comment]
https://github.com/hpcc-systems/DSP/blob/73bc91138d61442b8cbc31de6f835d7c3312dc66/DSP/src/main/webapp/js/Visualization/dist/hpcc-viz-layout.js#L1766   could fix here

**Comment by mlzummo** [comment]
https://github.com/hpcc-systems/DSP/issues/959

**Comment by mlzummo** [comment]
layout/grid.js adding this._parentElement.style("height", "inherit"); to fix as well.... should we do width?

we have 3 options to fix this

**Comment by GordonSmith** [comment]
I don't think the viz framework can simply set ``` this._parentElement.style("height", "inherit")``` when the owning element is a _non_ widget (since we have no idea what it would be inheriting from...)

**Comment by mlzummo** [comment]
@jchambers-ln @dineshshetye @GordonSmith 
we can fix this in CSS then with 2 diff ways ... and should this parent div be classed (DSP level here)

**Comment by GordonSmith** [comment]
This should simply be fixed in the DSP - its a requirement of the widgets that the div has a height that does not equate to 0px
