### ISSUE TITLE
if fit to width

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#1472]
if you have 1.8 derm with fit to width defined then in 1.10 and 1.8 DSP isn't setting the DIV height correctly.  Matt is aware and investigating.

**Comment by mlzummo** [comment]
{mlzummo}/{DSP}#959

**Comment by mlzummo** [comment]
related to this: https://github.com/hpcc-systems/DSP/issues/959

**Comment by GordonSmith** [comment]
The ```div``` the dashboard is being placed into needs to alter its height settings.
