### ISSUE TITLE
1.8.4 D3.js pie error

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#1496]
Hari set what was rendered as a AM_PIE orginally to Word Cloud using the layout designer and the dashboard would no longer render with the below JS error.

TypeError: array is undefined
var i = -1, n = array.length, a, b, c;
d3.js (line 87, col 17)

	
[PDEComparisonReport.zip](https://github.com/hpcc-systems/Visualization/files/127093/PDEComparisonReport.zip)

Can you validate this on 1.10 I don't think it has to be this particular composition.

**Comment by GordonSmith** [comment]
@jchambers-ln If you can provide the persist string for this dash?

**Comment by GordonSmith** [comment]
Works on latest sources
