### ISSUE TITLE
Hover over text on the bar chart is not rendering correctly for date fields

### ISSUE THREAD

**Issue by dineshshetye** [hpcc-systems/Visualization#1498]
The hover over text on the bar chart is not rendering correctly for date fields if the date is in YYYY-MM-DD format in the dataset.

![image](https://cloud.githubusercontent.com/assets/1731313/13013557/ed710498-d17d-11e5-9e88-b12dbc83a24a.png)

![image](https://cloud.githubusercontent.com/assets/1731313/13013262/bfffc0c2-d17c-11e5-8b06-32115a21281b.png)

**Comment by GordonSmith** [comment]
@dineshshetye This has been resolved in:  https://github.com/hpcc-systems/Visualization/pull/1530
