### ISSUE TITLE
Merging updated dashboard (added widget)

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#1505]
@jchambers-ln is this a 1.10.0 or 1.10.2 issue?

**Comment by jchambers-ln** [comment]
If this is the issue from Brenton's email it would be in 1.8 that he ran into the issue on.  I think we could safely make any enhancements in the 1.10.2 sprint though -- yes its annoying and yes it will stop people from wanting to use it but it isn't a production show stopper.
