### ISSUE TITLE
DSP - Deleting the filter after saving the layout still displays the form

### ISSUE THREAD

**Issue by prakash-sukumar** [hpcc-systems/Visualization#1515]
Steps to reproduce
1. Create a widget with filters and run it 
![screenshot 8](https://cloud.githubusercontent.com/assets/7846016/13278134/ff87e988-daf3-11e5-8b16-3c492b23a1b3.png)
![screenshot 9](https://cloud.githubusercontent.com/assets/7846016/13278139/10108fee-daf4-11e5-85d0-47bd25b79e94.png)
2. Do some changes with layout designer and save the layout.
![screenshot 10](https://cloud.githubusercontent.com/assets/7846016/13278147/1e577a2c-daf4-11e5-81fc-45c678c58036.png)
3. Edit the widget and Delete the filters.Run the dashboard.
![screenshot 11](https://cloud.githubusercontent.com/assets/7846016/13278153/27a8b974-daf4-11e5-8e19-fa21e144bef0.png)
4. Marshaller recreates the form widget from dermatology, which is not expected.  
![screenshot 12](https://cloud.githubusercontent.com/assets/7846016/13278157/2fa45232-daf4-11e5-94e1-62093f9ab46f.png)

**Comment by GordonSmith** [comment]
Same issue as:  https://github.com/hpcc-systems/Visualization/issues/1513
