### ISSUE TITLE
DSP - Change chart type after saving the layout

### ISSUE THREAD

**Issue by prakash-sukumar** [hpcc-systems/Visualization#1518]
Steps to reproduce.
1.Create a chart and run the dashboard
2.Do some changes in layout designer and save the layout.
![screenshot 19](https://cloud.githubusercontent.com/assets/7846016/13278637/e923f386-daf7-11e5-93a3-9f4fdf23b557.png)

3.Edit the widget and change the chart type 
![screenshot 21](https://cloud.githubusercontent.com/assets/7846016/13278641/f094cba4-daf7-11e5-9beb-abc0a2855eba.png)
4.Marshaller restores the chart type from the dermatology string. 
![screenshot 20](https://cloud.githubusercontent.com/assets/7846016/13278645/fde8e4fc-daf7-11e5-81dc-19f3c20096cd.png)

**Comment by GordonSmith** [comment]
This is actually the same issue as:  https://github.com/hpcc-systems/Visualization/issues/1517
