### ISSUE TITLE
Problem with table chart

### ISSUE THREAD

**Issue by prakash-sukumar** [hpcc-systems/Visualization#154]
When we render the Table chart with some data it renders correctly for the first time. But if we change the chart to some other type and change back again to table chart the data is not shown correctly. It shows some javascript functions appended in the extra columns.

**Comment by GordonSmith** [comment]
Is this inside a Multi Chart Surface?

**Comment by prakash-sukumar** [comment]
Yes Gordon. When we render a table chart using Multi Chart Surface and change to some other chart type and change back again to table chart the problem occurs.
