### ISSUE TITLE
Grid Layout designMode needs ability to prevent cell dragging unless surfaceTitle is grabbed

### ISSUE THREAD

**Issue by jbrundage** [hpcc-systems/Visualization#1546]
Widgets currently can't be interacted with while in designMode. Adding a publish param to specify whether or not cell dragging should be draggable only by the title bar will allow the best of both worlds.

**Comment by GordonSmith** [comment]
@jbrundage The PR needs to use the title bar in the MegaChart not Surface.

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
