### ISSUE TITLE
Boolean values are not being shown in Tables.

### ISSUE THREAD

**Issue by jprichard** [hpcc-systems/Visualization#1553]
I have data going into a table where the json looks as follows... "nap_summary": "11", "napindicator": false, "nasindicator": true, "outofstate": false, "haspublicrecordinst": false, "first": 
Is there a way for the table to show these either as the text true/false or put a tick in?

![viz-error1](https://cloud.githubusercontent.com/assets/908650/13505844/125ab184-e149-11e5-82df-deb6c83e9948.png)

**Comment by GordonSmith** [comment]
@jprichard In the property editor you can change the field "type" to Boolean which might help?

**Comment by GordonSmith** [comment]
@jprichard - you will need to point me to an example as I was unable to reproduce locally.

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
