### ISSUE TITLE
amCharts/Gauge does not show endpoint correctly (adds the min to the max it seems for the endpoint)

### ISSUE THREAD

**Issue by pbalwall** [hpcc-systems/Visualization#1555]
This is a issue I have discussed with Matt and he wanted me to create this issue.

I setup a gauge where the min=10, and the max=100, and value=20, but the end displayed was 110

Below is an example
http://rawgit.com/hpcc-systems/Visualization/master/demos/dermatology.html?src/amchart/Gauge&paletteID=default&low=10&high=100&axisLineWidth=0&colorType=a&numBands=2&axisAlpha=0.2&tickAlpha=0.2&valueInterval=20&bottomText=%5B%5Bdata%5D%5D%20km%2Fh

**Comment by GordonSmith** [comment]
A couple of things going on here - but essentially the "bands" values were greater than the low/high values + the valueInterval (for the ticks) causes the guage to be larger than the low/high.

I am making the following changes:  The range bands will be a % of the low high and defaulting valueINterval to null.
