### ISSUE TITLE
amCharts:Gauge and amCharts:Line do not seem to render correctly (size wrong and other issues) if in a div that is hidden

### ISSUE THREAD

**Issue by pbalwall** [hpcc-systems/Visualization#1556]
This is occurring in Portal. If the .render() method is called within the div is hidden, saw several issues, when this div was eventually displayed
1. gauge size too small
2. amCharts:Line width wrong
3: amCharts:Line leftMargin seemed wrong

This issue did not seem to happen for amCharts:Combo nor c3:Line

**Comment by GordonSmith** [comment]
@pbalwall when the tab is shown (or sized) you should probably call ```widget.resize().render()```?

**Comment by GordonSmith** [comment]
@pbalwall did you confirm if the resize + render fixed the issue after the DIV is unhidden?

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
