### ISSUE TITLE
Marshaller:  Add option to auto submit forms on initial render

### ISSUE THREAD

**Issue by dineshshetye** [hpcc-systems/Visualization#1558]
When you create a FILTER (Local/Global) the form does not auto submit when the dashboard is rendered the first time. If you click the flyout icon and then press the submit button it works.

URL: http://172.23.40.63:9090/DSP_DEV/
Dashboard Name 1:   global_filter_single_wiget
Dashboard Name 2: filter_single_widget

[ddl.txt](https://github.com/hpcc-systems/Visualization/files/163487/ddl.txt)
[Dermatology.txt](https://github.com/hpcc-systems/Visualization/files/163488/Dermatology.txt)

*\* filtersinglewidgetdashboard.dud **

```
ID "f8160821-19c8-4a11-a7d2-cc2c4ed6e4d1";
LABEL filtersinglewidgetdashboard;
AUTHOR shetyedv;
DESCRIPTION "RAMPS - Dashboard Perspective Contract";
CATEGORY VISUALIZE;
VERSION "0.1";
NAME filtersinglewidgetdashboard;
PERMISSIONS
VIEW:PUBLIC;
EDIT:PRIVATE;
RUN:PUBLIC;
END

INPUTS
    DATASET dsInput: MAPBYNAME,OPTIONAL
    FIELD Field1_FilterByServiceType: LABEL("servicetype");
END
END

OUTPUTS
    DATASET dsOutput(dsInput): WUID;
END
VISUALIZE filtersinglewidgetdashboard
      FORM FilterByServiceTypeFORM: TITLE("Filter By Service Type"),SELECTS(*->FilterByServiceType), _flyout("true"),_allowEmptyRequest("true")
    STRING Field1_FilterByServiceType: LABEL("servicetype"),DEFAULT("EC2");
END
      PIE FilterByServiceType(dsOutput{Field1_FilterByServiceType,COUNT}): LABEL(Field1_FilterByServiceType),WEIGHT(COUNT),FILTER(Field1_FilterByServiceType),TITLE("Filter By Service Type"), _charttype("AM_PIE");
END
```

*\* filtersinglewidget.cmp **

```
ID "ff429073-15c1-4263-b152-08058782b732";
NAME filtersinglewidget;
LABEL filter_single_widget;
CATEGORY VISUALIZE;
DESCRIPTION "A template only with Data source input";
VERSION "1.0.0";
AUTHOR shetyedv;
PERMISSIONS
VIEW:PRIVATE;
EDIT:PRIVATE;
RUN:PRIVATE;
END
INSTANCE dashboardrepo.shetyedvdashboardduds.filtersinglewidgetdashboard(Ins002)
    Field1_FilterByServiceType="servicetype"
    dsInput="^Ins001|dsOutput"
END
INSTANCE HIPIE_Plugins.UseDataset.UseDataset(Ins001)
    Structure="string|ip_prefix","string|region","string|servicetype"
    LogicalFilename="~dinesh::aws::amazon_public_ips"
    Method="THOR"
END
```

**Comment by jchambers-ln** [comment]
http://172.23.40.63:9090/DSP_DEV/?composition=10461204-8eb0-4f9e-b4fe-bedef2253984
[JoeTestAircraftDashboard.zip](https://github.com/hpcc-systems/Visualization/files/164004/JoeTestAircraftDashboard.zip)

**Comment by GordonSmith** [comment]
I have posted the required changes to DSP to make this to work here:  https://github.com/hpcc-systems/DSP/issues/1055

I am now going to re-purpose this issue to bring this ability "inside" the marshaller.

**Comment by GordonSmith** [comment]
@jchambers-ln @dineshshetye Questions:
1. Is this still a requirement?
2. Does the order of the form submission matter?
3. Can the forms be submitted in parallel, or do they need to be submitted one at a time?

**Comment by hamiltwp** [comment]
VIZ Version :1.14.8-rc3
HIPIE Version :1.8.2-SNAPSHOT
Two widgets: Table and Pie on integers, 

- [ ] global filter only, for number 4: applies correctly on first load.
- [ ] Global and local combined renders appropriately
- [ ] Without Global, local filters on same column render correctly and independently on initial loading of both widgets
- [ ] Local filters on different columns render as expected.

I don't see a problem with the current Viz Version

**Comment by jchambers-ln** [comment]
@GordonSmith based on @hamiltwp test I believe this has been addressed over time and is working.
