### ISSUE TITLE
Layout designer

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#1561]
in DSP

Open the layout designer with charts filling up all the space, select one then you can never get back to the global designer unless you srink a widget enough that you can click on the grid layer.

**Comment by GordonSmith** [comment]
@jchambers-ln FYI ctrl+click the selected item will give you the same result...  (this issue only happened after we removed the padding grids...)

**Comment by GordonSmith** [comment]
This will also be fixed with:  GH-1546

**Comment by hamiltwp** [comment]
Chart should deselect on any click other than the chart or properties. Such as in whitespace above.
