### ISSUE TITLE
Line chart text jumbled

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#1562]
in default view text in top left had on "Line Data" is jumbled up
![vizissue](https://cloud.githubusercontent.com/assets/1529783/13616286/3f8fb42c-e547-11e5-8358-d3d412855b30.jpg)

**Comment by jchambers-ln** [comment]
Same thing happens for column and Stacked Column these are all amCharts

**Comment by jchambers-ln** [comment]
http://172.23.40.63:9090/DSP_DEV/?composition=10461204-8eb0-4f9e-b4fe-bedef2253984

[JoeTestAircraftDashboard.zip](https://github.com/hpcc-systems/Visualization/files/163995/JoeTestAircraftDashboard.zip)

**Comment by GordonSmith** [comment]
https://github.com/hpcc-systems/Visualization/issues/1557
