### ISSUE TITLE
AM Area chart x-axis is flipped for dates

### ISSUE THREAD

**Issue by TomCharmanODG** [hpcc-systems/Visualization#1563]
See example "Stocks RSI Explorer 2" on dsp-dev.

There are three charts on the left with:
- xAxisType = time
- xAxisTypeTimePattern = %Y%m%d

The two LINE charts handle this fine, and draw sensible axis labels along X. The AM_AREA chart at the bottom arranges the data correctly from Jan-Dec 2006, but the axis labels start at 2007 and go backwards.

(posted this [in DSP](https://github.com/hpcc-systems/DSP/issues/1029) first but I'm guessing it should be here)

**Comment by GordonSmith** [comment]
@TomCharmanODG Can you share that dash so I can take a look?

**Comment by TomCharmanODG** [comment]
Hi Gordon -- the dashboard [is here](https://dsp-dev.risk.regn.net:443/?composition=2afc9da9-9346-4ab3-900f-6db19015e375). The 'oversold vs overbought' chart at the bottom is the one and will appear once you click a bar in the top left chart.

Doesn't look like a dupe of #1516:
* the chart didn't have "sort dates" checked
* checking it didn't change anything (I guess the data was already sorted)
* the data is presenting in the right order, it's just the axis which is wrong

**Comment by GordonSmith** [comment]
@jchambers-ln I don't have access to this environment, can you get the persist string for me to check this with?

**Comment by TomCharmanODG** [comment]
See #1593 -- this may well be fixed at this point but obscured by other issues.

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
