### ISSUE TITLE
Fly out menu is not getting displayed for Map widgets with local and global filters.

### ISSUE THREAD

**Issue by dineshshetye** [hpcc-systems/Visualization#1566]
The flyout menu does not show up on Choropleths in case of local and global filters.
I have created 2 dashboards to show this issue:

URL: http://172.23.40.63:9090/DSP_DEV/
Dashbaord Name: Flyout_Maps
The Attached zips has cmp, dud, ddl and dematology files

[FlyoutMaps.zip](https://github.com/hpcc-systems/Visualization/files/169519/FlyoutMaps.zip)

URL: http://172.23.40.63:9090/DSP_DEV/
Dashbaord Name: FluoutMapsGlobalFilter

[FluoutMapsGlobalFilter.zip](https://github.com/hpcc-systems/Visualization/files/169520/FluoutMapsGlobalFilter.zip)

**Comment by GordonSmith** [comment]
@dineshshetye Is this a 1.10.2 or a 1.14.0 issue (last week or in two weeks)?

**Comment by dineshshetye** [comment]
1.14.0 should be good. We will mark it as a known issue.

**Comment by GordonSmith** [comment]
Resolved by:  https://github.com/hpcc-systems/Visualization/pull/1715
