### ISSUE TITLE
table if no data for last column

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#1570]
if a table as filtered has the last column without data returned then the title cell is rendered but the data cells do not render that cell.

**Comment by GordonSmith** [comment]
@jchambers-ln Can you provide an example to clarify - my reading of the above is "if there is no data in the last column, that cell does not render"?  (or is it all cells do not render?)

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
