### ISSUE TITLE
Table: allow choice of initially selected row(s)

### ISSUE THREAD

**Issue by TomCharmanODG** [hpcc-systems/Visualization#1572]
Dashboards with tables + interactions often end up being empty of charts when initially loaded, because the user needs to click a table. 

An option to choose the initially selected row or rows would avoid this and allow you to choose a 'default' view.

**Comment by GordonSmith** [comment]
The same is true of any widget.  @drealeed Do you allow "default" values for all widgets, or just forms?

**Comment by drealeed** [comment]
Sounds like you're talking about selecting a default value for a filter; right now, this is handled by filtering a widget on a form and specifying the form field defaultl value.

**Comment by dabayliss** [comment]
A more comprehensive implementation of FILTER(?thing) to allow for broader aggregation in the unfiltered case is (IMO) the most elegant solution to most of this.

We could allow a default specified inside the filter statement; but that feels contrived ...

**Comment by drealeed** [comment]
We could build on one of the features being added to support global variables,https://github.com/hpcc-systems/HIPIE/issues/1307. This will be supporting the syntax

     VISUALIZE mydashboard:FILTER(city=GLOBAL.cityname)

This issue only handles supporting assignments that are global variables, but once the syntax is there, we could expand upon it and allow hard-coded default values to be specified as well.

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
