### ISSUE TITLE
Table: stop multiple row selection

### ISSUE THREAD

**Issue by TomCharmanODG** [hpcc-systems/Visualization#1573]
If you're using a table with an interaction, there may be times when your data doesn't aggregate sensibly and you rely on the user choosing one row, and one row only, as a filter.

An option for tables (or for interactions?) to specify that the dashboard should only allow one selection from the table seems like it'd be handy for avoiding this.

(If this belongs in DSP instead of Visualization just let me know and I'll move it)

**Comment by GordonSmith** [comment]
(marked as a bug as all the other vizzies are using "simple" selection)

**Comment by GordonSmith** [comment]
Resolved:  https://github.com/hpcc-systems/Visualization/pull/1597
