### ISSUE TITLE
Table: use cursor:pointer CSS for rows in tables with interactions

### ISSUE THREAD

**Issue by TomCharmanODG** [hpcc-systems/Visualization#1574]
If there's a meaningful effect to clicking on a table, it'd be good to indicate this with a pointer cursor instead of the standard arrow.

**Comment by jprichard** [comment]
Yes!

**Comment by GordonSmith** [comment]
This has been resolved with the generic "yellow" border for all vizzies?

**Comment by TomCharmanODG** [comment]
I don't think highlighting other elements when you hover over a different element necessarily makes you think "I can click this" as much as changing the mouse pointer, but certainly once you get how the DSP works then it makes it very clear. So I'd say it was still worthwhile to make it more new-user-friendly / consistent with general web practices. But not much impact on long-term users of course.

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
