### ISSUE TITLE
Table: allow word wrap within cells

### ISSUE THREAD

**Issue by TomCharmanODG** [hpcc-systems/Visualization#1575]
Tables have white-space:nowrap set at the moment. I suggest an option to turn this off for a table where you have content that would fit a lot better if it was allowed to wrap down.

(I'd say make this the default but I'm assuming there's a reason for the nowrap which I haven't thought of!)

**Comment by GordonSmith** [comment]
Currently can be done at the CSS level.

**Comment by GordonSmith** [comment]
New table on the way.
