### ISSUE TITLE
Tables: format changes to remove 'chart junk'

### ISSUE THREAD

**Issue by TomCharmanODG** [hpcc-systems/Visualization#1576]
Just a few suggestions for the default table CSS that would make the tables less heavy:
- Column headings
  - Un-invert colours (i.e. bold darkgrey on transparent)
  - 2px solid bottom border 
  - 5px left/right padding so that headings line up vertically with content (which has 5px left/right padding)
- Hide vertical gridlines by default
- Right-alignment for numeric data by default (obviously this could be much trickier than the others)

**Comment by GordonSmith** [comment]
@TomCharmanODG This can be done at the "themes" level already - but I do agree that an entire sweep through the widgets with better defaults would be nice _but_ as it stands this would be a breaking change for existing dashboards...

**Comment by GordonSmith** [comment]
New table on the way
