### ISSUE TITLE
Default AxisTypeTimePattern should be %Y%m%d for HPCC dashboard

### ISSUE THREAD

**Issue by TomCharmanODG** [hpcc-systems/Visualization#1577]
HPCC dates are always going to be %Y%m%d as far as I understand; could we default to this for a dashboard that's set up with "HPCC cluster" as the datasource? (as opposed to static data, where presumably all bets are off)

**Comment by GordonSmith** [comment]
@drealeed Do we have a "date" field type yet?

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
