### ISSUE TITLE
Dashed: Visualization Framework

### ISSUE THREAD

**Issue by anirudh3LOQ** [hpcc-systems/Visualization#1587]
Hello,
I am not sure if you guys are aware of this neat visualization framework - Dashed - that airbnb open sourced. Please have a look and see if you can fork it rather than developing another framework from scratch. They have a pretty neat data model and it works with and DB. 

We are currently experimenting with Dashed and accessing the data in HPCC via the JDBC driver. 

https://github.com/airbnb/dashed

Hope you consider forking from this Dashed as they have quite a few advanced features.

**Comment by GordonSmith** [comment]
Thanks for the link...

**Comment by GordonSmith** [comment]
Its missing some key functionality from the Viz point of view (specifically serialization).  It has a bunch of query support, which is also out side of this project.
