### ISSUE TITLE
Table conditional formatting.

### ISSUE THREAD

**Issue by rajunagarajan** [hpcc-systems/Visualization#1588]
I would like to define rules around the values in a cell and do conditional cell coloring in a table.

**Comment by jchambers-ln** [comment]
@GordonSmith @drealeed 
@GordonSmith do you envision this as a dictionary mapping and enhancements to the dermatology to color cells based on the dictionary key->value or do you see this as something to manually define in the dermatology?

@rajunagarajan is this something you want to define through the layout editor or something that you would want to burn into your data?

**Comment by GordonSmith** [comment]
@jchambers-ln I can't see anything beyond some basic capability being achieved at the dermatology layer?  Short of allowing per cell meta data (__cell_back_color) for each field?

**Comment by rajunagarajan** [comment]
@GordonSmith The following are the three different options I would prefer.
1. Based on a Specific cell value, set its color to differentiate High Medium Low (Ex. if value = x, #color, value = y, #color2, Value = z, #color3)
2. Based on a specific cell range (between 0 - 30, 30 - 60, > 60 or < 100) etc
3. Set another cell color based on another metric. (Set Cell A if Cell B is like eiher type 1 or type 2 from above scneario)

**Comment by GordonSmith** [comment]
Question:  Can we push the style string into the ECL?  
IOW if they wanted to style a column "lname", the could add a column called "lname_style" (which would not be selected in DSP for display, but would exist in the data), but would contain things like ```background-color: red; font-size:22px```
Then in the dermatology layer (using VIz II scheme) I can add a mechanism to nominate a style column for the actual column?
