### ISSUE TITLE
Chart legends are hidden after re-running dashboard

### ISSUE THREAD

**Issue by TomCharmanODG** [hpcc-systems/Visualization#1589]
1. Give chart in dashboard legend on right -> legend appears as normal
2. Re-run dashboard -> can't see legend any more
3. Change legend to be any of the other options -> chart margins will adjust to show legend
4. Re-run again -> again the chart will be sitting on top of the legend and you'll need to change the legend position again to see it

**Comment by GordonSmith** [comment]
@TomCharmanODG I am hopeful that the changes made to:  https://github.com/hpcc-systems/Visualization/pull/1602 will also resolve this issue.

**Comment by GordonSmith** [comment]
@TomCharmanODG Please re-open if this is still an issue.
