### ISSUE TITLE
AM_SCATTER with scatterType = bubble: no way to choose radius column

### ISSUE THREAD

**Issue by TomCharmanODG** [hpcc-systems/Visualization#1590]
The AM_SCATTER chart has a bubble option, but it seems like it just uses the y axis value to pick the size of the bubbles, instead of allowing the user to pick a column from the data.

If I'm right about where it's getting the bubble sizes from, it seems like the scale for the radius sizes is calculated differently for each series, making the bubbles impossible to compare across series (should be one bubble-size-scale for the whole chart).

**Comment by GordonSmith** [comment]
(Not to self) This can now be solved with the Viz II way of doing things...

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
