### ISSUE TITLE
Line (amChart) - Time axes don't work very well

### ISSUE THREAD

**Issue by TomCharmanODG** [hpcc-systems/Visualization#1593]
As of the recent update, setting an x-axis to 'time' and specifying the appropriate time format doesn't create the nice axis labels it used to (i.e. clever switching between year and months as needed, not just spitting out "YYYYmmdd" format labels as if it was an ordinal).

This is what the same thing does now: it's a bit of a mess but I think I see two main problems:
- It has sensibly identified that the data spans a year and has formatted the labels appropriately (i.e. first label is bold which would be for a year) but the actual text coming through is just the values from the data
- It seems to have grouped all the data into months (i.e. the data in this screenshot spans a year, so the distinct x values visible seem like they represent months).

![image](https://cloud.githubusercontent.com/assets/17152326/14098263/b12b72c2-f5c5-11e5-8703-87e44a9bea62.png)

**Comment by GordonSmith** [comment]
@TomCharmanODG Do you have an example I can look at?

**Comment by GordonSmith** [comment]
@TomCharmanODG (bump)

**Comment by GordonSmith** [comment]
@TomCharmanODG - this looks like the x-axis time pattern string is not set correctly and its simply using "ordinal" mode?

**Comment by TomCharmanODG** [comment]
I can reproduce this [on the demo page](http://rawgit.com/GordonSmith/Visualization/future-1.14.x/demos/dermatology.html?src/amchart/Line.simple&xAxisTypeTimePattern=%25Y%25m%25d&xAxisType=time)... just switched the data for what's below and it does the same thing with the axis labels.

    [["20030101",75,68,65],["20030401",45,55,52],["20030701",98,92,90],["20031001",66,60,72]]

![image](https://cloud.githubusercontent.com/assets/17152326/17794067/a4c1aa0c-65ef-11e6-9968-f44f39ebe9d1.png)

**Comment by TomCharmanODG** [comment]
I believe the correct labels in this case (from memory) were: 2003 (the bold one), February, March, April, May, June, July, August, September, October

**Comment by GordonSmith** [comment]
@TomCharmanODG you need to change the xAxisTickFormat to "%d %B, %Y":  http://rawgit.com/GordonSmith/Visualization/future-1.14.x/demos/dermatology.html?src/amchart/Line.simple&xAxisTypeTimePattern=%25Y%25m%25d&xAxisType=time&xAxisTickFormat=%25d%20%25B%2C%20%25Y

The way it works is:
* xAxisTypeTimePattern is used to parse the date/time string into a JS DateTime Structure
* xAxisTickFormat is used to format that structure into human readable string.

**Comment by TomCharmanODG** [comment]
Oh, right! So [the old amCharts clever, dynamic date format](https://www.amcharts.com/kbase/time-series-chart-the-great-advantages-of-parsing-dates/) was killed? If it were possible to bring it back and just have the axis tickformat override it when specified, I'd vote for that as it seemed really useful.

**Comment by GordonSmith** [comment]
@TomCharmanODG - I don't know (@mlzummo may have some comments as the original author).  I suspect we wanted it to work the same as the [HPCC Charts](http://rawgit.com/GordonSmith/Visualization/future-1.14.x/demos/dermatology.html?src/chart/Column.timeX&xAxisType=time&xAxisTypeTimePattern=%25Y-%25m-%25dT%25H%3A%25M%3A%25S&yAxisType=linear)?

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
