### ISSUE TITLE
Ability to pass filter & data from one widget as global filters for another dashboard

### ISSUE THREAD

**Issue by indiangolfer** [hpcc-systems/Visualization#1611]
Based on our conversation with Gordon yesterday:  Ability to pass filter & data from one widget as global filters for another dashboard

Ex:  Click on Table chart of one dashboard, extract the filters that were applied to the dashboard, and data from the row selected.  Use these as global filters for the next dashboard.

**Comment by jchambers-ln** [comment]
Required by https://github.com/hpcc-systems/DSR/issues/29

**Comment by GordonSmith** [comment]
Complete
