### ISSUE TITLE
Tree Map Widget

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#1624]
http://bl.ocks.org/mbostock/4063582

**Comment by jbrundage** [comment]
@GordonSmith How should this differ from the current Heat Map widget?

**Comment by GordonSmith** [comment]
Should have been "Tree Map" which is similar to the sunburst partition, but "boxy"

**Comment by GordonSmith** [comment]
Resolved by:  https://github.com/hpcc-systems/Visualization/pull/1692
