### ISSUE TITLE
Visualization crashes browser when many rows are returned.

### ISSUE THREAD

**Issue by bwood1** [hpcc-systems/Visualization#1627]
When attempting to make a pie chart the WU returned 3730 rows which caused the browser to crash while attempting to draw on screen.

HPCC Connection: four-way
WU: W20160413-141102

**Comment by GordonSmith** [comment]
@bwood1 Was this the AM Chart Pie?

**Comment by bwood1** [comment]
That was the one I tested yes. I did't test any of the other ones.

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
