### ISSUE TITLE
c3 repaint

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#1630]
c3 doesn't seem to repaint with settings from the Layout unless you close out the viz and reload it.

**Comment by GordonSmith** [comment]
@jchambers-ln - this is one of the limitations of the C3 libraries.  Not all of their properties can be changed at runtime.
IMO the time spent fixing this would be better spent duplicating the legend interaction that C3 has in the HPCC charts:
- [ ] Show hide data elements via legend
- [ ] Highlight data elements on hover over legend

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
