### ISSUE TITLE
select box filter

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#1650]
table shape to provide select box.
a alt/text or details that shows the supporting data would be nice also.

**Comment by GordonSmith** [comment]
@jchambers-ln - can you elaborate?  I am not sure what your asking for...

**Comment by jchambers-ln** [comment]
ability to take a table and change it to a select box/drop down list, you will need to choose the column to use as value and the one for label it can be the same.

If the table has more than two columns it would be nice to have an alt text so when you hover over you see the other info so:

if you have
value | Label | desc
1       | car     | a vehicle with 4 wheels
2       | boat   | a vehicle with no wheels


you end up with a html select box 

&lt;select&gt;
  &lt;option value="1"&gt;car&lt;/option&gt;
 &lt;option value="2"&gt;boat&lt;/option&gt;
&lt;/select&gt;

and then some JS magic to add in an alt so when I hover over car I get a little pop out div with "a vheicle with 4 wheels"

**Comment by GordonSmith** [comment]
Resolved with https://github.com/hpcc-systems/Visualization/pull/1697
