### ISSUE TITLE
Ordinal palettte mapping from table widget

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#1669]
Allow a table to be added to the dashboard that isn't shown to the user but is used for ordinal palette mappings

**Comment by GordonSmith** [comment]
Is this to be driven from server side data - or is it a client side dermatology thing?

**Comment by GordonSmith** [comment]
Need two Palette widgets (rainbow + ordinal) which could then replace paletteID in existing widgets.

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
