### ISSUE TITLE
XML tree view

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#1670]
a widget that takes raw xml and displays it as a tree (with +/- expanding nodes) without having to manually map it.

**Comment by jchambers-ln** [comment]
possible candidate but thinking more like windows explorer folder tree 
http://bl.ocks.org/mbostock/1093025
http://bl.ocks.org/herrstucki/5467720

**Comment by GordonSmith** [comment]
@jchambers-ln Is there a milestone project for this issue?

**Comment by GordonSmith** [comment]
@jchambers-ln How is the XML going to be sent to the visualization?

**Comment by jchambers-ln** [comment]
What they requested is the table field would have a blob of xml something like
widget one
id       name
1         test1
2         test2

and when you select test1 it would update the xml widget with the data in
id        XML
1         <xml>yada</xml>
2         <xml>ysada</xml>

and the xml widget would just render the <xml>yada</xml> as a tree.

**Comment by dabayliss** [comment]
XML is NOT one of our standard HIPIE formats. Is XML actually part of the requirement here? Or just part of a solution they have come up with?

My fear is taht they really want a tree and are eventually going to want all the other hipie stuff (colors / icons / paging / sorting etc)

**Comment by GordonSmith** [comment]
@jchambers-ln - any more thoughts?  BTW if they denormalize the XML file to a flat table, they would be able to use the existing tree/dendrogram to achieve this?
![image](https://cloud.githubusercontent.com/assets/966863/17268350/ae04bdc8-561f-11e6-9b36-8551c671111f.png)

**Comment by jchambers-ln** [comment]
This is trully the simplist case All this needs to do is be populated with a blob of XML and parse it into a human viewer widget.  All HIPIE/DSP/DDL will do is tell the widget which column of which dataset has the blob of xml in it.  

So really building off my above comment the dataset would be something like
ID, name, xmlbob

widget one would be all rows with ID, Name as a table, widget two would be filtered on ID and load the xmlblob into the widget.

The use case here is they have parsed out what they feel as important information into a proper dataset but attached the XML as a column of the full entry.
