### ISSUE TITLE
table dermatology delete column

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#1674]
if you modify a table in hipie to remove a column but the derm had been set before there is no way to delete the column definition from the derm.

**Comment by jchambers-ln** [comment]
this may also be related to Jo P's report where his columns didn't line up

**Comment by GordonSmith** [comment]
The following workaround should help:
* In the dermatology editor change the table type to any other widget and then back to table again.  This should have the effect of resetting it.
