### ISSUE TITLE
rename column breaks interaction

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#1675]
if you rename a column that is also a filter on a interaction it breaks the interaction.

**Comment by GordonSmith** [comment]
@jchambers-ln I will test this in conjunction with https://github.com/hpcc-systems/Visualization/issues/1674, but it may not be a Viz issue...  (but it may well be!)

**Comment by GordonSmith** [comment]
@jchambers-ln I believe this is fixed by GH-1674 please reopen if needed.
