### ISSUE TITLE
Search Box and Trigger Button Customization

### ISSUE THREAD

**Issue by albertodesignz** [hpcc-systems/Visualization#1685]
There needs to be an ability to customize the search box pop up and the trigger button. 
This includes 2 elements, the trigger button and search box itself. 

**For the trigger button:**
- Labeling (Need to be able change it from the down arrow to an actual label like "Search Filter")
- Button position (Should be able to place the button anywhere within the widget to optimize visibility)
- Button Styling (Should be able to change size, color and font size)

**For the Search Box**
- Styling (Background color, fonts, font colors, etc)
- Positioning 
- Size of the "box" itself.

**Rationale:**
This will give the Human Factors team ability and flexibility to test and enhance the usability of this key feature.

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
