### ISSUE TITLE
Empty cells in Table widget causes interactions to fail and the table to misalign columns

### ISSUE THREAD

**Issue by jprichard** [hpcc-systems/Visualization#1694]
If there are empty cells it screws both how the table looks and how the interaction values are picked up. In the attached example it picks up the lat/long value instead of the ultiid for the interaction.

![viz1](https://cloud.githubusercontent.com/assets/908650/15371746/ff15d9de-1d0a-11e6-8edc-b4718f6dfe7a.png)

**Comment by jchambers-ln** [comment]
required by https://github.com/hpcc-systems/HIPIE/issues/1633
