### ISSUE TITLE
showChartSelect checkbox not working

### ISSUE THREAD

**Issue by albertodesignz** [hpcc-systems/Visualization#1703]
Unchecking the showChartSelect button does not remove the chart selection from the dropdown in the Dermatology layer. Please review the screenshot
![filters](https://cloud.githubusercontent.com/assets/3629567/15505190/56c55270-2190-11e6-943b-fab2827235af.jpg)

**Comment by jbrundage** [comment]
@GordonSmith the array **slice** in the link below isn't actually affecting the toolbarWidgets (twArr) array and it is preventing **showChartSelect** and **showCSV** from working. Which version of the visualization framework should I create a PR against?

https://github.com/hpcc-systems/Visualization/blob/master/src/composite/MegaChart.js#L136

**Comment by GordonSmith** [comment]
@jbrundage / @mlzummo Please Review
