### ISSUE TITLE
sort based on field defined with ave

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#1711]
Given a thor based viz sorted by average of a column the sort doesn't work right

"mappings": {
                "x": ["uniquecarrier"],
                "y": ["arrdelay_AVE"]
            },
            "id": "Ins020_dsOutput1",
            "sort": ["-arrdelay_AVE"]
        },

**Comment by GordonSmith** [comment]
@jchambers-ln is there a dash I can test with?

**Comment by jchambers-ln** [comment]
http://xxx.xx.xx.63:9090/DSP_DEV/?composition=35ad6b93-4aa8-4acb-beb5-a6fc69ab014b

Redacted IP but it is the one you are use to:

**Comment by GordonSmith** [comment]
@jchambers-ln That dashboard no longer exists.

**Comment by GordonSmith** [comment]
@jchambers-ln bump

**Comment by jchambers-ln** [comment]
If you create a dashboard with a table
AVE(some numeric field), some field
and tell it to sort on AVE(some numeric field) you should be able to reproduce

I will create an example on the official dsp-dev for you.

**Comment by jchambers-ln** [comment]
https://dsp-dev.xxxx.xxxx.xxx:443/?composition=f2cd8f56-c4f2-4ca4-8d87-8c9a182f438c

**Comment by GordonSmith** [comment]
Its not sorting because there is no actual "arrdelay_AVE" field to sort - which goes back to the quick hack we put in for the symposium (the raw data includes a _SUM + basecount).

Do we really want to "fix" this in the client, or wait for the correct HIPIE fix in the future (the one where it uses the same functions it uses for databombs in WUs as well)?  @drealeed what time frame is that in?

**Comment by drealeed** [comment]
@GordonSmith , will the sample dashboard I generated a couple of weeks back (with the ddl function definitions for ave fields, etc) also address this issue?

**Comment by GordonSmith** [comment]
@drealeed Probably not - but the sources will be in the same area.

**Comment by jchambers-ln** [comment]
@GordonSmith I provided a new example in this issue https://github.com/hpcc-systems/DSP/issues/1294

**Comment by GordonSmith** [comment]
I believe this is resolved in latest rc?  Please reopen if this is not the case.
