### ISSUE TITLE
amcharts label rotation not working

### ISSUE THREAD

**Issue by mzummo** [hpcc-systems/Visualization#1721]

**Comment by mlzummo** [comment]
isolated this issue down to a flaw in amcharts when rotation of a column chart is set to true to make it a bar chart labelroation no longer works... waiting to hear back

**Comment by GordonSmith** [comment]
x-axis label rotation does not work with AM Bar Charts (is it even needed I wonder?)

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
