### ISSUE TITLE
Distinct Function is needed

### ISSUE THREAD

**Issue by keerthanasai** [hpcc-systems/Visualization#1725]
'Distinct' function is needed to retrieve distinct values on any column. This is an universal use case, any typical reporting would like to see distinct values for their selection.

For ex:
`select distinct marketing_business_area
from dim_campaign`

**Comment by GordonSmith** [comment]
I use d3.nest for this (assuming I am understanding you correctly).  There are some helpers for doing this inside a widget, but the simplest example is probably here (external to the widget, but after data has been fetched):  http://bl.ocks.org/GordonSmith/528b4e33431ef4ec095432e46efdd40b

**Comment by GordonSmith** [comment]
Please re-open if the above comment does not cover your original request (with more information)

**Comment by keerthanasai** [comment]
Hi Gordon,
I am looking for this functionality when retrieving the data from file , not at the widget level. It will be duplication to apply distinct on each widget.  the best place I am looking forward to have this distinct feature is  as displayed in screenshot where we have Max,Min etc. i should be able to apply distinct on a column before retrieving the data. If needed we can meet on a call for 15 min and I can explain the issue we are trying to resolve.
![distinct](https://cloud.githubusercontent.com/assets/9011122/15836682/e1df1ecc-2c03-11e6-922a-39ef4a634981.PNG)
@salimmantri

**Comment by dabayliss** [comment]
HIPIE already does the server side distinct for you. A dude of

    myfile{state,COUNT)

will give you a count of each distinct state.

**Comment by keerthanasai** [comment]
Thanks for a reply. When I pull row count and Lead create Year column, I do get distinct values along with row count. but Showing Row count to the user is not required. I would like to display only distinct lead create year for users to see. please let me know how can I achieve this? Do you have any ability on DSP to hide Row count column or mask it not to show to the users? 
![distinct](https://cloud.githubusercontent.com/assets/9011122/15838778/e6ee7566-2c0d-11e6-80da-efbdf3159668.PNG)
@salimmantri

**Comment by dabayliss** [comment]
I am not that familiar with DSP - @jchambers-ln might be able to answer that for you.

From a HIPIE perspective you absolutely do NOT have to populate the rowcount if you don't want to ....

**Comment by jchambers-ln** [comment]
Rowcount provides a way to achieve distinct grouping-- however it isn't required if you are not needing count or distinct.

Also for numeric any of the aggregations is going to work like a distinct as it groups on that column (max age per state) but you still have the extra column you don't want to display.

@GordonSmith is there a way to hide a column in the table?

A true distinct may make sense though that doesn't add the extra count column to the output.

**Comment by drealeed** [comment]
Joe, this can be done in HIPIE by specifying the value in visualization aggregate but not including it in the table fields.

TABLE mytable(dsOutput{state,COUNT}):LABEL("State"),VALUE(state);

**Comment by jchambers-ln** [comment]
Ahh ok it would be nice to have a proper distinct as it is more intuitive -- 
TABLE mytable(dsOutput{state,DISTINCT}):LABEL("State"),VALUE(state);
I'll look to see if we can add at least for table a "don't display" flag for each column in DSP.

@GordonSmith in the layout designer could we add a "Hidden" to the column types? I see that as being useful for some future work.

**Comment by GordonSmith** [comment]
@jchambers-ln I would have thought a hidden in DSP for the field and then it would not be included in the mappings in the DDL?

**Comment by jchambers-ln** [comment]
Right we don't have that yet in DSP-- I will add that capability but I also see lift from being able to hide a column in the layout editor-- say you don't want to re run the dashboard or if you want to have the count column as a sanity test but be able to toggle it on and off  If done in DSP that requires re running the composition if done in your layer it is just checking a box and reloading the dashboard.

**Comment by keerthanasai** [comment]
please post ETA for the fix. It would help to know when we can expect this feature.
