### ISSUE TITLE
Security enhancement 

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#1735]
External products require xss prevention by embedding session tokens into the header for all requests going back to the server.  Visualization needs to add a hook to allow the embedding application to set this token.

See CSRF tokens

**Comment by GordonSmith** [comment]
Should expose the entire comms request/response to the custom marshaller, then they can plugin whatever comms library functions they may have.

**Comment by GordonSmith** [comment]
Resolved by https://github.com/hpcc-systems/Visualization/issues/1729
