### ISSUE TITLE
multiselect option in layout designer causes issues

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#1736]
if you enable multi select it seems to work, but after you reload the dashboard from scratch applying the derm string the behaviour gets very odd--- tested on a dashboard in witch the dependent chart was a pie and in the case of no values selected in the driving widget you would get double values.  

If you change it to multi select when you unselect it blanks out, however if you close and reopen the dashboard it no longer functions the same and everything gets a little off.

**Comment by indiangolfer** [comment]
Provider Integrity Scan dashboards ran into the same issue as well.

**Comment by GordonSmith** [comment]
Multi select is not supported between the viz and the HIPIE generated layer (yet) - this is in the Viz II timeframe...

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
