### ISSUE TITLE
google map pin index should align with map data index

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1739]

**Comment by mlzummo** [comment]
have to match pin path $(e.target).context.__data__ when using svg selector for pin ... better way to access data?

**Comment by GordonSmith** [comment]
Are you trying to get the original row of data back on a mouse click?

**Comment by mlzummo** [comment]
@GordonSmith we actually have a solution to this now, but basically i we could user a hover event on pins so that we can do popovers

**Comment by GordonSmith** [comment]
I am not sure I follow?
