### ISSUE TITLE
table sorted

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#1741]
If you sort a table in hipie the table is sorted but it isn't putting the sort indicator into the header until you click one of the columns to resort on it.

@drealeed said the DDL should have the sort indicator so can we make VIZ show the up/down carrot to indicate the sort on that column on first load?

**Comment by GordonSmith** [comment]
@jchambers-ln at best the viz will only be able to approximate what has been specified in the DDL.

**Comment by GordonSmith** [comment]
Dup of:  https://github.com/hpcc-systems/Visualization/issues/2273
