### ISSUE TITLE
Duplicate IDs can exist on the page via two different DDLs

### ISSUE THREAD

**Issue by jbrundage** [hpcc-systems/Visualization#1753]
Rendering two different DDLs on the same web page can currently result in multiple DOM elements sharing the same ID.

The marshaller could avoid this problem by concatenating its own ID to all child widget IDs.

Thoughts?

**Comment by GordonSmith** [comment]
If the clash is a _w1 type ID, then it can be avoided by using a different "seed" to _w (in 1.14 I think).

If its an actual ID from the DDL then it is an issue.

In theory having the duplicate IDs shouldn't break anything though?

**Comment by mlzummo** [comment]
@GordonSmith 
extra code needs to be written ontop of the dashboards in an application we are developing. having duplicate IDs makes it more difficult to make sure we select the correct tag/container.

**Comment by mlzummo** [comment]
its an actual ID from the DDL so i think we may want to append a _XXXX to those so that each time we persist a marshaller XXXX could be something that would be the same everytime but different from each dashboard so that we can do things with jquery and css

**Comment by GordonSmith** [comment]
What I would suggest is ensuring your hosting DIV sections have known IDs then you can call:
```d3.select("#MyDiv").select("_w1");``` to ensure you get the correct one.

Prefixing the IDs based on parentage would be a non trivial change (backward comparability etc.)

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
