### ISSUE TITLE
Choropleth zoom not updated when resize() is called.

### ISSUE THREAD

**Issue by bwood1** [hpcc-systems/Visualization#1755]
Steps to re-produce:

Create a dashboard in DSP
Add choropleth widget and configure
Run dashboard
Click 'Browse dashboards' button
Wait for dashboard to finish running
Click the tab for the dashboard.

The container holding the widget will be sized appropriately but the map will not be zoomed in to fit the container. resize().render() is being called when you click back to the dashboard tab.

Expected Result:

![expectedresult](https://cloud.githubusercontent.com/assets/2362888/16086180/a3bb155c-32ec-11e6-8b94-f26e9eeef5a2.PNG)

Actual Result:

![actualresult](https://cloud.githubusercontent.com/assets/2362888/16086189/a8e29b4a-32ec-11e6-8d22-e0595d6c54cc.PNG)

Javascript errors:

    Unexpected value NaN parsing width attribute.
    this.setAttribute(name, value);
    d3.js (line 663, col 6)

    Unexpected value NaN parsing height attribute.
    this.setAttribute(name, value);
    d3.js (line 663, col 6)

    Unexpected value NaN parsing width attribute.
    this.setAttribute(name, value);
    d3.js (line 663, col 6)

    Unexpected value NaN parsing height attribute.
    this.setAttribute(name, value);
    d3.js (line 663, col 6)

    Unexpected value translate(NaN,NaN)scale(0.25) parsing transform attribute.
    this.setAttribute(name, value);
    d3.js (line 663, col 6)

    NS_ERROR_FAILURE: 
    var bbox = this._layersTarget.node().getBBox();

**Comment by GordonSmith** [comment]
Already resolved in newer version:  https://github.com/hpcc-systems/Visualization/issues/1617
