### ISSUE TITLE
Treemap: Support pallet with gradients (like the choropleth)

### ISSUE THREAD

**Issue by jprichard** [hpcc-systems/Visualization#1764]
I want to size the boxes in the way they are currently (volume) but shade them on another column (price movement etc..). And pick the colours for bottom to top GrRd / GrRd / RdBl etc.. See pic

![gordon3](https://cloud.githubusercontent.com/assets/908650/16157426/81b59d2e-3486-11e6-9e54-48fb65e0e577.png)

**Comment by GordonSmith** [comment]
@jprichard - In this example is the size based on volume and the color is based on closing price?

**Comment by jprichard** [comment]
@GordonSmith yup!

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
