### ISSUE TITLE
Treemap: Headers on the categories

### ISSUE THREAD

**Issue by jprichard** [hpcc-systems/Visualization#1765]
Currently you see the categories only if you hover over a box and see the tooltip. Can we have the option of having them in the treemap? see pic
![gordon4](https://cloud.githubusercontent.com/assets/908650/16157504/d70be56c-3486-11e6-8b74-bb6d6f7b0f69.png)

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
