### ISSUE TITLE
Second widget not displayed when local filter applied to first widget 

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#1770]
required by: https://github.com/hpcc-systems/DSP/issues/1452

The info here doesn't provide enough details to know the second widget isn't filtered:

"datasources":[  
   {  
      "filter":[  
         "subject"
      ],
      "outputs":[  
         {  
            "filter":[  
               "subject"
            ],
            "from":"Ins003_dsOutput1_View_s1",
            "id":"View_s1",
            "notify":[  
               "s1",
               "s2"
            ]
         }
      ],
      "WUID":true,
      "id":"Ins003_dsOutput1"
   }
],

@GordonSmith suggested fix is to look at the call hierarchy to see if there is indeed a widget/form acting on s2 and change the logic to render or not with data on initial load

@drealeed is thee a need for the second filter block in the above JSON from your point of view... if so is there a way to enhance it so you know filter:subject is only applied for widget s1 and not s2.

**Comment by drealeed** [comment]
With #1728, when HIPIE is using >=Viz 1.18.0, filters will be restructured. Example:

http://10.173.147.1:8002/WsEcl/submit/query/roxie/leeddx_issue_1728_filterrefactor_service_viz1_18.ins003_service_1
 
      "dashboards": [{
              "datasources": [{
                      "URL": "http://10.173.147.1:8002/WsEcl/submit/query/roxie/leeddx_issue_1728_filterrefactor_service_viz_1.18.Ins003_Service_1/json",
                       "filter": [{
                                "fieldid": "subject",
                                "nullable": false
                         }],
                          "id": "Ins003_dsOutput1",
                           "outputs": [{
                          "filter": [{
                                      "fieldid": "subject",
                                      "nullable": false
                             }],
                               "from": "View_s1",
                                "id": "View_s1",
                                "notify": ["s1"]
                            }, {
                                 "from": "View_s1",
                                  "id": "View_s2",
                                   "notify": ["s2"]
                             }]
              }],
