### ISSUE TITLE
UX Enhancement for Dermatology: DesignMode Button

### ISSUE THREAD

**Issue by albertodesignz** [hpcc-systems/Visualization#1782]
Move the designMode checkbox to top menu bar. This will allow designers to easily switch back and forth from preview to design mode, streamlining the UI UX design flow.

See attached image
![dsp-ux-imporvement-design-mode-button](https://cloud.githubusercontent.com/assets/3629567/16309266/20f7f644-3936-11e6-8e97-913300046093.png)

**Comment by GordonSmith** [comment]
Resolved with:  https://github.com/hpcc-systems/Visualization/pull/1813
