### ISSUE TITLE
Support for providing a set of tick values.

### ISSUE THREAD

**Issue by dprichard13** [hpcc-systems/Visualization#1783]
In some cases I have a count by hours of the day or months of the year and there are some months/hours that do not have aggregate values.

Is it possible to add support for providing a set of tick points (like you can do for max and min) so that the gaps will be shown?

**Comment by GordonSmith** [comment]
@dprichard13 - I suspect if you change the domain/x axis to "linear" from "ordinal" that it will resolve your issue?

**Comment by dprichard13** [comment]
Yes that worked! Thanks
