### ISSUE TITLE
Dermatology vs DDL conflict

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#1784]
If you have a dermatology that has customized names for columns in a table the ddl wins out and you only see the column names as defined by the ddl and not the dermatology.  Introduced between 1.10.6 and 1.10.8 probably in the fix to resolve the columns not showing up if they existed in the ddl but not the dermatology.

**Comment by GordonSmith** [comment]
This is already resolved in the candidate-1.10.x branch (but I can confirm it was an issue in v1.10.6).
