### ISSUE TITLE
layout editor enhancements

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#1786]
- [ ] ability to delete line item settings (set to default making it so it was never set)
- [ ] ability to delete all layout settings per widget
- [ ] ability to delete all "global" layout settings not tied to a widget
- [ ] ability to delete all widget level settings keeping the "global"

DSP and other embedding applications should add in the ability to completely remove dermatology

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
