### ISSUE TITLE
Summary Chart Type - Format issue

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#1787]
https://github.com/hpcc-systems/DSP/issues/1521

**Comment by keerthanasai** [comment]
I have one more issue for Summary chart Type -
Remove the label of a summary chart type
Save the layout changes.
Close the dashboard.
reopen the dashboard and you will see the  Label there. It is not getting removed. @salimmantri 
![summary charttype - remove label](https://cloud.githubusercontent.com/assets/9011122/16459270/3af57774-3df0-11e6-9543-29cc465123d4.png)

**Comment by jpellock** [comment]
I think we need a separate ticket for the label issue. We'll keep this focused on the format issue. The formatting should support D3 formatting functionality (https://github.com/d3/d3-format/blob/master/README.md#format) like the table widget. @mounicarachakonda, can you look at this one?

**Comment by keerthanasai** [comment]
@mounicarachakonda, Do we have any update on this issue ?
@salimmantri

**Comment by mounicarachakonda** [comment]
@keerthanasai, I made a pull request from the branch. My request is pending.
