### ISSUE TITLE
Summary Chart Type  - removing label

### ISSUE THREAD

**Issue by keerthanasai** [hpcc-systems/Visualization#1788]
I have one more issue for Summary chart Type -
Remove the label of a summary chart type
Save the layout changes.
Close the dashboard.
reopen the dashboard and you will see the Label there. It is not getting removed. @salimmantri @jpellock 
![summary charttype - remove label](https://cloud.githubusercontent.com/assets/9011122/16461724/ebc1552c-3dfb-11e6-847b-b8da26ad243f.png)

**Comment by GordonSmith** [comment]
I believe this has been resolved with:  https://github.com/hpcc-systems/Visualization/pull/1829.  Please reopen if this is not the case.
