### ISSUE TITLE
Local filter not applied in Static data dashboard #1509

### ISSUE THREAD

**Issue by hamiltwp** [hpcc-systems/Visualization#1790]
Can we check static filter in visualization, for code or incorrect parameter in dud since DSP looks OK?  https://github.com/hpcc-systems/DSP/issues/1509

**Comment by GordonSmith** [comment]
@hamiltwp Can you provide some additional information?

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
