### ISSUE TITLE
hovering over bar chart w/ stacked series gives wrong number

### ISSUE THREAD

**Issue by wrulla** [hpcc-systems/Visualization#1792]
(Moved from DSP/issues/1553)

See the public dashboard OrderingPattern_Anomaly2 on DSP-QA, nominally accessible via

https://dsp-qa.risk.regn.net:443/?composition=15db391d-ca93-4056-bc99-62722ea91fcb

(if link doesn't work may have to search for it in DSP-QA).

Select 'Farmers' in the Company table widget. In the 'Avg num products per order by state' table if you hover over an orange rectangle, you get avgnumproducts2 = 0, rather than the value used to graph the orange rectangle.

Suspect possibly due to hovering behaviour with stacked series, e.g. tooltip maybe using entire vertical region to identify data point, rather than rectangular subregion associated to individual series... & 1st series in stack is maybe what's displayed

**Comment by GordonSmith** [comment]
(waiting on QA access)

**Comment by GordonSmith** [comment]
I believe this has been resolved now.  Please reopen if not the case.
