### ISSUE TITLE
Table widget: sortbyfieldindex doesn't work

### ISSUE THREAD

**Issue by TomCharmanODG** [hpcc-systems/Visualization#1795]
After running a dashboard with a table that has sortbyfieldindex set, the table is not sorted (though the little sorting arrow is pointing the correct direction). 

It does sort the data when you choose it in the layout designer. And clicking on the column header once it loads also works.

**Comment by GordonSmith** [comment]
Related to:  GH-1741

**Comment by GordonSmith** [comment]
@TomCharmanODG I suspect the issue here is that we expose the "sortbyfieldindex" publically - it should be an internal property.

To default a sort, you need to do it in the DDL / HIPIE layer.

**Comment by TomCharmanODG** [comment]
Ah, right. The ability to sort tables in the UI by clicking on the table header once the dashboard had loaded made me assume that the sortbyfieldindex was related to that functionality rather than the DDL/HIPIE sort. 

If I understand you right and that's a whole different thing, should I make a new ticket to address allowing an initial state for the header-clicking-sort?

**Comment by GordonSmith** [comment]
@TomCharmanODG Are you trying to set the default sort in the dermatology layer?  That should really be done in the HIPIE/DSP layer (lots more options).  Or are your wanting the table to display (in the header) the initial sort column?
