### ISSUE TITLE
Marshaller's Map Pin tooltip should support the capability of displaying its a widget as its content

### ISSUE THREAD

**Issue by jbrundage** [hpcc-systems/Visualization#1796]
The GMapPin widget resulting from the marshaller needs the ability to contain a widget so that the content can be as flexibly as a dashboard needs it to be.

**Comment by jbrundage** [comment]
Example of a tooltip fed with data from its parent widget:
![image](https://cloud.githubusercontent.com/assets/1891935/16732923/5f11dcae-474d-11e6-9505-09d71accab64.png)

**Comment by jbrundage** [comment]
Data needs to be conveyed in the popover from its parent widget. Each data point needs to somehow be mapped to each position within the html for the popover. The screen shot above (from the BIS) demo shows a jQuery hover event callback creating a bootstrap tooltip with specific data points manually mapped to the appropriate html elements as the tooltip is shown.

**Comment by jprichard** [comment]
could we use the option of putting HTML into a single column that could be used rather than having to nominate a bunch of columns? That way it can be wired into the data and the tooltip can just render it?

**Comment by jbrundage** [comment]
@jprichard that would work. @GordonSmith added the ability to identify certain columns as longitude and latitude. We should be able to use the same feature to identify a column as "tooltiphtml"

**Comment by GordonSmith** [comment]
@jbrundage @jprichard Pushing to 1.16 as this is not a HC requirement (I will gladly accept in 1.14 if its done in time).

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
