### ISSUE TITLE
Format field not working for choroplethstates

### ISSUE THREAD

**Issue by mounicarachakonda** [hpcc-systems/Visualization#1815]
Choropleth hover over text is not formatted. When the user changes the format value it does not get reflected.

**Comment by GordonSmith** [comment]
Already fixed in v1.14.x
http://rawgit.com/hpcc-systems/Visualization/v1.14.0-rc5/demos/dermatology.html?src/map/ChoroplethStates&tooltipValueFormat=%2C.0f&projection=albersUsaPr&centerLat=38.49416886517441&centerLong=-98.32631788353747&zoom=7.974003801526609
