### ISSUE TITLE
Calendar Date Picker

### ISSUE THREAD

**Issue by jpellock** [hpcc-systems/Visualization#1819]
Create a date picker widget to ease date entry in input fields. 

I'd suggest looking at this Pikaday pure .js solution but would be open to alternates. 
https://github.com/dbushell/Pikaday

**Comment by salimmantri** [comment]
This is cool! only minor enhancements to this would be as follows: 
- Click on the year or month and it does drop down but its not obvious that it would do that ... we can consider adding “a drop-down” style icon to indicate that these two fields are in fact a drop-down list ….

**Comment by GordonSmith** [comment]
FYI The standard form/input widget has a date/time option (for browsers that support it):  https://github.com/hpcc-systems/Visualization/blob/master/src/form/Input.js#L21

**Comment by jpellock** [comment]
Yeah @GordonSmith , I cannot recall why I was thinking that we'd want another option. We'll look at the browser based version and maybe we'll close this one.

**Comment by jchambers-ln** [comment]
@GordonSmith is there a date range widget currently.

**Comment by GordonSmith** [comment]
@jchambers-ln the new from/range support should allow two date inputs (from and to) to work.
