### ISSUE TITLE
add baseValue,min,max,interval to amcharts Axis

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1823]
@dineshshetye

add baseValue to amcharts Axis

https://docs.amcharts.com/3/javascriptcharts/ValueAxis

**Comment by mounicarachakonda** [comment]
GH-1844

**Comment by mlzummo** [comment]
@GordonSmith can you assign this to @mounicarachakonda (i will work with her on getting this done0

**Comment by mlzummo** [comment]
https://www.amcharts.com/tutorials/user-defined-minmax-values-of-value-axis/

This migght be used to get the interval we want for value axis labels
