### ISSUE TITLE
popup menu needs to always display on screen & center screen mode (like modal)

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1845]
we need to change the popup menu so that it can detect where to position itself as to always display on screen (also should have a mode where its always center screen like a modal)

**Comment by mlzummo** [comment]
This can be done via css but might want a PP with css

**Comment by GordonSmith** [comment]
Duplicate of https://github.com/hpcc-systems/Visualization/issues/1685
