### ISSUE TITLE
window resize marshaller resize scholl issue (important)

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1854]
resizeMarshaller = function() {
    if ($(".tab-pane:visible .marshaller_HTML").length > 0) {
	var currentMarshaller = $(".tab-pane:visible .marshaller_HTML")[0];
	d3.select(currentMarshaller).datum().resize().lazyRender();
    }
}

if the resized marshaller cannot fully fit into the window the chrome scroll bar still goes away and we can not longer veritcal scroll. (turning scrollbar always on does not help) as its in a disabled state

**Comment by GordonSmith** [comment]
@mlzummo Is the scrollbar "in" the marshaller or is it outside of it (like on the owning div or the window)?

**Comment by mlzummo** [comment]
The window

**Comment by GordonSmith** [comment]
Have you set the marhsaller.fitTo to "width" or "all"?

But the windows scrollbar behavior will be dictated by the owning DIV of the marshaller and not the marshaller itself (IOW its will be the web apps issue).

**Comment by mlzummo** [comment]
@GordonSmith its set to ALL

**Comment by GordonSmith** [comment]
Then I suspect whatever is resizing the DIV which is hosting the marshaller is doing something wrong? 
In dermatology we do this when the window resizes:  https://github.com/hpcc-systems/Visualization/blob/master/demos/dermatology.html#L551-L552

**Comment by mlzummo** [comment]
we narrowed it down to the application, have used a fix that we can use "for now"
