### ISSUE TITLE
local filter issue with interaction of other widget

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#1856]
@GordonSmith see email chain with RE: DSP Dashboards I sent you.

if you have multiple widgets each with a local filter based on the same column but with a different value, lets call these 1-6 widgets and then a 7th that is a list of states that filter 1-6 on state.
in 1.10.2 and up to 1.10.8 on initial load 1-6 loaded with the filter applied but not filtered by a state
once you clicked on a state 1-6 rendered filtered by state and the proper local filter

in 1.10.10-rc2
on initial load 1-6 is filtered by the last local filter to load and not the value rendered in the form widget
on clicking a state 1-6 is now filtered by the state but the local filter has been set to 1 as rendered but the proper value in the form

**Comment by GordonSmith** [comment]
Resolved by:  https://github.com/hpcc-systems/Visualization/pull/1859
