### ISSUE TITLE
Graph Widget: Control Widget (maybe in the titlebar)

### ISSUE THREAD

**Issue by jprichard** [hpcc-systems/Visualization#1862]
Layout control in the title bar (like chart select)
Zoom 
Rotate etc..

**Comment by GordonSmith** [comment]
Something like:  http://rawgit.com/hpcc-systems/Visualization/master/demos/dermatology.html?../tree/Dendrogram

**Comment by GordonSmith** [comment]
https://github.com/hpcc-systems/Visualization/releases

Uploading to viz.hpccsystems.com now

**Comment by jprichard** [comment]
Yes! with the layout change there... perfect.

**Comment by GordonSmith** [comment]
Resolved in 2.0
