### ISSUE TITLE
Data Drive Select not working with interactions

### ISSUE THREAD

**Issue by jpellock** [hpcc-systems/Visualization#1864]
Click event is not mapped correctly. 
```javascript
context.click(context._valueRowMap[options[0]], "value", true);
```
Needs to use 
```javascript
context.rowToObj(d)
```
...like https://github.com/hpcc-systems/Visualization/blob/master/src/other/Table.js#L315

**Comment by GordonSmith** [comment]
Specifically ```context.click(context.rowToObj(context._valueRowMap[options[0]]), "value", true);```
