### ISSUE TITLE
marshaller popup additions (checkbox/dropdown?)

### ISSUE THREAD

**Issue by mzummo** [hpcc-systems/Visualization#1865]
for some dashboards in production we have inputs that we pass either 1 or "" we should be able to change these to checkbox's or some kind of on/off toggle? make the inputs a bit easier? we might already be able to do this and i just dont know?

**Comment by GordonSmith** [comment]
You should be able to do a _charttype("CHECKBOX")?

**Comment by mlzummo** [comment]
Will that return 1 or nothing to Roxie service?

>

**Comment by drealeed** [comment]
in HIPIE plugins usually it's boolean fields that are defined as checkboxes, in which case 0 or false would be returned.

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
