### ISSUE TITLE
Roxie query input parameters are not available as filters on Flyout menu

### ISSUE THREAD

**Issue by dineshshetye** [hpcc-systems/Visualization#1870]
When you create a dashboard based of roxie service, the input parameters are not available. 

Dashboard Link: https://dsp-dev.risk.regn.net:443/?composition=c10b5ca9-405f-4241-9e63-b9cdee57f0e0

![image](https://cloud.githubusercontent.com/assets/1731313/17261240/b7b73206-55a2-11e6-9134-1d48c6d7a6f8.png)

Attaching the CMP, DUD and DDL files
 
[testroxieservie.zip](https://github.com/hpcc-systems/Visualization/files/391227/testroxieservie.zip)

**Comment by GordonSmith** [comment]
The attached DDL has no mention of the flyout form?
