### ISSUE TITLE
Dasboards doesn't load Completely

### ISSUE THREAD

**Issue by Mohammed-Idris-K-J** [hpcc-systems/Visualization#1879]
Hi, 
Some of the dashboards like "Loss or Restriction of License V2"(DSP- DEV) doesn't load completely when integrated into HealthCare Portals. I just use the layout available to load the complete dashboard. No customization applied on the layouts.
Only the layout gets loaded, The chart/content doesn't populate for the widgets.

**Comment by GordonSmith** [comment]
This sounds like an instance of:  https://github.com/hpcc-systems/Visualization/issues/1877 Does your dashboard have flyout forms?

**Comment by Mohammed-Idris-K-J** [comment]
Hi, There are no flyout forms in the Loss or Restriction of License V2 dashboard

**Comment by GordonSmith** [comment]
@Mohammed-Idris-K-J Can you re-test with:
* https://github.com/GordonSmith/Visualization/tree/future-1.14.x
* http://rawgit.com/GordonSmith/Visualization/future-1.14.x/demos/dermatology.html?src/marshaller/HTML.roxie&ddlUrl=http%3A%2F%2F10.241.100.159%3A8002%2FWsEcl%2Fsubmit%2Fquery%2Froxie%2Fzz_jcarmigniani_BIZOfficers.ins001_service_1%2Fjson&designMode=false&surfacePadding=0

**Comment by GordonSmith** [comment]
This was resolved in rc10
