### ISSUE TITLE
1.14 Marshaller null values

### ISSUE THREAD

**Issue by hamiltwp** [hpcc-systems/Visualization#1882]
in iterating _ddlDashboards in HTML.js in some cases ._ddlDashboards[key] is $clone etc instead of a visualization.  We've placed if(this._ddlDashboards[key].visualizations){  in the populateContent method as a workaround but it may need a less brutal not exception-based solution.

**Comment by GordonSmith** [comment]
@hamiltwp Can you provide an example?

**Comment by hamiltwp** [comment]
@GordonSmith can you skype or call at 10 this morning?

**Comment by GordonSmith** [comment]
Resolved with nullable?
