### ISSUE TITLE
Graph Widget: missing edges, label is not the correct size and person icon is massive!

### ISSUE THREAD

**Issue by jprichard** [hpcc-systems/Visualization#1883]
![gordon5](https://cloud.githubusercontent.com/assets/908650/17367431/d6e92e18-595d-11e6-8c34-fc9f2f5001bf.png)

this is in master dermatology.

**Comment by GordonSmith** [comment]
@jprichard 
1. I have resolved the missing edge issue
2. The massive Person icon is due to a DDL setting.
3.  I have not been able to reproduce the testbox wrong size issue, but suspect it might also be a DDL setting (now that we pass all of them through).
