### ISSUE TITLE
Dashboard fails to load in Dermatology.

### ISSUE THREAD

**Issue by jprichard** [hpcc-systems/Visualization#1897]
http://rawgit.com/hpcc-systems/Visualization/master/demos/dermatology.html?src/marshaller/HTML.roxie&ddlUrl=http%3A%2F%2F10.241.100.159%3A8002%2FWsEcl%2Fsubmit%2Fquery%2Froxie%2Fzz_jcarmigniani_BIZOfficers.ins001_service_1%2Fjson&designMode=false&surfacePadding=0

**Comment by GordonSmith** [comment]
Jo - this must have been already resolved as its working fine on my "future" branch:  http://rawgit.com/GordonSmith/Visualization/future-1.14.x/demos/dermatology.html?src/marshaller/HTML.roxie&ddlUrl=http%3A%2F%2F10.241.100.159%3A8002%2FWsEcl%2Fsubmit%2Fquery%2Froxie%2Fzz_jcarmigniani_BIZOfficers.ins001_service_1%2Fjson&designMode=false&surfacePadding=0

**Comment by GordonSmith** [comment]
@jchambers-ln This is currently loading on my future branch:  http://rawgit.com/GordonSmith/Visualization/future-1.14.x/demos/dermatology.html?src/marshaller/HTML.roxie&ddlUrl=http%3A%2F%2F10.241.100.159%3A8002%2FWsEcl%2Fsubmit%2Fquery%2Froxie%2Fzz_jcarmigniani_BIZOfficers.ins001_service_1%2Fjson&designMode=false&surfacePadding=0

One of your enums is missing a field ID (but I am adding a test for that now).

**Comment by GordonSmith** [comment]
Resolved.
