### ISSUE TITLE
ie10 gmap pin tooltip (custom) ... moustin is not working

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1899]

**Comment by GordonSmith** [comment]
(When the snapshot tool works, it shows IE10 ok):  thttps://developer.microsoft.com/en-us/microsoft-edge/tools/screenshots/#http://rawgit.com/GordonSmith/Visualization/future-1.14.x/demos/dermatology.html?src/map/GMap.pins

**Comment by mlzummo** [comment]
@GordonSmith sorry i wasnt precise in what i said, i have some sample code we can look at in how we are handling custom pins ..
