### ISSUE TITLE
404 when trying to view dashboard with layout. Attempting to load js from different URL (viz.hpccsystems.com).

### ISSUE THREAD

**Issue by bwood1** [hpcc-systems/Visualization#1917]
Steps to re-produce

Create a dashboard.
Configure a widget.
Run the dashboard.

Dashboard runs as expected and displays the dashboard. If you close the dashboard and re-open it without creating a layout that should work as well.

Edit the layout and save it.
Close the dashboard tab.
Click on the link to view the dashboard.

Expected: the dashboard should load
Actual: Widgets are not rendered and there are some errors in the JS console.

	"NetworkError: 404 Not Found - http://viz.hpccsystems.com/v1.14.0-dev/dist-amd/hpcc-bundles-def.js"
	hpcc-bundles-def.js

	Error: Script error for "http://viz.hpccsystems.com/v1.14.0-dev/dist-amd/hpcc-bundles-def.js"
	http://requirejs.org/docs/errors.html#scripterror
		
	var e = new Error(msg + '\nhttp://requirejs.org/docs/errors.html#' + id);
	require.js (line 168, col 17)

**Comment by GordonSmith** [comment]
@bwood1 The quick fix is to use an official v1.14.0-rc9 build of the Viz Framework and not the candidate branch.

What is happening is that the version of the framework used to create the persist string is "v1.14.0-dev" which is the default version for the candidate-1.14.x branch, when the loader tries to resolve that it fails.

The actual fix will need to go into sideeffects.js (possibly with some additional functionality to make it easier in the viz framework).

**Comment by GordonSmith** [comment]
FYI - resolved for now by creating "http://viz.hpccsystems.com/v1.14.0-dev".  I will keep it up to date with the latest rc builds as we move along.

**Comment by hamiltwp** [comment]
We should generalize a validation to known-acceptible version numbers in sideeffects or probably better in DSP when making the createdashboard call in sideeffects.  So that sideeffects/viz will not have to deal with unknown Viz versions.  Putting that list in mysql table for administrative purposes.  @GordonSmith do you have a list of versions which I can use to limit the list?

**Comment by GordonSmith** [comment]
@hamiltwp the current list looks like this (from viz.hpccsystems.com):
```
v0.9.0-beta
v0.9.2-beta
v1.0.0
v1.2.0
v1.2.2
v1.2.4
v1.4.0
v1.4.2
v1.4.4
v1.4.6
v1.4.8
v1.6.0
v1.6.2
v1.6.4
v1.6.6
v1.6.8
v1.6.10
v1.8.0
v1.8.2
v1.8.4
v1.10.0
v1.10.0-rc2
v1.10.0-rc3
v1.10.0-rc6
v1.10.0-rc7
v1.10.0-rc8
v1.10.0-rc9
v1.10.0-rc10
v1.10.2
v1.10.4
v1.10.6
v1.10.8
v1.10.10
v1.10.10-rc1
v1.10.10-rc2
v1.10.10-rc3
v1.10.12
v1.12.0
v1.12.0-rc1
v1.12.0-test
v1.12.2
v1.12.2-rc1
v1.12.4
v1.12.4-rc1
v1.12.4-rc2
v1.14.0
v1.14.0-dev
v1.14.0-rc1
v1.14.0-rc2
v1.14.0-rc3
v1.14.0-rc4
v1.14.0-rc5
v1.14.0-rc6
v1.14.0-rc7
v1.14.0-rc8
v1.14.0-rc9
v1.14.0-rc10
v1.14.0-rc11
v1.14.2
v1.14.2-rc1
```
