### ISSUE TITLE
C3/Other Chart Colors & Palette.js

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#192]
So far with C3 it looks as though there are 2 ways I can do colors:

var ColorArr = Palette.custom(["orange", "green"], 0, 100, XVAR);
this._config.color.pattern = ColorArr.range();

where XVAR is the # of bars (or # of bars in each group)

this works for .ordinal .brewer with similar options.

basically your just giving the .pattern an array of colors.

the second way allows for a bit more customization but I am not sure if its needed or how to create an elegant way of implementing it and overall implementing both methods across all charts.

EX: 
        this._config.data.colors = {
            Geography: '#ff0000',
            English: '#00ff00',
            Math: '#0000ff',
            Science: '#0000ff'
        }

        this._config.data.color = function (color, d) {
            console.log(d);
            // d will be 'id' when called for legends
            return d.id && d.id === 'English' ? d3.rgb(color).darker(d.value / 150) : color;
            
        }

this will (if i can figure out where I went wrong in my code) and based off of what i see at http://c3js.org/samples/data_color.html let you
customize the color of each bar based off of the original input color for each bar + allows you access to the data (d) for potentially doing colors based off the data value

**Comment by mlzummo** [comment]
what are your thoughts on something like this?      @GordonSmith , @dineshshetye

      Common.prototype.publish("palette", {}, "object", "Palette object");
      
      Common.prototype.setPalette  = function (type,optionsObj) {

        var options = [];
        for (var key in optionsObj) {
            var val = optionsObj[key];
            options.push(val);
        }
        
        this.palette(Palette[type].apply(options));
    };

widget.setPalette(ordinal,["category20"]);
widget.setPalette(brewer,["category20",0,100]);
widget.setPalette(custom,[["green","blue","red"],0,100,5]);

**Comment by GordonSmith** [comment]
I am going to be re-working the whole palette paradigm shortly - I _think_ I have a clearer idea of how to do it (still mulling it over)...

**Comment by GordonSmith** [comment]
@mlzummo - I went with your second approach from above - here is an example with the palette refactor:
https://github.com/GordonSmith/Visualization/blob/299d8c7713b0339c1c132942f3c676b2e317c02f/widgets/src/c3/Gauge.js#L21-L23
