### ISSUE TITLE
Child dataset displayed in wrong column

### ISSUE THREAD

**Issue by senthilkumarperiasamy** [hpcc-systems/Visualization#1922]
Child dataset is always pushed to the last column of the table widget.

Example - http://rawgit.com/hpcc-systems/Visualization/v1.14.0-rc9/demos/dermatology.html?src/marshaller/HTML.roxie&ddlUrl=http%3A%2F%2F10.241.100.159%3A8002%2FWsEcl%2Fsubmit%2Fquery%2Froxie%2Fzz_speriasamy_SuspectAddressDemo.Ins011_Service_1%2Fjson&designMode=false&surfacePadding=0

**Comment by GordonSmith** [comment]
@drealeed - could this issue be part of the DDL generation?  Here is the sections from the DDL:
```
		"id": "table01",
        "source": {
          "output": "View_table01",
          "mappings": {
            "value": [
              "addrline1",
              "city",
              "state",
              "zip",
              "noofproviders",
              "totalpaid",
              "totalclaim",
              "addrscore",
              "scorereasons"
            ]
          },
          "id": "Ins011_AddressTab"
        },
        "label": [
          "Address Line1",
          "City",
          "State",
          "Zip",
          "Suspect Flags",
          "# of Providers",
          "Paid Dollars(All Provider)",
          "# of Claims(All Providers)",
          "Score"
        ],
		
        "id": "table02",
        "source": {
          "output": "View_table02",
          "mappings": {
            "value": [
              "providerkey",						
              "fname",
              "mname",
              "lname",
              "cname",
              "totalpaid",
              "paidpercent",
              "noofclaims",
              "specialitydesc",
              "npi",
              "provscore",
              "lnpid",
              "scorereasons"
            ]
          },
          "id": "Ins011_ProviderTab"
        },
        "label": [
          "Provider Key",
          "First Name",
          "Middle Name",
          "Last Name",
          "Facility Name",
          "Total Paid $",
          "% Paid",
          "# of Claims",
          "Speciality",
          "NPI",
          "Provider Score",
          "Suspect Flags",
          "LNPID"
        ],		
```

**Comment by GordonSmith** [comment]
@senthilkumarperiasamy Could you have LNPID + Suspect Flags (lnpid + scorereasons) in the wrong order in the DUD?

**Comment by senthilkumarperiasamy** [comment]
@GordonSmith - Here is my table definition and suspect flags are in the 5th column. Scorereasons is the child dataset.

	TABLE table01(AddressTab
	{addrline1,city,state,zip,**scorereasons**,noofproviders,totalpaid,totalclaim,addrscore,addrline}): 
LABEL  ("Address Line1","City","State","Zip","**Suspect Flags**","# of Providers","Paid Dollars(All Provider)","# of Claims(All Providers)","Score"),
VALUE  (addrline1,city,state,zip,**scorereasons**,noofproviders,totalpaid,totalclaim,addrscore),SELECTS(addrline1->table02.addrline1,MERGE),TITLE("Top Suspect Addresses"), _charttype("TABLE"), _pagination("");

**Comment by GordonSmith** [comment]
@drea @senthilkumarperiasamy looks like a HIPIE bug?

**Comment by lrenn** [comment]
I'll look into it.  This composition is checked into HIPIE_Compositions right?  Can you send me the path?  I remember there being a few "SuspectAddress" compositions.

**Comment by lrenn** [comment]
I didn't work on this, but just so I'm sure I understand:

```json
"mappings": {
            "value": [
              "addrline1",
              "city",
              "state",
              "zip",
              "noofproviders",
              "totalpaid",
              "totalclaim",
              "addrscore",
              "scorereasons"
            ]
          },
```
That score reasons should be in the 5th position correct?  I see the problem in HIPIE if so.

**Comment by senthilkumarperiasamy** [comment]
Correct.

**Comment by lrenn** [comment]
Can someone spot check the linked DDL and tell me if that all looks good?

https://gist.github.com/lrenn/b28b1b145b71c1985dbaf11d22ee459f

**Comment by lrenn** [comment]
Looking at that gist now, I noticed that the "fields" array is also in the incorrect order.

**Comment by GordonSmith** [comment]
It looks ok to me - the fields order is not important.

**Comment by GordonSmith** [comment]
Hipie issue now resolved.
