### ISSUE TITLE
Applying Global Filter displays full data without filtering

### ISSUE THREAD

**Issue by hamiltwp** [hpcc-systems/Visualization#1927]
In version 1.14 when the global filter is applied with the dropdown form on the widget, the full data is displayed on the widget.  When submitted a second time, the data is filtered.

**Comment by GordonSmith** [comment]
@hamiltwp Can you re-test with the 1.14.0-rc10 release?

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
