### ISSUE TITLE
Second y axis tickFormat affects both y axes

### ISSUE THREAD

**Issue by TomCharmanODG** [hpcc-systems/Visualization#1938]
Replicated in [the dermatology demo](http://rawgit.com/GordonSmith/Visualization/future-1.14.x/demos/dermatology.html?src/amchart/Combo.simple&backwardsCompatible=false)... 

Setting up a second y axis with 'y2' works, and unchecking 'backwardsCompatible' allows you to edit properties for each of them separately. But:
- the tickFormat for the first y axis doesn't do anything
- the tickFormat for the second y axis applies to both charts

![image](https://cloud.githubusercontent.com/assets/17152326/17730185/fb6eaeea-64aa-11e6-8830-b72c7717348b.png)

**Comment by GordonSmith** [comment]
Resolved by:   https://github.com/hpcc-systems/Visualization/pull/2261
