### ISSUE TITLE
Second y axis properties aren't saved

### ISSUE THREAD

**Issue by TomCharmanODG** [hpcc-systems/Visualization#1939]
Noticed this in [1.14](http://rawgit.com/GordonSmith/Visualization/future-1.14.x/demos/dermatology.html) and 1.10. Reloading charts with properties set for individual y axes (when backwardsCompatible is disabled and a second y axis is set up with y2) loses whatever you've set for at least tickFormat and position. To reproduce:
1. Go to the dermatology demo
2. Set up 2nd axis and apply position & tickFormat settings to y axes
3. Save state
4. Reload state

**Comment by TomCharmanODG** [comment]
This is still happening in 1.14.2 and basically means that dual-y-axis charts are unusable.

**Comment by huppry01** [comment]
@GordonSmith, I see this is part of 1.14.8 but I believe that is already "in production".  Is this going to be included in the next release?

**Comment by GordonSmith** [comment]
Expired - please reopen if needed.
