### ISSUE TITLE
Show/Hide HPCC Chart Axis Labels

### ISSUE THREAD

**Issue by JamesSanCPL** [hpcc-systems/Visualization#1950]
Hi, is it possible to have properties to show/hide X and Y axis labels added to the HPCC charts?

**Comment by GordonSmith** [comment]
I assume your asking about: 
![image](https://cloud.githubusercontent.com/assets/966863/17813631/06508f3e-6624-11e6-950e-9fdffa4a4bea.png)
 
You can set "yAxisTitle" to "" to hide that one and you can set the first string in the columns array to "" to hide the x axis title.
But we could add an explicit (optional) xAxisTitle + show/hide options easily enough?

Another workaround would be to hide them with a small bit of CSS?

**Comment by JamesSanCPL** [comment]
Sorry if I wasn't being specific on my request, I was thinking of having properties to show/hide these labels:
![image](https://cloud.githubusercontent.com/assets/21122043/17814056/e5985c20-6625-11e6-86f5-f5cc301b611b.png)

**Comment by GordonSmith** [comment]
Hmmm - yAxisTickCount of 0 will remove the Y axis labels (but not the y axis and you will lose the horizontal lines).

I can add properties to hide them (is it text + line or just text?) - alternatively you can use CSS to hide them (and make them small)?

**Comment by JamesSanCPL** [comment]
Thanks Gordon. I think it would look nice if we were hiding only the text:

![image](https://cloud.githubusercontent.com/assets/21122043/17815427/323a3a84-662c-11e6-9b4f-c92af0c8d4f3.png)

(using AM charts as an example)

**Comment by GordonSmith** [comment]
There are new options in the x+y axis to hide - please reopen if they do not fit the need.
