### ISSUE TITLE
require issue

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#1951]
Gordon is this the require.js race condition that we say before?  I find it odd that it is trying to include d3.js off the site root.

"NetworkError: 404 Not Found - https://dsp-dev.risk.regn.net/d3.js"
d3.js
Error: Script error for "d3", needed by: src/marshaller/HTML
http://requirejs.org/docs/errors.html#scripterror
	

var e = new Error(msg + '\nhttp://requirejs.org/docs/errors.html#' + id);

	
require.js (line 168, col 17)
"NetworkError: 404 Not Found - https://dsp-dev.risk.regn.net/css.js"
css.js
Error: Script error for "css", needed by: css!src/form/Form_unnormalized2, css!src/other/PropertyEditor_unnormalized3, css!src/layout/Grid_unnormalized4, css!src/form/Input_unnormalized5, css!src/layout/Surface_unnormalized6, css!font-awesome_unnormalized7, css!src/form/Input_unnormalized8, css!src/common/TextBox_unnormalized9, css!src/form/Slider_unnormalized10
http://requirejs.org/docs/errors.html#scripterror
	

var e = new Error(msg + '\nhttp://requirejs.org/docs/errors.html#' + id);

	
require.js (line 168, col 17)
Error: Load timeout for modules: css!src/form/Form_unnormalized2,css!src/other/PropertyEditor_unnormalized3,css!src/layout/Grid_unnormalized4,css!src/form/Input_unnormalized5,css!src/layout/Surface_unnormalized6,css!font-awesome_unnormalized7,css!src/form/Input_unnormalized8,css!src/common/TextBox_unnormalized9,css!src/form/Slider_unnormalized10,css!src/layout/Border_unnormalized11,css!src/common/Text_unnormalized12,css!src/other/Table_unnormalized13,css!src/layout/Cell_unnormalized14,css!src/form/Input_unnormalized15,css!src/layout/Toolbar_unnormalized16,css!src/other/Legend_unnormalized17,css!src/common/Icon_unnormalized18,css!src/common/Shape_unnormalized19,css!font-awesome_unnormalized20,css!src/common/FAChar_unnormalized21,css!src/chart/Axis_unnormalized22,css!src/other/Paginator_unnormalized23
http://requirejs.org/docs/errors.html#timeout
	

var e = new Error(msg + '\nhttp://requirejs.org/docs/errors.html#' + id);

**Comment by jchambers-ln** [comment]
FYI seems to be isolated to firefox.

**Comment by dabayliss** [comment]
@GordonSmith this is currently a 1.7 DSP issue - do you have any thoughts on this ? Or do I need to push resolultion back ?

**Comment by GordonSmith** [comment]
Looks like an issue with how DSP is loading and initializing the viz framework (in this example its using the local un-minified sources, so might only be happening in your “debug” instance) – I have been unable to locate _where_ the loader code is (typically in a HTML file somewhere) so cant verify or point a finger.
 
What I am seeing is that the “loader.js” file is being loaded after the sideeffects.js file, which is not correct.

**Comment by jchambers-ln** [comment]
Our tweak on loading seems to have fixed this.
