### ISSUE TITLE
Layout Editor not responding to widget select click after save

### ISSUE THREAD

**Issue by hamiltwp** [hpcc-systems/Visualization#1952]
I believe this is related to an issue fixed in RC-11 , but appears after saving a layout, closing and re-opening the layout editor.  The save is successful, the widget renders with the altered layout, but the individual widget layout properties have gone missing in layout editor.

this is from DSP issue https://github.com/hpcc-systems/DSP/issues/1859

**Comment by GordonSmith** [comment]
@hamiltwp I was unable to reproduce - is this still an issue?

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
