### ISSUE TITLE
error in the console HTMLWidget.js:110

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#1953]
HTMLWidget.js:110 Uncaught Target can only be assigned once.

This occurs and a few of the flyout menus are blank I will send you an email with an example.

**Comment by GordonSmith** [comment]
@jchambers-ln This is a known issue where 1 form is driving several widgets and that form get marked as a flyout.   The workaround is to disable the flyout flag and I will take a look at your email to see if I can improve on the workaround
