### ISSUE TITLE
Line Break Issues

### ISSUE THREAD

**Issue by senthilkumarperiasamy** [hpcc-systems/Visualization#1957]
Line break works for AM_BAR, but does not work in C3_BAR, BAR and GOOGLE_BAR.

**Comment by GordonSmith** [comment]
Can you be more specific:
* tick labels
* titles
* tooltips
etc.

**Comment by senthilkumarperiasamy** [comment]
Example - 1 Brookline Pl 105 <br> Brookline MA 02445                                 

When I tried to display this label in bar chart, AM_BAR displayed it correctly while other bar chart display the line with <br>.  I have a test dashboard test_pie_02 in dev dsp as example.

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
