### ISSUE TITLE
Table should have ability to receive more than one value from a table_select

### ISSUE THREAD

**Issue by keerthanasai** [hpcc-systems/Visualization#1958]
Table_select chart type has ability to select more than one value. but when I select more than one value, the actual data table is not getting updated accordingly. The actual data table is getting updated by only one value. The ability pass more than one value is a critical feature and would appreciate the time to solve this issue.  @mounicarachakonda @salimmantri @jpellock @GordonSmith 
![ability to pass multiple values](https://cloud.githubusercontent.com/assets/9011122/17902115/f8fcca56-6933-11e6-83f3-e46ea4298f43.PNG)

**Comment by jpellock** [comment]
[depends on HIPIE change](https://github.com/hpcc-systems/HIPIE/issues/670)

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
