### ISSUE TITLE
User action instructions

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#196]
It would be helpful if we could build in some basic user instructions into the graphs.  See Arjuna's comment here.
https://github.com/hpcc-systems/DSP/issues/151

**Comment by GordonSmith** [comment]
This would not be a function of the visualization framework.

**Comment by dabayliss** [comment]
@GordonSmith within Viz - I have text boxes that I can just place on top of stuff --- right ? So if someone wanted to put instructions up on their dashboard they could ....

If so - I think this is closeable - if not - I think that is a legit request ...

**Comment by GordonSmith** [comment]
Technically we have the pieces to do this, but practically its not usable by anyone - further I suspect what folks would really like is the ability to do interactive "info graphs" and that would be a lot of work, its a fairly big can of works (even putting a floating text box over a bar chart is tricky when it comes to resizing etc.)
