### ISSUE TITLE
COLOR( palette_id ) or equivalent

### ISSUE THREAD

**Issue by dabayliss** [hpcc-systems/Visualization#1968]
https://github.com/hpcc-systems/DSP/issues/1152#issuecomment-242804394.

If you need any extra hipie support let us know .... but at least naively --- how you interpret the value inside COLOR( x ) is none of my business

**Comment by GordonSmith** [comment]
@jchambers-ln can you point me to a dashboard with the COLOR specified, so I can evaluate?

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
