### ISSUE TITLE
Disappearing Properties in Layout Editor

### ISSUE THREAD

**Issue by hamiltwp** [hpcc-systems/Visualization#1969]
After building a dashboard with two widgets,
In Layout Editor,

if you control-click to select two widgets, and then single-click on the first widget, the property settings disappear altogether.  They return on a subsequent click on the widget.

Possibly related to https://github.com/hpcc-systems/DSP/issues/1044 and https://github.com/hpcc-systems/Visualization/issues/1561

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
