### ISSUE TITLE
For tables with local sorting allow predefined sort order

### ISSUE THREAD

**Issue by dabayliss** [hpcc-systems/Visualization#1980]
For those tables with local sorting (not related to hipie) allow the default sort order to be defined in the dermatology

**Comment by GordonSmith** [comment]
Relates to:  
https://github.com/hpcc-systems/Visualization/issues/2273
https://github.com/hpcc-systems/Visualization/issues/2276

**Comment by GordonSmith** [comment]
Expired - please reopen if needed.
