### ISSUE TITLE
VizEvents Not captured for Table Click/Double Click Events

### ISSUE THREAD

**Issue by Mohammed-Idris-K-J** [hpcc-systems/Visualization#1984]
Trying to save the state of the dashboard when click/double click happens on the tables of the dashboard, where it currently saves the state on click/doubleclick of other widgets.

**Comment by GordonSmith** [comment]
Background:
The current design allows users to "listen" for click evens on the marshaller.  This works fine for all widgets which have side-effects (clicking on them updates another widget in the page).
Currently widgets with no side-effects, will not emit any events and the only way to "listen" to those widgets is to register a callback with them individidually.
