### ISSUE TITLE
Graph Vertex Event Params

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#1991]
Does not conform to the row, col, sel paradigm.

**Comment by lrenn** [comment]
@GordonSmith Any way you could confirm that the proposed PR will also fixed the above linked HIPIE issue?  I'm pretty confident it will, as long as the row being passed into that method is the full data row and not the data from the table.

**Comment by lrenn** [comment]
Actually, I think @drealeed linked the wrong item.  It should be #1990.
