### ISSUE TITLE
Pre-filtering on dependent charts not working when local filters are present.

### ISSUE THREAD

**Issue by dineshshetye** [hpcc-systems/Visualization#1994]
When we have widget A updating widget B and both the widgets have local filters, all the data in the Widget B is loaded. 

Actual Result: All the data from Widget B is updated when we open the dashboard for the first time. 

![image](https://cloud.githubusercontent.com/assets/1731313/18353832/8a5afb74-75b1-11e6-938b-a2fc9d108b6a.png)

Expected Result: The data in Widget B should be populated only on click event in widget A.

![image](https://cloud.githubusercontent.com/assets/1731313/18353861/a4169e9c-75b1-11e6-8aa0-dba4cc7c1453.png)

DUD, CMP and DDL:
[drilldown2.zip](https://github.com/hpcc-systems/Visualization/files/461908/drilldown2.zip)

**Comment by GordonSmith** [comment]
@dineshshetye I will need the WU ID or dash link to look at this (its not contained in any of the attached files).

**Comment by dineshshetye** [comment]
@GordonSmith This is the link to dashboard on DSP DEV https://dsp-dev.risk.regn.net:443/?composition=53cf2139-eea3-413a-b6e8-f1f351d690ac

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
