### ISSUE TITLE
Default values in flyout form not populating widget

### ISSUE THREAD

**Issue by bwood1** [hpcc-systems/Visualization#1995]
When you open a dashboard that has a global filter the widgets render but no data is populated. To see the data you have to click the flyout button and then click submit. 

Before re-submitting:
![flyoutbefore](https://cloud.githubusercontent.com/assets/2362888/18366432/9f3d8588-75e4-11e6-8ef6-5cbc606dc941.PNG)

After: 
![flyoutafter](https://cloud.githubusercontent.com/assets/2362888/18366437/a2e0015c-75e4-11e6-8415-483f7db9f56d.PNG)

**Comment by GordonSmith** [comment]
@bwood1 Can I get access to this dash?

**Comment by bwood1** [comment]
@GordonSmith I emailed you the details on how to access this dashboard.

**Comment by bwood1** [comment]
I think this may be related to the third issue in https://github.com/hpcc-systems/DSP/issues/1940

**Comment by GordonSmith** [comment]
Note:  This is only happening with roxie dashboards (fix incoming)
