### ISSUE TITLE
table widget properties dropping / not applying

### ISSUE THREAD

**Issue by huppry01** [hpcc-systems/Visualization#1996]
Whenever I re-open a dashboard it loses number formatting and revised column headers.

Here is a dashboard on QA where I am having this issue: https://dsp-qa.risk.regn.net:443/?composition=cf36aee0-ae2e-4b62-bea0-bb559986c27a

•	If I set the "sum(v2016)" column header in the table widget to a different name it goes back to "sum(v2016)" upon re-opening
•	If I set the number format in the "sum(v2016)" column to include thousands separator it disappears upon re-run.  Although if this is the only property I change it appears to stick.  If I change anything else (like column headers), both disappear.

**Comment by GordonSmith** [comment]
@huppry01 I believe this is resolved with:  https://github.com/hpcc-systems/Visualization/pull/2017
