### ISSUE TITLE
Implement New Summary Tiles

### ISSUE THREAD

**Issue by jpellock** [hpcc-systems/Visualization#2006]
We'd like to have new capabilities in our summary widget. In addition to a summary metric, we'd like to be able to support conditional formatting and also display another metric to display period over prior period. In addition, a historical graph. 

![image](https://cloud.githubusercontent.com/assets/1138194/18516916/b26701c4-7a68-11e6-8618-5363d2910a2f.png)

@mounicarachakonda

**Comment by GordonSmith** [comment]
There are a "lot" of nice examples out there:  https://www.google.ie/search?site=&tbm=isch&source=hp&biw=2133&bih=1610&q=dashboard&oq=dashboard&gs_l=img.3..0l10.1761.2854.0.3080.9.5.0.4.4.0.76.276.5.5.0....0...1ac.1.64.img..0.9.283.4o6bV1z9pGQ#tbm=isch&q=dashboard+bootstrap 
Before starting lets get a "short list" of ones we like?

**Comment by salimmantri** [comment]
http://secondtruth.github.io/startmin/pages/index.html - this has a good style of Summary Tiles.

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
