### ISSUE TITLE
PIE Not Honoring legendPosition/showLegend w/DDL.

### ISSUE THREAD

**Issue by lrenn** [hpcc-systems/Visualization#2007]
No legend is shown at all.  Originally it was reported to me as legendPosition not working, but I had him add showLegend which didn't seem to help.  Reported by @senthilkumarperiasamy.

```json
		"id": "PieChart",
		"properties": {
			"charttype": "PIE",
			"legendPosition": "right",
			"showLegend": true
		},
```

http://viz.hpccsystems.com/v1.14.2-rc1/apps/legacyDash.html?Hostname=10.241.100.159&Port=8010&Protocol=http&Wuid=W20160914-113753&ResultName=SuspectAddressPie_Comp_Ins011_DDL

**Comment by GordonSmith** [comment]
Adding @drealeed 

Hmmm - this is a little nastier than you might think.  What we have is a "Surface" widget with legend support, which hosts the actual chart.  Currently all "_"properties are passed through to the contained chart (which has no legend as such).

I can do a hacky fix - but in the long run we are going to need support dot syntax and properties.

IOW 
```
_legendPosition("right")  // Goes to the hosting surface widget
_chart.backgroundColor("red")  //  Goes to the contained pie chart 
```

type of thing...

**Comment by GordonSmith** [comment]
BTW the current workaround is to enable the legend in the dermatology layer rather than the _dud
