### ISSUE TITLE
refresh = undefined issue breaks hierarchy (marshaller)

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#2012]
refresh = undefined issue breaks hierarchy (marshaller)

seems there is some odd logic makes refresh = undefined and breaking stuff

**Comment by mlzummo** [comment]
treeuid = needs to be passed as well

**Comment by GordonSmith** [comment]
Already resolved with https://github.com/hpcc-systems/Visualization/pull/2002
