### ISSUE TITLE
Expand filter info in ddl

### ISSUE THREAD

**Issue by drealeed** [hpcc-systems/Visualization#2054]
This is the viz side of the HIPIE change https://github.com/hpcc-systems/HIPIE/issues/1728 and https://github.com/hpcc-systems/HIPIE/issues/670
 to include more information in the filters for a ddl. Currently the filters collection under outputs is an array. This will move that array to each "visualization" inside outputs, with the filters appropriate to that visualization. It will also change the array from a set of strings to a set of json attributes with info on nullability, etc.

```
{
"outputs": [
  {
    "from": "View_statedetails",
    "id": "View_statedetails",
    "notify": [{
        visualization:  "statedetails",
        "filter": [
            { "fieldid":"a", "nullable":false, "equivalence":"lessthan"},
            { fieldid:"b", "nullable":true},
            {"fieldid":"c", "nullable":true}
        ]
    }]
  },
```

**Comment by jchambers-ln** [comment]
@GordonSmith do you have an eta on this one? without it I need to push out the rage filter updates in DSP.
