### ISSUE TITLE
Clicking on different columns/points perform different updates

### ISSUE THREAD

**Issue by drealeed** [hpcc-systems/Visualization#2065]
This is the visualization side of HIPIE enhancement https://github.com/hpcc-systems/HIPIE/issues/1727

A concrete example of this:
A Locations table has a "state_abbreviation", "state_name" and "city_name" field. 
Clicking in the "state_name" column updates a "States" choro , filtering on "state_abbreviation"
Clicking in the "city_name" field updates a "Cities" table, filtering on "city_name".

This enhancement includes handling the changes in the ddl needed to define column/field-specific filtering so that visualization knows to do the above, + any changes to widget updates to do it.

**Comment by GordonSmith** [comment]
@drealeed FYI The table widget already passes the "col" clicked on to the marshaller (which is ignoring it currently)
