### ISSUE TITLE
table - marshaller needs to check by key or if index number is wrong throw away serialization

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#2068]

**Comment by GordonSmith** [comment]
Closing in favor of:  https://github.com/hpcc-systems/Visualization/issues/2076

Note:  The current DSP process require the user to re-visit any dashboard dermatology when the underlying Roxie / DDL query changes.  In this case the user would need to rename the fields/label to align correctly.

The underlying issues is that the matching is performed based on column index - the above issue is to switch to matching on ID - the actual issue will still occur, but less often.
