### ISSUE TITLE
Apply saved Filters not Working

### ISSUE THREAD

**Issue by Mohammed-Idris-K-J** [hpcc-systems/Visualization#2070]
Version of Code: Visualization-GH-2052 
While trying to render with the saved filter i get the below given error
HipieDDL.js:1628 Uncaught TypeError: Cannot read property 'mappings' of undefined

**Comment by GordonSmith** [comment]
@Mohammed-Idris-K-J I have just update the GH-2052 branch, can you re-test?

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
