### ISSUE TITLE
Roll over legends in the bar charts are not aligned to the slice we roll over

### ISSUE THREAD

**Issue by Mohammed-Idris-K-J** [hpcc-systems/Visualization#2071]
In the Health Care Portal bar charts roll over legends are not aligned to the one we roll over. It works fine in DSP. Could we have a fix which works for both DSP and portal?

**Comment by GordonSmith** [comment]
Do you have a screen shot?

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
