### ISSUE TITLE
surfaceTitleBackgroundColor and surfaceBackgroundColor have no effect

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#2073]
@TomCharmanODG commented on [Thu Sep 29 2016](https://github.com/hpcc-systems/DSP/issues/2035)

In DSP 1.7.2 (and for some time back, I think) I'm finding that setting either of these background color properties has no effect on the widget--you're stuck with the two default shades of gray.

---

@dabayliss commented on [Thu Sep 29 2016](https://github.com/hpcc-systems/DSP/issues/2035#issuecomment-250350185)

@GordonSmith --- presumably this is you ?

---

@GordonSmith commented on [Thu Sep 29 2016](https://github.com/hpcc-systems/DSP/issues/2035#issuecomment-250389158)

@TomCharmanODG surfaceTitleBackgroundColor isn't used in the marshaller created dashboards (as its superseded by the MegaChart Title), but the surfaceBackgroundColor should be working fine:  
![image](https://cloud.githubusercontent.com/assets/966863/18944331/c8eb820c-861c-11e6-9dfa-3b293fff0b86.png)

---

@TomCharmanODG commented on [Wed Oct 19 2016](https://github.com/hpcc-systems/DSP/issues/2035#issuecomment-254676862)

Everything below is based on testing with DSP Dev/QA -- if there's a better place for me to be testing this let me know. Though I get the feeling that this issue may only be turning up there if it hasn't become obvious independently.
#### surfaceBackgroundColor

So, on QA at the moment (DSP 1.7.2, VIZ 1.14.2) I get _two_ surfaceBackgroundColor properties for a choropleth (one in the first 'widget' group and one in the root level) and both seem to work (one is on top of the other it seems).

![image](https://cloud.githubusercontent.com/assets/17152326/19500849/acf8752a-95ec-11e6-9523-94e5fad23c8a.png)

However, the table next to it in that picture has only one surfaceBackgroundColor, and it doesn't work (it's set to red in that picture). I also find I don't have a working surfaceBackgroundColor for:
- amCharts
- google charts
- C3 charts

Just to confuse me completely, in DEV (DSP 1.7.2, Viz 1.14.6-rc3) the choropleth only has one surfaceBackgroundColor property, and it has no visible effect.
#### surfaceTitleBackgroundColor

On QA and DEV, everything has two surfaceTitleBackgroundColor properties (one in the 'widget' group and one at the root level) and only the 'widget' one works. So this is fine, though obviously hiding the non-functional one would be ideal.

---

@GordonSmith commented on [Thu Oct 20 2016](https://github.com/hpcc-systems/DSP/issues/2035#issuecomment-255016353)

@TomCharmanODG I am unable to reproduce on my local examples, can you share the dashboards your testing with?  
![image](https://cloud.githubusercontent.com/assets/966863/19547871/cba3ecb0-9692-11e6-8a58-b1f7bec604a7.png)

**Comment by GordonSmith** [comment]
Added PR which will present the properties in a more sensible order - awaiting on test case to see if this issue is already resolved.

**Comment by huppry01** [comment]
Gordon, here is an example in a dashboard I am trying to create.  Basically I want the background on all charts to be white but it never changes from gray

![image](https://cloud.githubusercontent.com/assets/18580746/20229115/ad46fe96-a822-11e6-9f8c-d64cf60f0d3b.png)

**Comment by huppry01** [comment]
Here is the dashboard link: 

https://dsp-qa.risk.regn.net:443/?composition=bc2bf1d0-77c3-46a3-8d43-9293cd53b256

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.

**Comment by huppry01** [comment]
still needed.  I provided the additional info requested.

**Comment by huppry01** [comment]
@GordonSmith this is still needed. I provided the additional info requested.

**Comment by GordonSmith** [comment]
Expired - please reopen if needed.
