### ISSUE TITLE
Summary ChartType  - the value is repeating

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#2080]
@keerthanasai commented on [Thu Oct 27 2016](https://github.com/hpcc-systems/DSP/issues/2101)

Hi, I have 'Summary' selected in the charttype for One column . 
the value is repeating . can you please help to overcome this issue.  I only want the number is Bold. 
![charttype -summary](https://cloud.githubusercontent.com/assets/9011122/19773109/51da7a58-9c36-11e6-929d-94eb347e7523.PNG)
@salimmantri @jchambers-ln @bwood1 

---

@jchambers-ln commented on [Tue Nov 01 2016](https://github.com/hpcc-systems/DSP/issues/2101#issuecomment-257643805)

@GordonSmith I don't see a way to hide the Label in the dermatology editor.  I have a feeling you could use the Mask to hide it but that is non-optimal

**Comment by jpellock** [comment]
@mounicarachakonda , can you look at updating the summary widget so that the sub metric is optional?

**Comment by mounicarachakonda** [comment]
GH-2099 - Added check boxes to make the sub metric optional.

**Comment by GordonSmith** [comment]
Resolved.
