### ISSUE TITLE
inter-widget reloading failing on latest build on viz.hpccsystems.com

### ISSUE THREAD

**Issue by drealeed** [hpcc-systems/Visualization#210]
I noticed something curious: when I run this viz against
http://viz.hpccsystems.com/v0.9.0-beta/legacyDash.html?Hostname=10.173.147.1&Port=8010&Protocol=http&Wuid=W20150211-103717&ResultName=leeddx_TestServiceViz_Comp_Ins001_DDL

, data comes back, but the table data is populated incorrectly upon clicking the pie—a known bug that was fixed a while back.

However, if I run it against
http://viz.hpccsystems.com/master/legacyDash.html?Hostname=10.173.147.1&Port=8010&Protocol=http&Wuid=W20150211-103717&ResultName=leeddx_TestServiceViz_Comp_Ins001_DDL

the table isn’t updated at all and remains empty when clicking on the pie. I don’t see any javascript errors in the console eithr. Any idea what’s up with that?:

**Comment by GordonSmith** [comment]
It works on the current master:  http://rawgit.com/hpcc-systems/Visualization/master/widgets/legacyDash.html?Hostname=10.173.147.1&Port=8010&Protocol=http&Wuid=W20150211-103717&ResultName=leeddx_TestServiceViz_Comp_Ins001_DDL

I think I should delete "master" from viz.hpccsystems.com as it is never up to date?

**Comment by drealeed** [comment]
Ramps users/plugin developers like me and Jo are using it frequently to test visualization development. Could you update it with the same version that's on rawgit.com?
Thanks,
Drea

**Comment by GordonSmith** [comment]
I can do - but the rawgit version is _always_ current and the one on viz.hpccsystems.com has to be manually built, deployed and purged before its usable....

**Comment by GordonSmith** [comment]
Closing as the latest has also been deployed to the cdn serrver
