### ISSUE TITLE
amCharts Tooltip number formatting to %

### ISSUE THREAD

**Issue by huppry01** [hpcc-systems/Visualization#2101]
None of the format settings appear to affect the display format of numbers that show in tooltips.  For example, I am trying to get decimals to appear as % in the tooltip like the rest of the chart.

**Comment by mlzummo** [comment]
are you using the amcharts flavor?

**Comment by huppry01** [comment]
yes

**Comment by jpellock** [comment]
@mounicarachakonda , can you look into this one?
