### ISSUE TITLE
Remove amCharts watermark?

### ISSUE THREAD

**Issue by huppry01** [hpcc-systems/Visualization#2102]
Is there any way the "JS chart by amCharts" watermark can be removed/toggled?

**Comment by mlzummo** [comment]
that requires purchasing amCharts from amcharts.com and swapping out the download they give you with the code in bower_components

**Comment by huppry01** [comment]
can we do that?  Its only $140 so I'm not sure why we wouldn't do it in the core DSP install

**Comment by GordonSmith** [comment]
Issue moved to [hpcc-systems/DSP #2131](https://github.com/hpcc-systems/DSP/issues/2131) via [**ZenHub**](https://www.zenhub.com/)
