### ISSUE TITLE
c3 Combo chart dropping types setting

### ISSUE THREAD

**Issue by huppry01** [hpcc-systems/Visualization#2103]
I have a C3 chart in the following dashboard on QA and when i specify the chart types (["bar", "line", "bar", "bar"]) the chart properly reflects those settings but then they are lost as soon as I hit Save Layout.

https://dsp-qa.risk.regn.net:443/?composition=bc2bf1d0-77c3-46a3-8d43-9293cd53b256

**Comment by mlzummo** [comment]
can you contact me on lync. what is your LN email address?

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
