### ISSUE TITLE
legend icon for line series not distinguished from column/bar series

### ISSUE THREAD

**Issue by huppry01** [hpcc-systems/Visualization#2106]
In amCharts combo charts the legend shows the same color block for line series as column/bar series.  The amCharts demos show a differentiated legend for line series.  Not sure if this is a defect or enhancement but is this on the roadmap?

![image](https://cloud.githubusercontent.com/assets/18580746/20144606/2c468a4a-a66b-11e6-9495-038b76aa6b1d.png)

Here is a demo sample from amCharts showing diff icons for column vs. line seriies

![image](https://cloud.githubusercontent.com/assets/18580746/20144642/4491ac7e-a66b-11e6-8b4d-4c7d92fbd749.png)

**Comment by GordonSmith** [comment]
This is "by design" - essentially all charts share the same legend for consistency and this "global" legend is just a simple one.

On the plus side, any improvements we make to the global legend will benefit _all_ charts.

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
