### ISSUE TITLE
Cross-dashboard interactivity not working

### ISSUE THREAD

**Issue by drealeed** [hpcc-systems/Visualization#2108]
This dashboard has a choro that updates widgets on the same dashboard and other dashboards:

http://viz.hpccsystems.com/v1.14.8-rc2/apps/legacyDash.html?Hostname=10.173.147.1&Port=8010&Protocol=http&Wuid=W20161118-141210&ResultName=issue_1109_flyover_Comp_Ins003_DDL

The second dashboard widgets are not updating.

Also the "title" defined for the line and pie widgets is not showing up.

Here's the ddl:

     [{
	"datasources": [{
		"WUID": true,
		"filter": ["clean_st"],
		"id": "Ins003_dsOutputDefined",
		"outputs": [{
			"from": "Ins003_dsOutputDefined_View_States",
			"id": "View_States",
			"notify": ["States"]
		}, {
			"filter": ["clean_st"],
			"from": "Ins003_dsOutputDefined_View_StateTable",
			"id": "View_StateTable",
			"notify": ["StateTable", "StatePie", "StateLine", "StateTable2", "StatePie2", "StateLine2"]
		}]
	}],
	"hipieversion": "1.8.0",
	"id": "Ins003_MainDash",
	"label": "MainDash",
	"primary": true,
	"title": "Main Dashboard",
	"visualizations": [{
		"color": "Red_Yellow_Blue",
		"events": {
			"click": {
				"updates": [{
					"datasource": "Ins003_dsOutputDefined",
					"instance": "Ins003",
					"mappings": {
						"clean_st": "clean_st"
					},
					"merge": false,
					"visualization": "StateTable"
				}, {
					"datasource": "Ins003_dsOutputDefined",
					"instance": "Ins003",
					"mappings": {
						"clean_st": "clean_st"
					},
					"merge": false,
					"visualization": "StateLine"
				}, {
					"datasource": "Ins003_dsOutputDefined",
					"instance": "Ins003",
					"mappings": {
						"clean_st": "clean_st"
					},
					"merge": false,
					"visualization": "StatePie"
				}, {
					"datasource": "Ins003_dsOutputDefined",
					"instance": "Ins003",
					"mappings": {
						"clean_st": "clean_st"
					},
					"merge": false,
					"visualization": "StateTable2"
				}, {
					"datasource": "Ins003_dsOutputDefined",
					"instance": "Ins003",
					"mappings": {
						"clean_st": "clean_st"
					},
					"merge": false,
					"visualization": "StatePie2"
				}, {
					"datasource": "Ins003_dsOutputDefined",
					"instance": "Ins003",
					"mappings": {
						"clean_st": "clean_st"
					},
					"merge": false,
					"visualization": "StateLine2"
				}]
			}
		},
		"fields": [{
			"id": "clean_st",
			"properties": {
				"type": "string2"
			}
		}, {
			"id": "Base_COUNT",
			"properties": {
				"type": "real"
			}
		}],
		"id": "States",
		"source": {
			"id": "Ins003_dsOutputDefined",
			"mappings": {
				"state": "clean_st",
				"weight": ["Base_COUNT"]
			},
			"output": "View_States"
		},
		"title": "Choro",
		"type": "CHORO"
	}, {
		"fields": [{
			"id": "clean_st",
			"properties": {
				"label": "clean_st",
				"type": "string2"
			}
		}, {
			"id": "Base_COUNT",
			"properties": {
				"label": "Base_COUNT",
				"type": "integer"
			}
		}],
		"id": "StateTable",
		"label": ["clean_st", "Base_COUNT"],
		"properties": {
			"flyover": true
		},
		"source": {
			"id": "Ins003_dsOutputDefined",
			"mappings": {
				"value": ["clean_st", "Base_COUNT"]
			},
			"output": "View_StateTable"
		},
		"title": "Table filtered by state",
		"type": "TABLE"
	}, {
		"fields": [{
			"id": "clean_st",
			"properties": {
				"type": "string2"
			}
		}, {
			"id": "Base_COUNT",
			"properties": {
				"type": "integer"
			}
		}],
		"id": "StatePie",
		"properties": {
			"flyout": true
		},
		"source": {
			"id": "Ins003_dsOutputDefined",
			"mappings": {
				"label": "clean_st",
				"weight": ["Base_COUNT"]
			},
			"output": "View_StateTable"
		},
		"title": "Pie filtered by state",
		"type": "PIE"
	}, {
		"fields": [{
			"id": "clean_st",
			"properties": {
				"type": "string2"
			}
		}, {
			"id": "Base_COUNT",
			"properties": {
				"type": "integer"
			}
		}],
		"id": "StateLine",
		"properties": {
			"flyout": true
		},
		"source": {
			"id": "Ins003_dsOutputDefined",
			"mappings": {
				"x": ["clean_st"],
				"y": ["Base_COUNT"]
			},
			"output": "View_StateTable"
		},
		"title": "Line filtered by state",
		"type": "LINE"
	}],
	"visualizationversion": "v1.14.6-rc1"
     }, {
	"datasources": [{
		"WUID": true,
		"filter": ["clean_st"],
		"id": "Ins003_dsOutputDefined",
		"outputs": [{
			"from": "Ins003_dsOutputDefined_View_States",
			"id": "View_States",
			"notify": ["States"]
		}, {
			"filter": ["clean_st"],
			"from": "Ins003_dsOutputDefined_View_StateTable",
			"id": "View_StateTable",
			"notify": ["StateTable", "StatePie", "StateLine", "StateTable2", "StatePie2", "StateLine2"]
		}]
	}],
	"hipieversion": "1.8.0",
	"id": "Ins003_Dashboard2",
	"label": "Dashboard2",
	"title": "Dashboard filtered by state",
	"visualizations": [{
		"fields": [{
			"id": "clean_st",
			"properties": {
				"label": "clean_st",
				"type": "string2"
			}
		}, {
			"id": "Base_COUNT",
			"properties": {
				"label": "Base_COUNT",
				"type": "integer"
			}
		}],
		"id": "StateTable2",
		"label": ["clean_st", "Base_COUNT"],
		"properties": {
			"flyover": true
		},
		"source": {
			"id": "Ins003_dsOutputDefined",
			"mappings": {
				"value": ["clean_st", "Base_COUNT"]
			},
			"output": "View_StateTable"
		},
		"title": "Dashboard2 Table filtered by state",
		"type": "TABLE"
	}, {
		"fields": [{
			"id": "clean_st",
			"properties": {
				"type": "string2"
			}
		}, {
			"id": "Base_COUNT",
			"properties": {
				"type": "integer"
			}
		}],
		"id": "StatePie2",
		"properties": {
			"flyout": true
		},
		"source": {
			"id": "Ins003_dsOutputDefined",
			"mappings": {
				"label": "clean_st",
				"weight": ["Base_COUNT"]
			},
			"output": "View_StateTable"
		},
		"title": "Dashboard2 Pie filtered by state",
		"type": "PIE"
	}, {
		"fields": [{
			"id": "clean_st",
			"properties": {
				"type": "string2"
			}
		}, {
			"id": "Base_COUNT",
			"properties": {
				"type": "integer"
			}
		}],
		"id": "StateLine2",
		"properties": {
			"flyout": true
		},
		"source": {
			"id": "Ins003_dsOutputDefined",
			"mappings": {
				"x": ["clean_st"],
				"y": ["Base_COUNT"]
			},
			"output": "View_StateTable"
		},
		"title": "Dashboard2 Line filtered by state",
		"type": "LINE"
	}],
	"visualizationversion": "v1.14.6-rc1"
     }]

**Comment by GordonSmith** [comment]
@drealeed - there are two separate datasource definitions (one per dashboard).

On the client each instance has its own state (which includes the request + response) so even though a viz on dashboard one notifies a viz from the second dash, when it goes to look in its datasource for the data, it is empty.

I we want to common up the datasources, then they should be moved out of the dashboards?

**Comment by drealeed** [comment]
That makes sense. With the 1.16+ ddl structure, where you have a "dashboards" property rather than an array of visualizations, we can move the datasources out.

For the current viz version, will outputting all datasources for all dashboards in each "datasource" section resolve this issue?

**Comment by GordonSmith** [comment]
For a pure DDL change to work within the 1.14.x branch, you would need to put all your datasources and visualizations into a single dashboard structure.  Any changes beyond that should really go into the 1.16.x branch (which will have the tabbed dashboard support - work is done, but not pulled)

**Comment by drealeed** [comment]
@GordonSmith , should this issue be tagged for 1.16.x?

**Comment by drealeed** [comment]
Here's the HIPIE side of the change: https://github.com/hpcc-systems/HIPIE/issues/2229
