### ISSUE TITLE
Legend fonts can't be changed

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#2112]
@sunsan01 commented on [Mon Nov 28 2016](https://github.com/hpcc-systems/DSP/issues/2170)

Legend font style and size can't be changed. Would like to have this as an option to be consistent with the rest of the dashboard. thanks. 

---

@sunsan01 commented on [Mon Nov 28 2016](https://github.com/hpcc-systems/DSP/issues/2170#issuecomment-263357908)

Would also like to be able to change the font style and size for the content of a table widget. Currently, I can only apply font changes to the table header but not to the data within the table. thanks!

**Comment by GordonSmith** [comment]
I _think_ this is only for c3 chart legends?

**Comment by GordonSmith** [comment]
Expired - please reopen if needed.
