### ISSUE TITLE
Cannot change color of columns in Combo charts, only for lines and the border of the column

### ISSUE THREAD

**Issue by sunsan01** [hpcc-systems/Visualization#2123]
There is not an option in Layout Designer for me to change the color of the columns in combo charts. I can change the line color but that also changed the border of the columns, which is not my intention, and also, the legend does not reflect the color changes that I've made to Combo charts. 

Also, when I select one of the pre-existing paletteIDs in the dropdown, selection "Set1" may be different from one chart to the next within the same dashboard. Can we add another paletteID that uses LexisNexis color schemes? Thanks. 

Project: Market Rate Activity Dashboard

**Comment by GordonSmith** [comment]
This is being revisited in 2.0 at a bigger theme / palette level.
