### ISSUE TITLE
Unable to print all graphs and tables in the dashboard

### ISSUE THREAD

**Issue by sunsan01** [hpcc-systems/Visualization#2124]
When I use the Print option on the top right hand corner, it currently only allows me to print the widgets that I see displayed on the screen. so if there's anything outside of the current display, then it will not be printed. In another word, if I have to scroll up and down, I will not be able to print what I don't see on the screen. Can this be fixed so users can print the entire dashboard?

Project: Market Rate Activity Dashboard

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
