### ISSUE TITLE
CDN fonts

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#2126]
cdn fonts failing to load via cdn: (says cancelled)
however when you navigate to said link a file is downloaded
(this may be a non-issue and if thats the case we can delete this bug)

![image](https://cloud.githubusercontent.com/assets/1057527/20931165/42e83a26-bb9e-11e6-8bf7-534ab3cd073d.png)

**Comment by GordonSmith** [comment]
Its an issue with the CDN servers rules (CORS disabled) - I think someone is looking into it already.

**Comment by GordonSmith** [comment]
CDN Server now updated to support CORS
