### ISSUE TITLE
When a wiget is refreshed via an interation it should clear subordinate widgets

### ISSUE THREAD

**Issue by jprichard** [hpcc-systems/Visualization#2147]
If I have widget A that updates widget B that updated widget C and currently widget C is showing data based on a selection from widget B, then if I make a new selection on widget A that refreshes the data in widget B it should clear the filter on widget C and update it.

**Comment by jprichard** [comment]
It causes issues when the user has picked say, a new state but the widget at the bottom is still showing data from the previous state that was selected.

**Comment by GordonSmith** [comment]
@jprichard There should be a global option to "propogateClear" is this set?

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
