### ISSUE TITLE
Combo Chart Changes Do Not Save

### ISSUE THREAD

**Issue by zsuffern** [hpcc-systems/Visualization#2148]
I am trying to make a C3_Combo graph. I’m in the layout designed with a dataset that has two parts and I set the C3_Combo to have a defaultType line, and types filed is filled as such : [“area”,”bar”] and while in layout designer it all looks correct but when I save the layout the changes don’t go through and the graph reverts to a C3_Combo Bar Chart.

**Comment by zsuffern** [comment]
this seems to work with any combo graph but I have a visualization called linking_stats on DSP_DEV where this behavior can be found, just try to change the combo chart and save.

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
