### ISSUE TITLE
Summary Widget customization

### ISSUE THREAD

**Issue by albertodesignz** [hpcc-systems/Visualization#2152]
Would like to be able to change the following parameters for the summary widget:
- Ability to customize non-populated state colors and text
- Ability to change positioning of text
- Ability to add images
- Change font type and size

**Comment by jchambers-ln** [comment]
Gordon looking 
Visualization/dist/hpcc-viz.css is where this is coming from.


.chart_Summary .content {
  float: left;
  width: 100%;
  height: 100%;
  background-color: #efd752;
}

1. can this be overridden in the client application using styles in the header safely?

2. what potential side effects are there to just change this out?

**Comment by GordonSmith** [comment]
1 - Yes
2 - Not much its just the default colour.

**Comment by albertodesignz** [comment]
This essential covers the color of the inactive state. What about:
Ability to change positioning of text
Ability to add images
Change font type and size

**Comment by jchambers-ln** [comment]
@albertodesignz correct they don't want to demo with the yellow, the other items would need to be addressed.

**Comment by GordonSmith** [comment]
Expired - please reopen if needed.
