### ISSUE TITLE
Choropleth Legend Incorrect

### ISSUE THREAD

**Issue by huppry01** [hpcc-systems/Visualization#2153]
The legend does not display the correct range values for the corresponding colors.  In the following screenshot, the legend is showing 0.06% for the lightest color but then 0.00% for all of the bins between the lowest and highest.  

![image](https://cloud.githubusercontent.com/assets/18580746/22206464/64d160e2-e149-11e6-9106-1e9aabfca3ad.png)

**Comment by huppry01** [comment]
Adding dashboard link.  Can this be tagged as a bug and added to a release?

https://dsp-qa.risk.regn.net:443/?composition=b6b0d3dc-b7df-4e9b-91b7-08f147bd7999

**Comment by GordonSmith** [comment]
Resolved in 2.0
