### ISSUE TITLE
Border Radius for Widgets

### ISSUE THREAD

**Issue by albertodesignz** [hpcc-systems/Visualization#2156]
Ability to specify radius to specific corners of a widget:

surfaceBorderRadiusAll - All corners are affected

surfaceBorderRadiusTop -Top 2 corners are affected

surfaceBorderRadiusTopRight - Top right corner is affected

surfaceBorderRadiusTopLeft - Top left Corner is affected

surfaceBorderRadiusBottom - Bottom 2 corners are affected

surfaceBorderRadiusBottomLeft - Bottom left corner is affected

surfaceBorderRadiusBottomRight - Bottom right corner is affected

**Comment by GordonSmith** [comment]
Surface as we know it is going away in 2.0

**Comment by albertodesignz** [comment]
Great! do you have a link or place where i can see the update?
