### ISSUE TITLE
New Dashboard Layout Settings Needed

### ISSUE THREAD

**Issue by huppry01** [hpcc-systems/Visualization#2171]
There are a few issues that hinder dashboard design in DSP:

1)  There is no way to set the width and height of the entire dashboard
2)  The "fitTo" dashboard setting only has values of "width" and "all".  A new option is needed for "none". 
3)  There is no padding or margin setting for the entire dashboard.  All padding/margin settings that exist today control widget padding.  We need to be able to add margin around the entire dashboard. 

The following is an example of a dashboard that would benefit from these settings.  The Summary widgets should be equally sized and centered in the middle of the dashboard.  Since the fitTo options only allow "width" and "all", the widgets are automatically re-sized to fill the screen according to that setting.  The desired look is that the dashboard canvas is larger than the space that the widgets consume and to have the widgets equally sized in the middle of the dashboard.  

![image](https://cloud.githubusercontent.com/assets/18580746/23375305/dc70eac4-fcf5-11e6-93b5-ae28d167c9ed.png)

https://dsp-qa.risk.regn.net:443/?composition=f642e082-989a-4024-9d78-c038f0167a28

**Comment by GordonSmith** [comment]
Expired - please reopen if needed.
