### ISSUE TITLE
Missing widget after double clicked

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#2174]
@sunsan01 commented on [Mon Feb 27 2017](https://github.com/hpcc-systems/DSP/issues/2301)

### Version and Instance (URL) in which the issue was found or feature not available in
DSP Version :1.8.1
https://dsp-qa.risk.regn.net:443/?composition=164c8e51-b93c-43d9-b2fe-e7ce178868d3

### Expected Behavior
When this happened before, the widget that was double clicked would be hidden underneath one of the other widgets in the dashboard and I would always be able to find it. 

### Actual Behavior
I cannot find that table anywhere in the dashboard even after moving all the other widgets around. I have tried removing it and adding it back in but I think because they have the same name, the new one just replaced the old one's position wherever that is.

### Steps to Reproduce the Issue
Double click on a widget

### Other Details
I have already fixed the issue by changing the widget position within Layout Designer but we need a solution to have it not go off grid. The position it was in was row:-1, column:-13. thanks.

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
