### ISSUE TITLE
Distinctive hover text not displayed for the measures in stacked chart

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#2186]
@AdlinSteffi commented on [Thu Mar 16 2017](https://github.com/hpcc-systems/DSP/issues/2317)

Instance (URL): http://172.23.42.86:8081/
(DSP Version: 1.8.1; HIPIE Version: 1.8.3-rc1; VIZ Version: 1.14.8)

Create and run a dashboard with Stacked column widget
Example:
http://172.23.42.86:8081/?composition=a40904ce-852b-42dd-b89a-24823ff27b65
Hover over the various stacks

Issue: Distinctive hover text is not displayed. The hover text is displayed the same for all the stacks
![2017-03-16_161902](https://cloud.githubusercontent.com/assets/18044342/23992797/4af75bd8-0a64-11e7-904b-1aa01ec7a4ea.png)

**Comment by jchambers-ln** [comment]
Steffi I moved this to the Visualization project and closed this issue

**Comment by GordonSmith** [comment]
I believe this is resolved now - please reopen if needed,
