### ISSUE TITLE
CHORO_USCOUNTIES Map not working

### ISSUE THREAD

**Issue by sunsan01** [hpcc-systems/Visualization#2187]
URGENT - Users are waiting as this dashboard has already gone live.

This happens when I'm running my dashboard using the current run version. When an interaction is created between TABLE_SELECT and CHORO_USCOUNTIES, the map will only reflect some selections in the list. It appears that the current version is not recognizing some state/county codes because when I tried  viewing it in v1.16.2-beta2, the county level details did appear even though they didn't appear in the other Run Version. 

[https://dsp-qa.risk.regn.net:443/?composition=c67ae732-39b7-422b-9e4c-d315b741bef7](https://dsp-qa.risk.regn.net:443/?composition=c67ae732-39b7-422b-9e4c-d315b741bef7)

Try the following combinations:
Year = 2016
Customer = "Amica Mut Grp-03362"
Vendor Source = "A & B"
Table_select within CountryMap = "deed_document_number"
State = "CA" <-- does not show
State = "GA" <-- does show

**Comment by GordonSmith** [comment]
@sunsan01 is this an ongoing issue?

**Comment by sunsan01** [comment]
It started after the new DSP version was put in production. Only some states would show in the county map.

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
