### ISSUE TITLE
X Y heat map

### ISSUE THREAD

**Issue by gopala-rudraraju** [hpcc-systems/Visualization#2188]
Need a viz, where I can pass in 2 attributes and be able to color map based on the aggregated value.
The below links should give you an idea.
http://bl.ocks.org/tjdecke/5558084
http://seaborn.pydata.org/_images/seaborn-heatmap-6.png

@jpellock

**Comment by GordonSmith** [comment]
The closest thing we have to that is:  http://rawgit.com/hpcc-systems/Visualization/master/demos/dermatology.html?src/chart/HexBin.simple&xAxisType=linear&yAxisType=linear

Which really only works if you x-axis is a linear value (like a scatter chart).

**Comment by GordonSmith** [comment]
We do also have:  http://rawgit.com/hpcc-systems/Visualization/master/demos/dermatology.html?src/other/CalendarHeatMap.simple

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
