### ISSUE TITLE
Adjust Interactions from Graph Widget

### ISSUE THREAD

**Issue by stermi01** [hpcc-systems/Visualization#2196]
We would like the ability to adjust the interactions from the graph widget by assigning any fields in the graph dataset available.

Here is an example:

      
GRAPHDetails(dsOutput2{dsInput2_treeuid,dsInput2_entitycontextuid,dsInput2_entitylabel,dsInput2_entityflag4,**dsInput2_alert_number**,dsInput2_childcount,dsInput2_entityweight,dsInput2_entitytype,dsInput2_entitycolor,dsInput2_entityicon,links{dsInput2_associationsvertexid}}): 
LABEL(dsInput2_entitylabel),UID(dsInput2_entitycontextuid),
WEIGHT(dsInput2_childcount),
**SELECTS(INPUTS.dsInput2_alert_number->AlertDetail.alert_number,MERGE),**
FILTER(dsInput2_treeuid),ICON(dsInput2_entitytype,ENUM(1=inputpersonflagicon)),
FLAG(dsInput2_entityflag4,ENUM(1=inputflagicon,0=nothing)),
LINK(links,UID(dsInput2_associationsvertexid)),TITLE("Details");

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
