### ISSUE TITLE
Applying Layout effects non styled widgets

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#2202]
Create a composition ‘comp1’
Configure Pie and Column widgets
Run the composition
View the dashboard
Click Layout designer
Set fitTo as Width
Save the layout
Close the composition
Clone the composition ‘comp1clone’
Select Edit configuration
Delete pie widget
Add Line widget as the second widget
Run
View the dashboard

**Comment by jchambers-ln** [comment]
@GordonSmith the bulk of the details is in the DSP issue.

**Comment by GordonSmith** [comment]
Expired - please reopen if needed.
