### ISSUE TITLE
LN Font Style

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#2203]
@sunsan01 commented on [Mon Nov 28 2016](https://github.com/hpcc-systems/DSP/issues/2169)

Some font styles do not appear to be available in DSP. I want to use the official LexisNexis Brand fonts: Source Sans Pro or Droid Serif Regular to my dash but it appears that only Droid Serif Regular works. Source Sans Pro font style does not appear to work. thanks. 

---

@jchambers-ln commented on [Mon Nov 28 2016](https://github.com/hpcc-systems/DSP/issues/2169#issuecomment-263357901)

Since the fonts are rendered by your browser any fonts used has to be available on the computer rendering the page.  There are ways to make a website provide the font library but baring that unless it is a websafe font you are dependent on what fonts a computer has.  If the website provides the Font then we have to consider the license for the font.

@GordonSmith any ideas on how to make these fonts universally available?

@sunsan01 do you have a list of required fonts?

---

@sunsan01 commented on [Tue Nov 29 2016](https://github.com/hpcc-systems/DSP/issues/2169#issuecomment-263575093)

I see. Thanks Joe. I have downloaded them but can't seem to move them into my Fonts library. I'll need to call the help desk then. I am hoping to apply the official LexisNexis fonts used for branding and marketing as stated in the below URL.

**Comment by GordonSmith** [comment]
By default the visualizations should use whatever the default font is on the host application page - so the font use in DSP may not be the same as when the dashboard is hosted in the final product.
It may be possible to add the ability to use any font from Google Fonts (or similar) - but it would only work for "online" computers,

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
