### ISSUE TITLE
Table default onscroll event needs to be optimized

### ISSUE THREAD

**Issue by jbrundage** [hpcc-systems/Visualization#2208]
By default the margins are set on every scroll tick (regardless of which axis is being scrolled). This is causing performance issues when dealing with a large DOM.

**Comment by GordonSmith** [comment]
Do you have a line of code your referring to?

**Comment by jbrundage** [comment]
This is the line I'm talking about:
https://github.com/hpcc-systems/Visualization/blob/master/src/other/Table.js#L745

**Comment by GordonSmith** [comment]
Looks like its only needed on a horizontal scroll?

**Comment by GordonSmith** [comment]
New grid on the way.
