### ISSUE TITLE
Message Bus widget

### ISSUE THREAD

**Issue by chuajoey** [hpcc-systems/Visualization#2213]
Implement a widget with a message bus publish/subscribe pattern to enable loose coupling of components in a dashboard. This pattern is better than point-to-point interactions that are hard to maintain when components in a dashboard are added/removed/edited.

(please assign ticket to me).

**Comment by GordonSmith** [comment]
FYI I am also investigating "ConflatingMessages" in conjunction with animation frames.

**Comment by GordonSmith** [comment]
Expired - please reopen if needed.
