### ISSUE TITLE
Choropleth can cause cross-origin error

### ISSUE THREAD

**Issue by chuajoey** [hpcc-systems/Visualization#2219]
In b1.16.0- beta4, dist-amd:
* using map/ChoroplethStates
  browse html file via file://
  error: `hpcc-viz.js:40 XMLHttpRequest cannot load file:///<snip>/map/TopoJSON/us-states.json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.`
* work-around: serve files via http
  dermatology still seems to work, though
* error does not occur in 1.14.8.

**Comment by GordonSmith** [comment]
This is a "server" setting and nothing the client JS can do anything about.  
Note I:  It will work in IE (if you allow "blocked content" when prompted)
Note II:  It will work in chrome if you launch chrome with the "--allow-file-access-from-files" command line option.
