### ISSUE TITLE
Viz 1.16.0-beta4 will not re apply dermatology

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#2223]
@jchambers-ln commented on [Thu Jun 08 2017](https://github.com/hpcc-systems/DSP/issues/2571)

### Version and Instance (URL) in which the issue was found or feature not available in
Viz 1.16.0-beta4 dsp/hipie 1.9.0
### Expected Behavior
save derm, reopen, it works
### Actual Behavior
Viz 1.16.0-beta4 will not re apply dermatology, widgets fail to load
### Steps to Reproduce the Issue
create dashboard with above viz version and then save layout, close the dashboard and reopen
### Other Details
Depends on fixes in VIZ Gordon is aware of

**Comment by GordonSmith** [comment]
Resolved.
