### ISSUE TITLE
HPCC Comms to send a >3000 ms fetching information...

### ISSUE THREAD

**Issue by miguelvazq** [hpcc-systems/Visualization#2235]
Gordon as we discussed can we integrate different callbacks that will give us status info on requests occurring. For example, I am fetching something that has a large response and it is taking longer than three seconds it would be nice for the U/I to know of this and display a toaster simply stating something such as "Fetching Information..." or something of the sort.

**Comment by GordonSmith** [comment]
Expired - please reopen if needed.
