### ISSUE TITLE
Table column hide 

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#2241]
ability to hide a column of data but to still use that data as the driving field for an interaction. 

Needed for Project if you could update Tianie on time frame

**Comment by GordonSmith** [comment]
@jchambers-ln If this is only for tables then I believe it is supported already:  https://github.com/hpcc-systems/Visualization/pull/2075

**Comment by jchambers-ln** [comment]
@GordonSmith I looked and didn't see a way to do it... if the linked pull does what it says then this is covered we just need educated on how to use it in the biz project requesting this.

**Comment by GordonSmith** [comment]
![image](https://user-images.githubusercontent.com/966863/28972293-08c6b43e-7927-11e7-89dc-f8da9d5046dc.png)

**Comment by GordonSmith** [comment]
Expired - please reopen if needed.
