### ISSUE TITLE
Turn off the (filter value) from widget titles

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#2242]
Ability to disable the (filter) from the widget title.

**Comment by GordonSmith** [comment]
Dup of:  https://github.com/hpcc-systems/Visualization/issues/2274

**Comment by jchambers-ln** [comment]
@GordonSmith can you post into this issue how to disable it?

**Comment by GordonSmith** [comment]
You can override the title by setting a "template" string in "ddlParamsFormat".  For example:   "{fname}, {lname}"
