### ISSUE TITLE
Choose a different column value to be displayed in the dependent widget title

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#2243]
Assuming you have a driving widget

PEOPLE
ID, Name
1, bob
2,fred
and a driven widget related on ID
INCOME
ID, Income
1, 30000
2, 45000

and you click on bob

it is displayed  as
INCOME(1)
1, 30000

Have the ability to set a different column (but still filter on the ID) so that you get 

INCOME(bob)
1,30000

https://jira.rsi.lexisnexis.com/browse/RAMPS-243

**Comment by GordonSmith** [comment]
Dup of:  https://github.com/hpcc-systems/Visualization/issues/2274
