### ISSUE TITLE
Change how between filter values are displayed at the top of widget

### ISSUE THREAD

**Issue by bwood1** [hpcc-systems/Visualization#2248]
I think using a dash to show the filter would be clearer than using a comma.
 
https://github.com/hpcc-systems/DSP/issues/2775

**Comment by GordonSmith** [comment]
@bwood1 Can you point me to an example?

**Comment by bwood1** [comment]
@GordonSmith in the example referenced in https://github.com/hpcc-systems/DSP/issues/2775 I would expect to see a dash in between the 4 and 6 because that's the between filter. Expected 'FL, GA, 2005, 4-6'  current 'FL, GA, 2005, 4,6'.

**Comment by GordonSmith** [comment]
@bwood1 sorry, I was looking for a link to a working example.

**Comment by bwood1** [comment]
It shows with a pipe now instead of a comma. You can close

<img width="108" alt="screen shot 2017-08-29 at 10 12 01 am" src="https://user-images.githubusercontent.com/2362888/29825486-930ac5f2-8ca2-11e7-9e15-d1479b8d15c6.png">

**Comment by GordonSmith** [comment]
@bwood1 - I want to test my new "override" title code with this specific case, which is why I am looking for a working dashboard to hit...

**Comment by bwood1** [comment]
@GordonSmith I can't find a working example with any of my existing dashboards and new dashboards are being generated with the pipe. I'm not sure how to re-produce this anymore.

**Comment by GordonSmith** [comment]
An example with the pipe will work for me.  The issue is about being able to tweak it at runtime.

**Comment by bwood1** [comment]
Share link via integration server:

http://172.23.42.86:8081/?composition=0658006c-a6fe-4fa7-9721-0cabd04e02f7 

workunit:

http://10.173.147.1:8010/?Wuid=W20170829-100735&Widget=WUDetailsWidget

raw viz:
http://viz.hpccsystems.com/v1.16.0/apps/legacyDash.html?Hostname=10.173.147.1&Port=8010&Protocol=http&Wuid=W20170829-100735&ResultName=rangebetweenexamplegordon_Comp_Ins4669136_DDL

**Comment by GordonSmith** [comment]
@bwood1, @drealeed the DDL in the above example is bad:
```
{
    "id": "month",
    "properties": {
        "datatype": "string",
        "default": [
            "2|4"
        ],
        "label": "month",
        "type": "string"
    }
}
```

Should be ```"type": "range"```?

**Comment by bwood1** [comment]
kjhsdfklajh on integration:

http://172.23.42.86:8081/?composition=23e1e48b-ecae-4d5e-a33e-feea8884b573

http://10.173.147.1:8010/?Wuid=W20170728-084904&Widget=WUDetailsWidget

http://viz.hpccsystems.com/v1.16.0-rc2/apps/legacyDash.html?Hostname=10.173.147.1&Port=8010&Protocol=http&Wuid=W20170728-084904&ResultName=kjhsdfklajh_Comp_Ins013_DDL


a111StaticRangeDemo on integration

http://172.23.42.86:8081/?composition=51a11c0d-d4bc-4866-9f0d-bcdcfd9a866a

**Comment by GordonSmith** [comment]
This is highlighting a HIPIE issue:  https://github.com/hpcc-systems/HIPIE/issues/2972
