### ISSUE TITLE
Drop down values not selected when rendered with filters applied

### ISSUE THREAD

**Issue by Mohammed-Idris-K-J** [hpcc-systems/Visualization#2249]
In one of the dashboards we have drop down selection. Drop down change works and appropriate filters are applied. But when we apply filters to the entire dashboard with the selection, the drop down goes empty.(Filters for dropdown is not retained)
![drop down](https://user-images.githubusercontent.com/20775282/28575882-42a2d926-7120-11e7-921d-0e50f17ff94f.png)

**Comment by GordonSmith** [comment]
Expired - please reopen if needed.
