### ISSUE TITLE
Widget sorted by default (when sort not specified)

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#2268]
@AdlinSteffi commented on [Tue Aug 01 2017](https://github.com/hpcc-systems/DSP/issues/2834)

DSP Version: 1.9.1-rc2; HIPIE Version: 1.9.1-rc3; VIZ Version: 1.16.0-rc3
Instance (URL):
http://172.23.42.86:8081/

Create a dashboard as given below:
Dashboard name: drcp
Datasource: ~.a::valid_file
Configure columns for Table: turnover, rowcount, companyname and place
Run the dashboard

Issue: Widget is sorted with respect to the 'Turnover' field by default
http://172.23.42.86:8081/?composition=45cdd86a-cd00-41e3-b7f5-ee6e622e2e2c
[drcp.zip](https://github.com/hpcc-systems/DSP/files/1189753/drcp.zip)
![image](https://user-images.githubusercontent.com/18044342/28813478-07cef0f4-76b7-11e7-894c-9d0248e60164.png)

 

---

@jchambers-ln commented on [Tue Aug 01 2017](https://github.com/hpcc-systems/DSP/issues/2834#issuecomment-319402539)

The generated output from hipie is not sorted so I think this is in Viz.
@GordonSmith 

---

@jchambers-ln commented on [Tue Aug 01 2017](https://github.com/hpcc-systems/DSP/issues/2834#issuecomment-319402690)

Issue moved to [hpcc-systems/Visualization #2267](https://github.com/hpcc-systems/Visualization/issues/2267) via [**ZenHub**](https://www.zenhub.com/)

**Comment by GordonSmith** [comment]
Currently Once there is a group-by / aggregate is specified, the default sort order will be undetermined.  

I can attempt to make this process "stable" (I had some code in one of my recent PRs, which got rolled back.

(this is not a new issue)

**Comment by GordonSmith** [comment]
Expired - please reopen if needed.
