### ISSUE TITLE
When interaction is A->B->C, C is automatically populated with all values on load

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#2270]
@AdlinSteffi commented on [Tue Aug 01 2017](https://github.com/hpcc-systems/DSP/issues/2831)

DSP Version: 1.9.1-rc2; HIPIE Version: 1.9.1-rc3; VIZ Version: 1.16.0-rc3
Instance (URL):
http://172.23.42.86:8081/

Create dashboard 'au11' with three table, bar and column widgets (four-way)
File: ~dinesh::oklahoma::thor::dashboard::auditlatency

Add table with columns:
bestprojectedlatency (AVE)
workeroffice
Local filter: year (2015)

Add bar chart with attributes:
Measure: bestprojectedlatency (AVE)
Attribute: quarter

Add coloumn chart with attributes :
Measure: bestprojedectlatency (AVE)
Attribute: month

Provide interaction:
Table (workeroffice) -> Bar (workeroffice)
Bar (quarter) -> Coloumn (quarter)

Run the dashboard
http://172.23.42.86:8081/?composition=c598b991-a2b6-4167-ac5f-fb3d75bf73ee
[au11.zip](https://github.com/hpcc-systems/DSP/files/1189586/au11.zip)

Issue: On load, the column chart is automatically populated with all the values. 
![image](https://user-images.githubusercontent.com/18044342/28810958-0e9433c0-76aa-11e7-9c6a-0a30eac49bed.png)

---

@jchambers-ln commented on [Tue Aug 01 2017](https://github.com/hpcc-systems/DSP/issues/2831#issuecomment-319398699)

generated DUD syntax looks right.  Nothing is nullable.

@GordonSmith @drealeed is this Viz or hipie?

---

@drealeed commented on [Tue Aug 01 2017](https://github.com/hpcc-systems/DSP/issues/2831#issuecomment-319478984)

@GordonSmith , When this is viewed with 1.16.0-beta5, it works:
http://viz.hpccsystems.com/v1.16.0-beta5/apps/legacyDash.html?Hostname=10.173.147.1&Port=8010&Protocol=http&Wuid=W20170801-013455&ResultName=au11_Comp_Ins071_DDL

with rc3, it does not:
http://viz.hpccsystems.com/v1.16.0-rc3/apps/legacyDash.html?Hostname=10.173.147.1&Port=8010&Protocol=http&Wuid=W20170801-013455&ResultName=au11_Comp_Ins071_DDL

**Comment by GordonSmith** [comment]
Resolved in rc4
