### ISSUE TITLE
Form / Submit on enter press

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#2272]
Add support for pressing "enter" to submit the form

**Comment by jbrundage** [comment]
Should this only apply while one of the form's inputs has focus? I think that's the expected functionality.

**Comment by GordonSmith** [comment]
Yes - and it may be working already, needs a retest

**Comment by GordonSmith** [comment]
Appears to work - but the following would help the UI experience:
* auto focus first field
* Make submit the "default" (can you do this in html?)

**Comment by jbrundage** [comment]
I know some browsers will treat a button as an input with type="submit" if its the only button with that form, but I think the behavior is inconsistent between browsers.
