### ISSUE TITLE
REOPENED: LN Font Style

### ISSUE THREAD

**Issue by sunsan01** [hpcc-systems/Visualization#2279]
Defaulting the font styles used in dashboards to the same font used during creation regardless of where they're viewed so that all dashboards would look consistent with the final dashboard presented.

**Comment by GordonSmith** [comment]
I will need to think about this - as it stands the framework is designed to use the default front from the hosting web page so it fits in better.  It is possible for the hosting page to force any font on the dashboards via CSS as well (Just a FYI).

**Comment by GordonSmith** [comment]
Expired - please reopen if needed.
