### ISSUE TITLE
Descending sort in layout designer does not persist on re-open

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#2282]
@AdlinSteffi commented on [Wed Aug 09 2017](https://github.com/hpcc-systems/DSP/issues/2855)

DSP Version: 1.9.1-rc2; HIPIE Version: 1.9.1-rc4; VIZ Version: 1.16.0-rc5
Instance (URL):
http://172.23.42.86:8081/

Create dashboard 'a1941_6'
Select Table widget
Select ~.::thousands_seperator_format
Configure the columns: v2015, v2016
Change the aggregation of v2016 to SUM
Run the dashboard
Click the column header SUM(v2016)
Click Layout Designer
Select the descending checkbox
Save the layout
The values are sorted in descending:
![2017-08-09_134404](https://user-images.githubusercontent.com/18044342/29111867-a1655868-7d09-11e7-9fc3-4e4575e3435f.png)
Close the dashboard
Click the dashboard link again
Issue: The descending sort does not persist;
![2017-08-09_134435](https://user-images.githubusercontent.com/18044342/29111930-cf5ad9f0-7d09-11e7-9108-e3b5f9a3f78e.png)

---

@jchambers-ln commented on [Wed Aug 09 2017](https://github.com/hpcc-systems/DSP/issues/2855#issuecomment-321282913)

Seems, the header is reflecting the sort settings but the data isn't sorted correctly... @GordonSmith I believe this is in your house.

**Comment by hamiltwp** [comment]
Just to note here, aggregation and multiple columns are not necessary to reproduce the issue.
[sorting.zip](https://github.com/hpcc-systems/Visualization/files/1468159/sorting.zip)

**Comment by GordonSmith** [comment]
Expired - please reopen if needed.
