### ISSUE TITLE
Title bar not displayed when Legend position is set at the top

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#2283]
@AdlinSteffi commented on [Fri Aug 26 2016](https://github.com/hpcc-systems/DSP/issues/1918)

#1860

Create a Line widget
Run the dashboard
Click Layout Designer
Select legendPosition to be at the top
Click Save
Select the Legend checkbox at the top

Issue: The title bar at the top completely disappears
http://172.23.40.63:9090/DSP_DEV/?composition=8f07e994-c0ee-47bf-9eea-e00998d936dc
![image](https://cloud.githubusercontent.com/assets/18044342/17995828/7c590860-6b82-11e6-8513-892fe5354c9e.png)

---

@dabayliss commented on [Fri Aug 26 2016](https://github.com/hpcc-systems/DSP/issues/1918#issuecomment-242705569)

@GordonSmith is title bar still you? Or could that be us ?

---

@GordonSmith commented on [Fri Aug 26 2016](https://github.com/hpcc-systems/DSP/issues/1918#issuecomment-242705991)

Its me.

---

@jchambers-ln commented on [Thu Jun 29 2017](https://github.com/hpcc-systems/DSP/issues/1918#issuecomment-312047908)

@GordonSmith was there a viz issue opened?

---

@jchambers-ln commented on [Mon Aug 07 2017](https://github.com/hpcc-systems/DSP/issues/1918#issuecomment-320679271)

@GordonSmith this still occurs in 1.16.0-rc4 do you have an issue open?

**Comment by GordonSmith** [comment]
Expired - please reopen if needed.
