### ISSUE TITLE
Can't overlap charts in 1.16.0

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#2286]
You can't overlap charts, this is used when using a table as a Key/Legend.  @jbrundage can you comment on the importance of this for you?

**Comment by GordonSmith** [comment]
I don't have any easy fixes for this - really the "legend" issue needs to be addressed properly for 2.0 as there will be no overlapping there either.

We do support "overlayed" widgets in general, but it the WYSIWYG layout engine that is the problem.

**Comment by GordonSmith** [comment]
Expired - please reopen if needed.
