### ISSUE TITLE
Graph interactions not working

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#2287]
See email for example

I don’t see any network calls being made to roxie when a graph node is clicked. I am seeing this in the console error logs:

Invalid value for 'dataFamily':  GRAPH expected set

Also, clicking on another item in search clears out the widget rather than updating it.

**Comment by drealeed** [comment]
Here's the url: 
http://viz.hpccsystems.com/v1.16.0/apps/legacyDash.html?Hostname=10.241.100.157&Port=8010&Protocol=http&Wuid=W20170817-124520&ResultName=govbisgsavi_Comp_Ins4621360_DDL
