### ISSUE TITLE
Error puts visulaization into a bad state when embeded into a product

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#2300]
See https://github.com/hpcc-systems/DSP/issues/2950 

If a error occurs other dashboards fail to load due to certain errors with in the same session.

**Comment by jbrundage** [comment]
@jchambers-ln Could I get access to the DSP repo?

Does that DSP#2950 contain an isolated example of this? I think this type of application-breaking js error is solely caused by "Maximum call stack" errors

**Comment by jchambers-ln** [comment]
@jbrundage you will need to do a ticket for access to the dev environment. But I thought you already had access.  Email me on access since this conversation is public.

**Comment by jchambers-ln** [comment]
@jbrundage this seems to be occurring with more regularity any luck with solving it?

**Comment by GordonSmith** [comment]
Expired - please reopen if needed.
