### ISSUE TITLE
Report some errors to user

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#2301]
Some errors make sense to display to the user and not just output to the console.  Either a interface for the embeding app to call or add a message capability to the frame work to show this to the user.

example: error: Roxie 1403:  Unknown query testdspdevdeveloper_mbs_b2933_121655.Ins001_Service_1, in target roxie  hpcc-viz-other.js:8:28756

See https://github.com/hpcc-systems/DSP/issues/2950

**Comment by GordonSmith** [comment]
Expired - please reopen if needed.
