### ISSUE TITLE
tool tip doesn't load if large number of slices (Intermittent)

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#2306]
I was testing another issue and generated a dashboard with a driving widget with 308 slices in it, updating a table with the exact data.  (rowcout, origin_iata [basically the count of flights departing an airport]).  After changing from AM_PIE to C3_PIE and deselecting the clear data I saved the layout.  At that point the tool tip didn't load on the pie when you hover over it... the interaction would still occur.

After refreshing my browser it worked fine.

I think it was a resource issue as the amount of data as pushing the memory usage in Firefox. 

This is the workunit I was testing against. 
http://10.173.147.1:8010/?Wuid=W20170920-105943&Widget=WUDetailsWidget#/stub/Summary

**Comment by jbrundage** [comment]
Are you able to reliably reproduce this issue or is it somewhat randomly occurring?

**Comment by jchambers-ln** [comment]
random

**Comment by GordonSmith** [comment]
Expired - please reopen if needed.
