### ISSUE TITLE
Liquid Fill Gauge widget

### ISSUE THREAD

**Issue by mounicarachakonda** [hpcc-systems/Visualization#2309]
Should return an object with an update method which allows the gauge value to be changed.

Features should include:

Changeable min/max values.
All colors.
Outer circle thickness.
Gap between the outer circle and inner fill area.
Wave height.
Wave speed.
Wave count.
Wave rise time.
Wave height scaling on/off. Reduces the wave height near the min/max values so that the wave won't make the fill area appear total full or totally empty.
Wave starting offset. Most useful when wave animation is turned off and you want the wave min or max at a specific horizontal position in the fill area.
Wave rising upon load on/off.
Wave animation on/off.
Text height.
Text vertical position.
Text increment from min value upon loading.
Display of % symbol on/off.

**Comment by mounicarachakonda** [comment]
GH-2310

**Comment by GordonSmith** [comment]
Expired - please reopen if needed.
