### ISSUE TITLE
zooming

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#231]
if you double click on a Choropleth it zooms both the Choropleth 
![vizualizationglitch](https://cloud.githubusercontent.com/assets/1529783/6357305/660175d6-bc31-11e4-9a66-b192b7828326.jpg)
and the rest of the screen, though google charts don't zoom

**Comment by GordonSmith** [comment]
This has been resolved and is waiting on a review.

**Comment by GordonSmith** [comment]
@jchambers-ln Is this ok to close now?

**Comment by GordonSmith** [comment]
Closing Fixed.
