### ISSUE TITLE
GMap streetView publish parameter is no longer working

### ISSUE THREAD

**Issue by jbrundage** [hpcc-systems/Visualization#2330]
Google maps api must have changed in some way that prevents `.streetView(true)`  from enabling Street View mode.

http://rawgit.com/hpcc-systems/Visualization/candidate-1.16.x/demos/dermatology.html?src/map/GMap.splitStreetView
http://rawgit.com/hpcc-systems/Visualization/candidate-1.18.x/demos/dermatology.html?src/map/GMap.splitStreetView
http://rawgit.com/hpcc-systems/Visualization/candidate-1.20.x/demos/dermatology.html?src/map/GMap.splitStreetView

**Comment by GordonSmith** [comment]
Resolved in 1.20.x
