### ISSUE TITLE
ChartPanel: Info/Summary button

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#2335]
* Should be a ToggleButton
* Should be associated with a HtmlWidget or TextWidget or MarkdownWidget
* When "on" it will show the Widget as floating / transparent / modal DIV centered and resized over the main ChartPanel content
* When "off" + when the mouse hovers over the button (tooltip), it should also show the modal dialog in a similar way to when it is on, but be more transparent?  And it should "feel" like a tooltip.

**Comment by jbrundage** [comment]
How should content be provided for this info/summary? A "string" publish param on the ChartPanel for that purpose?
