### ISSUE TITLE
Phosphor:  Add "design mode" toggle to Dock Panel

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#2339]
Design Mode should support:
* Enable/Disable dragging of tabs from one "cell" to another "cell"
* Enable/Disable reordering of tabs in a single cell
* Show/Hide Single Tabs:  If only one tab exists at a given cell, then it should only be displayed in "design mode"

**Comment by jbrundage** [comment]
Rather than having to modify the phosphor source code, maybe we could just override the drag events?

**Comment by GordonSmith** [comment]
Partially resolved in 2.0
