### ISSUE TITLE
TitleBar:  "Make Responsive"

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#2344]
If the space for the title bar is too small (in a ChartPanel) then it should collapse to a single "menu" button, which in turn shows the items as a drop menu when clicked.

**Comment by jbrundage** [comment]
Want to use some Primer styles for the drop down menu?

**Comment by jbrundage** [comment]
Like this: https://primer.github.io/storybook/?selectedKind=Box&selectedStory=Box--condensed&full=0&down=0&left=1&panelRight=0

**Comment by GordonSmith** [comment]
Resolved in 2.0
