### ISSUE TITLE
FontAwesome + rollup bundles

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#2372]
Need to replace the relative URLs in the css with a @hpcc-js/common reference.

**Comment by jbrundage** [comment]
Maybe SASS integration should take place before this change?

**Comment by GordonSmith** [comment]
I suspect this issue will still prevail (unless there are sass files in the font-awesome project.

A relatively simple search/replace with the rollup bundle will fix it.

**Comment by jbrundage** [comment]
font-awesome does offer Less and Sass support

**Comment by GordonSmith** [comment]
Expired - please reopen if needed.
