### ISSUE TITLE
Update main readme.md for transition from 1.20 -> 2.0 

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#2388]
Will need to to merge the candidate-2.0.x into master soon.

Also we should have a readme for each package, with some sort of demo page (on observerhq maybe?)

**Comment by jbrundage** [comment]
Maybe add a "package_demo" test for each widget's dermatology/tests/nnnnFactory list. Then these observerhq package demo pages can display a grid of each widget's "package_demo"? 

(Or I guess we could just display the "simple" but that's not as exciting)

**Comment by GordonSmith** [comment]
Resolved in 2.0
