### ISSUE TITLE
Errors when requiring modules within Observablehq

### ISSUE THREAD

**Issue by jbrundage** [hpcc-systems/Visualization#2399]
Attempting to require "/map", "/other", "/composite", and/or "/marshaller" results in this error:
![image](https://user-images.githubusercontent.com/1891935/36041493-b7584cac-0d96-11e8-9f22-02e0dda0d506.png)

Attempting to require "/ddl-shim", and/or "/react" results in this error:
![image](https://user-images.githubusercontent.com/1891935/36041729-7bc7ee44-0d97-11e8-990c-2200df89cff3.png)

Attempting to require "/requirejs-shim" results in this error:
![image](https://user-images.githubusercontent.com/1891935/36041776-a5803692-0d97-11e8-9f91-6453e06e530c.png)

@GordonSmith the rest of the packages work just fine

**Comment by GordonSmith** [comment]
The first should be resolved with:  https://github.com/hpcc-systems/Visualization/pull/2398  I will take a look at the other two.

**Comment by GordonSmith** [comment]
Expired - please reopen if needed.
