### ISSUE TITLE
Flyout menu auto closes when 'autoCloseFlyout' option is unchecked

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#2434]
@AdlinSteffi commented on [Thu Mar 15 2018](https://github.com/hpcc-systems/DSP/issues/3539)

DSP Version: 1.11.0-SNAPSHOT; HIPIE Version: 1.11.0-SNAPSHOT; VIZ Version: 1.18.2
http://xxx.xxx.xxx.xxx:8081/

Create a dashboard
Provide a local filter
Run the dashboard
Click Layout designer
Uncheck autoCloseFlyout
Save the layout
Open the filter flyout, provide a filter value and click Submit
http://xxx.xxx.xxx.xxx:8081/?composition=dba93bd8-96b7-446e-ac5d-e8ae0afe51da

Expected: The flyout menu should not automatically close
Actual: The flyout menu automatically closes on Submit

---

@jchambers-ln commented on [Mon Mar 19 2018](https://github.com/hpcc-systems/DSP/issues/3539#issuecomment-374217139)

@GordonSmith this I believe is a visualization issue.

**Comment by jchambers-ln** [comment]
@GordonSmith I blanked out the IP's if you need to look back at it they are still available in the DSP issue.

**Comment by jbrundage** [comment]
@jchambers-ln two questions: 

1. When you close and reload that dashboard does it fix the issue? In other words... "autoCloseFlyout" might only work as expected if it's unchecked while initializing the dashboard.
2. When you close and reload that dashboard does the Layout designer display "autoCloseFlyout" as unchecked? In other words... is that parameter persisting properly?
