### ISSUE TITLE
Double ended slider

### ISSUE THREAD

**Issue by bwood1** [hpcc-systems/Visualization#2456]
We have a need for a double ended slider that can be used for a between interaction. Example is pictured below for doing a range of 2000 - 2001.

<img width="1413" alt="screen shot 2018-03-30 at 2 16 20 pm" src="https://user-images.githubusercontent.com/2362888/38148578-17bb1dae-3425-11e8-811f-813655d22caa.png">

**Comment by GordonSmith** [comment]
If you set the "allowRange" option to true it will enable that feature, but I suspect it will need some marshaller work to know how to return the range back to roxie?

https://rawgit.com/hpcc-systems/Visualization/candidate-1.20.x/demos/dermatology.html?src/form/Slider.range&allowRange=true

**Comment by bwood1** [comment]
Yes it will also need to be able to send a two tailed value to another widget like we do with between filters "2000|2001"

**Comment by GordonSmith** [comment]
Expired - please reopen if needed.
