### ISSUE TITLE
More space to see provider and business graph

### ISSUE THREAD

**Issue by senthilkumarperiasamy** [hpcc-systems/Visualization#2462]
can we increase the screen size to visualize business and provider graph? Business is requesting this enhancement as part of Suspect Address 2.0 release. Also, is it possible to hide/unhide legends in the graph?

**Comment by GordonSmith** [comment]
@senthilkumarperiasamy Is this the same issue where I suggested letting the user switch from "Hierarchy" to "ForceDirected"?  

Also there is no legend to hide unhide?

**Comment by jbrundage** [comment]
Per Senthil this will be handled at the Portal application layer
