### ISSUE TITLE
Auto hide columns with no data in table widget and dynamically change column name

### ISSUE THREAD

**Issue by senthilkumarperiasamy** [hpcc-systems/Visualization#2566]
For SA 2.0 release, business is asking if we can auto-hide columns with no data and dynamically change column names in the table.

**Comment by GordonSmith** [comment]
@senthilkumarperiasamy do you have:
1. An ETA for this?
2. A target version for the viz framework (1.18,1.20,2.0 etc.)

Can you elaborate on the dynamic changing of column names?

**Comment by GordonSmith** [comment]
Resolved with:  https://github.com/hpcc-systems/Visualization/pull/2628
