### ISSUE TITLE
DDL chartType info + visualization section

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#2574]
Move the chart type information into the "properties section" so hipie knows to persist it as _ stuff.

@drealeed maybe the entire visualization section should be persisted as "_XXX"  and have no "properties"?
@drealeed I think you will want to persist nested properties as well (could be as simple as "_xxx.yyyy")?

**Comment by drealeed** [comment]
@GordonSmith , what I'm planning to do is add a DERMATOLOGY() tag to each visualization and stash all the viz properties in there. chartType is currently exposed to the user so they can "set it ahead of time", but with the new dashboard designer paradigm that won't be necessary.

**Comment by GordonSmith** [comment]
@drealeed Are the terms "PIE", "TABLE", "LINE", "GRAPH" dead now?

**Comment by drealeed** [comment]
Yes, as of ddl2.0, assigning the chart types will be relegated to the viz dashy app in the dashboard mini-app.

**Comment by GordonSmith** [comment]
Good.

**Comment by drealeed** [comment]
Closing--turns out this isn't needed due to HIPIE dermatology design decisions
