### ISSUE TITLE
Summary Widget Doesn't Display More Info when no Data Provided

### ISSUE THREAD

**Issue by stermi01** [hpcc-systems/Visualization#2576]
I’ve noticed an issue with the summary widget where if there is never a possible output for the widget it will display a blank yellow box with no information. While this makes sense logically since there is no information being generated for the widget, we would really like the set info tab to be displayed in the event that there is no data to display still. Is that something that we can change on our end or is it an option that needs to be added?

The composition is the following on DSP-QA:
GOV-BIS-CustomerStats-V2

I’ve also added in the DDL if you need it.

http://10.241.100.157:8010/WsWorkunits/WUResult.json?Wuid=W20180517-144805&ResultName=govbiscustomerstatsv2_Comp_Ins4811344_DDL&SuppressXmlSchema=true

**Comment by GordonSmith** [comment]
@stermi01 Can you let me know which version you are currently using so I can target a fix?

**Comment by stermi01** [comment]
DSP Version :1.10.2.1
HIPIE Version :1.10.1.1
VIZ Version :1.18.2
Salt Version :SALT32
Minimum HPCC Version :5.6.4-1
KEL Version :
Dermatology Version :1.3.1
