### ISSUE TITLE
ddl1-to-ddl2 upgrade not handling nested visualizations

### ISSUE THREAD

**Issue by drealeed** [hpcc-systems/Visualization#2581]
I converted a DDL that had a nested visualization within a visualization. It didn’t convert correctly. Here’s the ddl1:
{
                "dashboards": [{
                                "id": "Ins011_suspectaddressbardashboard",
                                "label": "suspectaddressbardashboard",
                                "title": "suspectaddressbardashboard",
                                "visualizations": [{
                                                "fields": [{
                                                                "id": "addrline1",
                                                                "properties": {
                                                                                "datatype": "string50",
                                                                                "type": "string50"
                                                                }
                                                }, {
                                                                "id": "city",
                                                                "properties": {
                                                                                "datatype": "string20",
                                                                                "type": "string20"
                                                                }
                                                }, {
                                                                "id": "state",
                                                                "properties": {
                                                                                "datatype": "string2",
                                                                                "type": "string2"
                                                                }
                                                }, {
                                                                "id": "zip",
                                                                "properties": {
                                                                                "datatype": "string5",
                                                                                "type": "string5"
                                                                }
                                                }, {
                                                                "id": "suspectflags",
                                                                "properties": {
                                                                                "datatype": "dataset",
                                                                                "localVisualizationID": "nestedtable01",
                                                                                "type": "visualization"
                                                                }
                                                }, {
                                                                "id": "noofproviders",
                                                                "properties": {
                                                                                "datatype": "integer2",
                                                                                "type": "integer2"
                                                                }
                                                }, {
                                                                "id": "totalpaid",
                                                                "properties": {
                                                                                "datatype": "integer8",
                                                                                "type": "integer8"
                                                                }
                                                }, {
                                                                "id": "totalclaim",
                                                                "properties": {
                                                                                "datatype": "integer8",
                                                                                "type": "integer8"
                                                                }
                                                }, {
                                                                "id": "addrscore",
                                                                "properties": {
                                                                                "datatype": "integer2",
                                                                                "type": "integer2"
                                                                }
                                                }],
                                                "id": "table01",
                                                "label": ["Address Line1", "City", "State", "Zip", "Suspect Flags", "# of Providers", "Paid Dollars(All Provider)", "# of Claims(All Providers)", "Score"],
                                                "properties": {
                                                                "charttype": "TABLE",
                                                                "itemsPerPage": 10,
                                                                "missingDataString": true,
                                                                "pagination": false
                                                },
                                                "source": {
                                                                "id": "Ins011_AddressTab",
                                                                "mappings": {
                                                                                "value": ["addrline1", "city", "state", "zip", "suspectflags", "noofproviders", "totalpaid", "totalclaim", "addrscore"]
                                                                },
                                                                "output": "View_table01"
                                                },
                                                "title": "Top Suspect Addresses",
                                                "type": "TABLE",
                                                "visualizations": [{
                                                                "fields": [{
                                                                                "id": "cnt",
                                                                                "properties": {
                                                                                                "datatype": "integer2",
                                                                                                "label": "#",
                                                                                                "type": "integer2"
                                                                                }
                                                                }, {
                                                                                "id": "reason",
                                                                                "properties": {
                                                                                                "datatype": "string100",
                                                                                                "label": "Reason",
                                                                                                "type": "string100"
                                                                                }
                                                                }],
                                                                "id": "nestedtable01",
                                                                "label": ["#", "Reason"],
                                                                "properties": {
                                                                                "pagination": false
                                                                },
                                                                "source": {
                                                                                "id": "Ins011_AddressTab",
                                                                                "mappings": {
                                                                                                "value": ["cnt", "reason"]
                                                                                },
                                                                                "output": "View_table01"
                                                                },
                                                                "type": "TABLE"
                                                }]
                                }]
                }],
                "datasources": [{
                                "URL": "http://10.241.100.159:8002/WsEcl/submit/query/roxie/leeddx_issue_2047_nestedtable.Ins011_Service/json",
                                "id": "Ins011_AddressTab",
                                "outputs": [{
                                                "from": "View_table01",
                                                "id": "View_table01",
                                                "notify": ["table01"]
                                }]
                }],
                "hipieversion": "1.11.0",
                "visualizationversion": "<ECLSTRINGBREAK> + $.HIPIEConfig.VizVersion + <ECLSTRINGBREAK>"
}

And here’s the ddl2:
{
                "version": "0.0.21",
                "datasources": [{
                                "type": "hipie",
                                "id": "Ins011_AddressTab",
                                "url": "http://10.241.100.159:8002",
                                "querySet": "roxie",
                                "queryID": "leeddx_issue_2047_nestedtable.Ins011_Service",
                                "inputs": [],
                                "outputs": {
                                                "View_table01": {
                                                                "fields": []
                                                }
                                }
                }],
                "dataviews": [{
                                "id": "table01",
                                "datasource": {
                                                "id": "Ins011_AddressTab",
                                                "request": [],
                                                "output": "View_table01"
                                },
                                "activities": [{
                                                "type": "project",
                                                "transformations": []
                                }, {
                                                "type": "filter",
                                                "conditions": []
                                }, {
                                                "type": "sort",
                                                "conditions": []
                                }, {
                                                "type": "groupby",
                                                "groupByIDs": [],
                                                "aggregates": []
                                }, {
                                                "type": "limit",
                                                "limit": 0
                                }, {
                                                "type": "mappings",
                                                "transformations": [{
                                                                "fieldID": "Address Line1",
                                                                "type": "=",
                                                                "sourceFieldID": "addrline1"
                                                }, {
                                                                "fieldID": "City",
                                                                "type": "=",
                                                                "sourceFieldID": "city"
                                                }, {
                                                                "fieldID": "State",
                                                                "type": "=",
                                                                "sourceFieldID": "state"
                                                }, {
                                                                "fieldID": "Zip",
                                                                "type": "=",
                                                                "sourceFieldID": "zip"
                                                }, {
                                                                "fieldID": "Suspect Flags",
                                                                "type": "=",
                                                                "sourceFieldID": "suspectflags"
                                                }, {
                                                                "fieldID": "# of Providers",
                                                                "type": "=",
                                                                "sourceFieldID": "noofproviders"
                                                }, {
                                                                "fieldID": "Paid Dollars(All Provider)",
                                                                "type": "=",
                                                                "sourceFieldID": "totalpaid"
                                                }, {
                                                                "fieldID": "# of Claims(All Providers)",
                                                                "type": "=",
                                                                "sourceFieldID": "totalclaim"
                                                }, {
                                                                "fieldID": "Score",
                                                                "type": "=",
                                                                "sourceFieldID": "addrscore"
                                                }]
                                }],
                                "visualization": {
                                                "id": "table01",
                                                "title": "Top Suspect Addresses",
                                                "description": "",
                                                "chartType": "TABLE",
                                                "moduleName": "@hpcc-js/grid",
                                                "className": "Table",
                                                "properties": {
                                                                "charttype": "TABLE",
                                                                "itemsPerPage": 10,
                                                                "missingDataString": true,
                                                                "pagination": false
                                                }
                                }
                }]
}

**Comment by GordonSmith** [comment]
Note to self:  This is primarily for display viz in table via child dataset (where the child dataset can be aggregated sorted and mapped etc.).
