### ISSUE TITLE
ddl1-to-ddl2: filter fields that aren't displayed not retained in filter activity

### ISSUE THREAD

**Issue by drealeed** [hpcc-systems/Visualization#2604]
I have a table that's grouped by unique carrier, year, month, destination state and origin state with the aggregation being the average of arrdelay.

Of these fields, month, year, destination state and origin state are filtered.

Of these fields, only unique carrier, year and ave(arrdelay) are shown.

In this case, the converted ddl2 doesn't list origin_state in  the filter fields that are being shown.

attached are the ddl1 and the ddl2 that it generated.

a working service (1.18.2) is also at 
http://10.173.147.1:8002/WsEcl/submit/query/roxie/leeddx_issue_2810_filterclasscast.Ins046_Service_1/json?month_changed=true&month=1&dest_state_changed=true&dest_state=GA&origin_state_changed=true&origin_state=FL&year_min_changed=false&year_min=2000&year_max_changed=false&year_max=2007&refresh=false

I noticed that with 1.18.2 as well, even though origin_state is listed as a filter in the ddl1, the visualization fails to send the origin_state parameter from the form. 

[ddl1.json.txt](https://github.com/hpcc-systems/Visualization/files/2077448/ddl1.json.txt)
[ddl2.json.txt](https://github.com/hpcc-systems/Visualization/files/2077449/ddl2.json.txt)

**Comment by GordonSmith** [comment]
This sounds like its related to:  https://github.com/hpcc-systems/Visualization/issues/2605
