### ISSUE TITLE
Radar Chart error when first value is 0

### ISSUE THREAD

**Issue by lesterlpena** [hpcc-systems/Visualization#2647]
Having this test data:
data = ['Value1', 0, 55],
            ['Value2', 0, 61],
            ['Value3', 0, 45],
            ['Value4', 0, 50],

We get this error: 
`Cannot read property '1' of undefined at SVGTextElement.eval`

Please let me know if you need more information.
Regards

**Comment by GordonSmith** [comment]
Resolved
