### ISSUE TITLE
Add option to dynamically change modalIfData title

### ISSUE THREAD

**Issue by jbrundage** [hpcc-systems/Visualization#2686]
Senthil requested this option today.

**Comment by senthilkumarperiasamy** [comment]
I need this option for SA 2.0 release. We want to show historical data at the patient, address and provider level. We are using one table to show different attributes.

**Comment by GordonSmith** [comment]
@jbrundage Did this get resolved?

**Comment by jbrundage** [comment]
@senthilkumarperiasamy The `ddlParamsFormat` publish parameter can be used (within a DUD file) to include values from your search parameters into the resulting modal's title.

For example: 
Given these parameters: `.title('Some Title').ddlParamsFormat('{fname}, {lname}')` and a search for `John Doe` would result in a modal title: `Some Title (Doe, John)`
