### ISSUE TITLE
Package and expose as bower dependency

### ISSUE THREAD

**Issue by boneill42** [hpcc-systems/Visualization#269]
@deanpoulin
Can we take a look at what it would take to package this as a bower dependency?
(and get it published to a public repo?)

**Comment by GordonSmith** [comment]
I did look into this and got it working about 80% - it fell down with the dagre lib as it had invalid bower information (at the time).  It would be good to get it working though...

**Comment by GordonSmith** [comment]
(That was a big yes BTW)

**Comment by GordonSmith** [comment]
Closing Fixed.
