### ISSUE TITLE
Incorrect resultName when loading Dashy from wuresult

### ISSUE THREAD

**Issue by woodbr01** [hpcc-systems/Visualization#2736]
The result name getting populated in the data tab is incorrect. It seems like in the upgrade from v1 to v2 viz is grabbing the wrong value for result name. In the example below it should be grabbing 'from' but is actually getting 'id'.

"outputs": [{
    "from": "Ins265_dsOutput1_View_a",
    "id": "View_a",
    "notify": ["a"]
}]

**Comment by GordonSmith** [comment]
I believe this is resolved:  https://github.com/hpcc-systems/Visualization/commit/ee1369f0fe5b5e726f26de1122d4ef93b22ba756
