### ISSUE TITLE
ddl1-to-ddl2: casing lost during conversion

### ISSUE THREAD

**Issue by drealeed** [hpcc-systems/Visualization#2828]
It looks like the mappings are being all lowercased in upgrade.ts.  This is causing dashboards not to show up due to the ddl mapping fields not matching the casing of the actual data.

[ddl1cased.json.txt](https://github.com/hpcc-systems/Visualization/files/2337957/ddl1cased.json.txt)

**Comment by GordonSmith** [comment]
@drealeed There are two scenarios here:
1. We upgrade the DDL to v2, but leave the existing service alone (v1 hipie genrated).
2. We upgrade the DDL to v2 _and_ upgrade the service to one generated by Hipie 2.0?

How realistic are both the above?

**Comment by GordonSmith** [comment]
https://github.com/hpcc-systems/Visualization/pull/2864
