### ISSUE TITLE
Tooltip issues

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#2880]
Some issues with the tooltip:
* When forced to the bottom, the arrow is not taken into consideration:
![image](https://user-images.githubusercontent.com/966863/45942956-64397e80-bfdc-11e8-8dcc-664528a5ca4b.png)
* The left and right arrows are a lot bigger then the top/bottom ones:
![image](https://user-images.githubusercontent.com/966863/45942994-892df180-bfdc-11e8-80f7-4d5a6e8e30ba.png)
* Text is making it outside of the balloon:
![image](https://user-images.githubusercontent.com/966863/45998639-5d257580-c09b-11e8-8731-db685be9162b.png)

**Comment by jbrundage** [comment]
@GordonSmith I've fixed the tooltip arrow issues with #2886. Could we track the text overlap issue separately? Are there any test cases that are known to cause that overflow issue? It looks like that tooltip has custom html and there are too many possible causes that come to mind that could cause that text overflow.

**Comment by GordonSmith** [comment]
Yes - as long as you open a new issue for it.
