### ISSUE TITLE
ddl1-to-ddl2 upgrade issue with faChar

### ISSUE THREAD

**Issue by drealeed** [hpcc-systems/Visualization#2917]
A ddl1 that has "faChar":"0xf007" will produce a ddl2 that has "faChar":"".  Looks like the issue is in the faCharFix() code in upgrade.ts.

Here's an example ddl1 experiencing the issue:
[facharddl.txt](https://github.com/hpcc-systems/Visualization/files/2457276/facharddl.txt)

**Comment by GordonSmith** [comment]
FWIW There is no diff between the two - but it may be better to keep the Hex version of the char.
