### ISSUE TITLE
Add README.md to each package

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#2944]
Ensure there is a README.md for each package.

Each readme should have the same opening paragraph (see https://github.com/hpcc-systems/Visualization/blob/candidate-2.x.x/packages/dgrid-shim/README.md).

Do a single README for Chart first and we can review on a per package basis?

Each README should contain:
* A bullet point list of the "major" exported Widgets (so for Chart I would expect a list of all the charts, but not things like XYAxis or Axis...)
* A link to the gallery (ideally to the sub category and not the root folder).
* Some sample images inline

**Comment by jbrundage** [comment]
These are the remaining packages that need a README.md (excluding the shim packages):
* api
* comms
* composite
* eclwatch
* form
* html
* loader
* marshaller
* other
* phosphor
* react
* timeline
* util
Are there any I should remove from this list? And should the shims have README.md files as well?

**Comment by GordonSmith** [comment]
I would skip:
* api
* eclwatch
* react

And for marshaller  I would expect a users guide to the dashy app - not sure if that belongs in the marshaller package or elsewhere?

**Comment by jbrundage** [comment]
@GordonSmith The stand-alone html sample for composite is throwing an error that `require` is undefined.

I tried including the `loader` package, but then it throws this error: `Uncaught Error: Mismatched anonymous define() module`.

Any ideas?

https://codepen.io/jbrundage/pen/ebMNQx?editors=1000

**Comment by GordonSmith** [comment]
Any widget which dynamically loads a new widget based on a user selection needs a global "require" to do so. 
We have put all those widgets into "composite", all the other packages shouldn't need it.

**Comment by GordonSmith** [comment]
A working example would be:  https://codepen.io/LeSchmoo/pen/JwLGWp?editors=1000

**Comment by jbrundage** [comment]
Removed `html` package from the list per a phone conversation

**Comment by jbrundage** [comment]
@GordonSmith 
- composite
- form
- loader
- marshaller
- util
...these are the only remaining. Each one is somewhat unorthodox compared to the other packages. I don't think our standard README.md format would work for these five. Thoughts?
