### ISSUE TITLE
Adding add custom hooks for Surface widget

### ISSUE THREAD

**Issue by dineshshetye** [hpcc-systems/Visualization#296]
Can we add custom hooks that can be initialized in an application? The visual element can be annotation/button.

Please see an example concept below. This will enable the container application to hook in custom functionality that is not generic but something that makes sense from an application perspective. So if this widget was shown in dashboard creator that form that would be shown would be different from what would be shown when the same widget is displayed in Accurint. 
 
This will be helpful for adding custom forms that are ready to be used to the widget.

![image](https://cloud.githubusercontent.com/assets/1731313/7204597/a6acaf68-e4f1-11e4-9fff-bfd598e3e540.png)

**Comment by GordonSmith** [comment]
@dinesh - Will this button be popping open your form?

**Comment by dineshshetye** [comment]
Yes. The idea is to integrate already existing 3rd party forms (in case of DSP, ZK driven forms) and the user can modify the parameters in the form, submit and it will refresh the underlying widget.

**Comment by mlzummo** [comment]
can HTML surface work diff and the SVG surface in this regard?

**Comment by GordonSmith** [comment]
It will be different internally - but externally it will look the same to the user.
