### ISSUE TITLE
WordCloud hides words that don't fit in the container (it should scale everything to fit)

### ISSUE THREAD

**Issue by jbrundage** [hpcc-systems/Visualization#2960]
For example, "Social Security" is missing in this sample screen shot:
![image](https://user-images.githubusercontent.com/1891935/47577561-36b25e80-d915-11e8-9d1f-30cf4d10ba93.png)

**Comment by GordonSmith** [comment]
I believe this is a known issue with d3-cloud:  https://github.com/jasondavies/d3-cloud/issues/36
