### ISSUE TITLE
Column chart column width

### ISSUE THREAD

**Issue by lucashby** [hpcc-systems/Visualization#2968]
In our use case, we have a column chart that is set for a consistent size with the other charts on our page, but due to the nature of the data, there aren't many columns across the x-axis, and thus the width of the columns is too much and looks inconsistent with our multi-series data.  Could there be a way to manipulate the width of the columns on the chart?

**Comment by GordonSmith** [comment]
@lucashby the onus may end up on you to "pad" the data to ensure all the columns and rows always exist (even if they don't contain data for all the intersections).

We would then need to ensure that we handle the "undefined" intersections correctly?

**Comment by lucashby** [comment]
> @lucashby the onus may end up on you to "pad" the data to ensure all the columns and rows always exist (even if they don't contain values for all the intersections).
> 
> We would then need to ensure that we handle the "undefined" intersections correctly?

All the data exists.  The problem is because we set the chart width/height to match the others on the screen for consistency and the amount of entries will always be small, that's what causes us to run into the issue.  I'm not sure how we can pad the data just to make more x-axis entries when there will only ever be 2 which is why i was hoping we could just manipulate the column widths manually.  Could we perhaps just use some css to do it?

**Comment by vivekvasudevula** [comment]
Yeah, the fix is good and this issue is good to close.
