### ISSUE TITLE
Legend Totals are wrong

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#2991]
![image](https://user-images.githubusercontent.com/966863/48298160-1905fd00-e4b0-11e8-8a61-8122b97eb78a.png)

**Comment by lucashby** [comment]
I believe what I just discovered is related to this as well (these numbers look wacky):

![image](https://user-images.githubusercontent.com/938632/49034280-78862d00-f17f-11e8-8db6-efac052195c4.png)

**Comment by jbrundage** [comment]
That's odd, I'll look into it now

**Comment by jbrundage** [comment]
Ah, looks like that logic will need to behave differently for 2d charts. I'll look into it today.
