### ISSUE TITLE
Pie Chart Visualization Issue 

### ISSUE THREAD

**Issue by vivekvasudevula** [hpcc-systems/Visualization#2994]
In our case, we have few pie charts where they are not loading when the legend text size is long. Could there be a way to manipulate the text size of the  legend.
![causation](https://user-images.githubusercontent.com/44681169/48488884-c601b200-e7ef-11e8-9ba9-d0b7369c5db3.PNG)``

**Comment by lucashby** [comment]
It seems like the quantity of text may be too much, which is pushing over the legend too far.  Should there be some sort of threshold for how far the legend can push over so it doesn't cause the pie chart itself not to render?

**Comment by vivekvasudevula** [comment]
It would be a great help if someone can please take a look or give direction on this issue.

**Comment by GordonSmith** [comment]
@jbrundage Can you get a sample of this data and run it through your new layout pull request - we may need to add a "Min" radius option for the pie and let the text clip naturally (with tooltips)?

**Comment by jbrundage** [comment]
Sure, the new layout logic does add a min radius option (defaults to min radius of 20), but the text clip with tooltips will need to be added. I'll reach out to @vivekvasudevula for some sample data

**Comment by jbrundage** [comment]
@vivekvasudevula This is resolved pending the merge of #3014

**Comment by lucashby** [comment]
We are still struggling with some issues with Pie Charts as of these library versions:

"@hpcc-js/chart": "^2.6.0",
"@hpcc-js/layout": "^2.6.1",
"@hpcc-js/phosphor": "^2.4.1"

![pie1](https://user-images.githubusercontent.com/938632/50842303-6679db80-1334-11e9-93f3-3d27875911ae.PNG)
![pie2](https://user-images.githubusercontent.com/938632/50842304-6679db80-1334-11e9-8005-dd5cce807177.PNG)
![pie3](https://user-images.githubusercontent.com/938632/50842306-6679db80-1334-11e9-8654-3b2925f09373.PNG)

Is this an issue with the library (or versions we are using)?  Any suggestions would be greatly appreciated.

**Comment by jbrundage** [comment]
Hey @lucashby, we've got some major improvements to the Pie (#3054) going into the next build (today).
