### ISSUE TITLE
Roxie query ID "onchange" issue

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#3065]
"I figured it out—if I copy and paste the query ID into the box and then tab off, the result dropdown isn’t populated. But if I go back, remove the .1 and then re-add it, the output result dropdown is populated. Looks like some sort of onchange/onblur type problem." - @drealeed

**Comment by drealeed** [comment]
I go to the datasources tab, add a roxie service, click on it, go to the right hand page, and copy and paste the following values into the text boxes:

URL: http://10.173.147.1:8002
Queryset: roxie
QueryID: beijingiac_claim_group_list_srvc.1

When I tab off of queryid, no results are populated in the dropdown.

Then I remove the .1, tab off, and the results dropdown populates.

If I then change queryid to be a non-existent query, the results dropdown doesn't refresh/clear out.
