### ISSUE TITLE
IconList gallery sample throws "Target can only be assigned once"

### ISSUE THREAD

**Issue by jbrundage** [hpcc-systems/Visualization#3066]

**Comment by jbrundage** [comment]
@GordonSmith this update logic is causing the widgets to be recreated on each call: https://github.com/hpcc-systems/Visualization/blob/master/packages/other/src/IconList.ts#L34-L49

Is there an example where we're creating (and updating) an instance of a widget for each data row? In the `PropertyEditor2` PR I've cached instances of each created widget in an object belonging to that instance of the `PropertyEditor2`, a similar concept would resolve this issue, but is there a case where you've handled a similar situation so I could take a look?

**Comment by GordonSmith** [comment]
Yea that code looks unusual...  Here is an example:  https://github.com/hpcc-systems/Visualization/blob/master/packages/layout/src/FlexGrid.ts#L23-L61

Note:  Line 61 looks wrong - it should have an "each" and call `.target(null)` for each widget.
