### ISSUE TITLE
adding another groupby field overwrites the first aggregate column

### ISSUE THREAD

**Issue by drealeed** [hpcc-systems/Visualization#3068]
If you load the attached json ddl into dashy, go to the groupby tab and add the groupby field "productdescription", the content of productdescription overwrites the content in the numrecs column rather than inserting a new groupby column in front of it.
[ddltest.json.txt](https://github.com/hpcc-systems/Visualization/files/2733244/ddltest.json.txt)

**Comment by drealeed** [comment]
Also, deleting a groupby field doesn't delete that column name, just moves all the data over to the left one column.

**Comment by GordonSmith** [comment]
@drealeed - the attached DDL's roxie needs to be re-submitted.
