### ISSUE TITLE
UI Enhancement: Streamline form creation

### ISSUE THREAD

**Issue by drealeed** [hpcc-systems/Visualization#3069]
Currently, to add a form to a dashboard, you have to:
* go to datasource, 
* manually fill out form json with default values. If you tab off the textbox while invalid json is in there, all quotes are automatically escaped, causing issues.
* go to the dashboard
* add a widget, 
* go to the viz tab in properties, 
* change the type to a fieldform

Can this be streamlined? from and end user's perspective, having a form datasource and form widget is non-intuitive

**Comment by jbrundage** [comment]
@drealeed It sounds like we just need a "+ Field Form Widget" button in the datasources section. Could you paste an example/snippet of the `manual form json with default values` that you're referring to?

**Comment by drealeed** [comment]
![formdatasource](https://user-images.githubusercontent.com/4984355/50987037-73cecb80-14d6-11e9-8b1d-07ae9b0f937f.jpg)
Here's a screenshot of the form datasource and its payload
