### ISSUE TITLE
Non AMD Word Cloud Support

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#307]
Non AMD word cloud needs a "shim" so it can be resolved at runtime.

**Comment by GordonSmith** [comment]
@buunguyen (I am not able to assign this to you - will try and find out why)...

**Comment by buunguyen** [comment]
I've just commented on the related thread, what I've learned from building the non-AMD demo is that we don't have to tweak the require shim at all because lib code doesn't consume the output of `require`. But I'll fix it anyway to be future-proof.

**Comment by buunguyen** [comment]
Done, submitted PR to your repo.

**Comment by GordonSmith** [comment]
@buunguyen Going forward (now that we have an official base in upstream) we try and issue pull requests along the lines of:  https://github.com/hpcc-systems/Visualization/pull/309

So what I did there was created a new branch based on upstream/candidate-1.0.0
Cherry picked you fix for the Word Cloud resolving.
Ammended the commit to add a "proper" message - guidelines:  https://github.com/hpcc-systems/HPCC-Platform/wiki/Git-commit-message-guidelines
Push to my repo and then issue PR.
