### ISSUE TITLE
"fetchme" showing in hipie roxie service-based dashboards

### ISSUE THREAD

**Issue by drealeed** [hpcc-systems/Visualization#3071]
The following ddl is showing a ‘fetchme’ column, even though that column isn’t defined in the ddl.
 
this is in a straight-up viz container, not dashy:

dashboard = new Dashboard(this.container).hideSingleTabs(true);

 
{
                "version": "0.0.22",
                "datasources": [{
                                "type": "hipie",
                                "querySet": "roxie",
                                "queryID": "leeddx_risk_testroxie.Ins002_Service_1",
                                "inputs": [],
                                "outputs": {
                                                "View_e_14": {
                                                                "fields": [{
                                                                                "id": "state",
                                                                                "type": "string",
                                                                                "default": [],
                                                                                "children": []
                                                                }, {
                                                                                "id": "population",
                                                                                "type": "number",
                                                                                "default": [],
                                                                                "children": []
                                                                }]
                                                }
                                },
                                "id": "Ins002_dsOutput1",
                                "url": "http://10.173.147.1:8002/"
                }],
                "dataviews": [{
                                "id": "e_14",
                                "datasource": {
                                                "request": [],
                                                "output": "View_e_14",
                                                "id": "Ins002_dsOutput1"
                                },
                                "activities": [],
                                "visualization": {
                                                "title": "Element 14",
                                                "id": "cp_14",
                                                "chartType": "Table",
                                                "__class": "dgrid_Table",
                                                "properties": {
                                                                "widget": {
                                                                                "__class": "dgrid_Table"
                                                                },
                                                                "title": "Element 14"
                                                }
                                }
                }],
                "properties": {
                                "layout": {
                                                "main": {
                                                                "currentIndex": 0,
                                                                "type": "tab-area",
                                                                "widgets": [{
                                                                                "__id": "cp_14"
                                                                }]
                                                }
                                }
                }
}

**Comment by GordonSmith** [comment]
@drealeed - this roxie query needs to be re-created.
