### ISSUE TITLE
Maps Pin Custom Image Support

### ISSUE THREAD

**Issue by lucashby** [hpcc-systems/Visualization#3072]
Would it be possible to implement a feature to allow consumers to use custom pin images on the Google maps control(s)?  Attached an example custom pin image.

![crash](https://user-images.githubusercontent.com/938632/50856884-e36b7c00-1359-11e9-96de-4524c2e49ae0.png)

EDIT:  This should also include the ability to provide custom pin images for clusters.

**Comment by GordonSmith** [comment]
@jbrundage the existing "Icon" widget supports FA Chars and Images and already has a "Pin" shape - can you do up some gallery samples and see if it will fit the bill?  I will investigate what is involved in getting it into the new mapping layers (with clustering support)...

**Comment by GordonSmith** [comment]
@lucashby for the clusters "icon" can you do a rough sketch of what your thinking?  
The cluster might contain many different icon types I would have thought?  Also it needs to show the physical number of items inside the cluster - or maybe its something we can look at after you have the initial version up and running?

**Comment by GordonSmith** [comment]
Would I be correct in saying that your "cluster" is for several entities at a single location?  

I suspect your "cluster" is at odds with the built in clustering capability and may need some details fleshed out (so I understand it properly).  I will issue a PR for the custom image (pin) support and we can discuss (and open new tickets) for:
* Tooltips + Click Bubbles
* Custom cluster rendering

**Comment by lucashby** [comment]
We were going to let the clustering tell us when they cluster ('zoom level') so they don't have to be at the exact same location and let the clustering take place in both the 'zoom level' and single location if possible.
