### ISSUE TITLE
Line Chart w/Chart Panel Colors

### ISSUE THREAD

**Issue by lucashby** [hpcc-systems/Visualization#3078]
When using a line chart in a chart panel, there seems to be a slight discrepancy between the colors in the legend and the colors of the lines.  When styling the lines a little thicker, this becomes more obvious.

**Comment by jbrundage** [comment]
@lucashby What properties are you using on the Line Chart? Have you set the `interpolate` and/or `interpolateFill` properties?

**Comment by lucashby** [comment]
Here is our initialization code:

`vm.numberCrashesByAgeAndSex = new vm.hpcc.Layout.ChartPanel()
	.widget(new vm.hpcc.Chart.Line().paletteID('cc-ageSex').tooltipValueFormat('').xAxisGuideLines(false).yAxisGuideLines(false).pointShape('rectangle'))
	.target('numberCrashesByAgeAndSexDiv')
	.title('Age')
	.titleVisible(false)
	.legendVisible(true)
	.legend_showSeriesTotal(true)
	.legend_showLegendTotal(true);`

**Comment by GordonSmith** [comment]
@lucashby can you do a sanity check that you _do_ have the #2986 fix (which first showed which should have shown up in @hpcc-js/chart v2.4.1 or greater...

**Comment by jbrundage** [comment]
@GordonSmith I've confirmed that he does have the fix and there's a bug that I'm working on now.
