### ISSUE TITLE
Table export as CSV undefined

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#3081]
Certain datasets that show blanks in the table widget export with the value of undefined in the column. 

Possible bug or opportunity to add "treat as blank" option in the dermatology.

**Comment by databaser1** [comment]
When a blank value shows in a table cells, it'll be initialized as empty string or anything defined in missingDataString setting in marshaller_HTML section in Layout Designer (for exemple: *MISSING*); but all those blank values that haven't got chance to be displayed in the table (like in page 2 and above) will be a literal string "undefined" in the downloaded CSV.

**Comment by GordonSmith** [comment]
Can we double check the viz version as it looks like this fix made it into v1.20.0-rc6:  https://github.com/hpcc-systems/Visualization/commit/3ccecabe13673c1069f79a69856ce8dd8f5c267b

**Comment by GordonSmith** [comment]
@jchambers-ln can you email me a link to the offending dash?

**Comment by databaser1** [comment]
Https://dsp-cert.risk.regn.net

Login and find dashboard SASearchV4. Then search for a first name such as John then click on a record in search result, and the specialty summary widget will be populated, whose font needs to be adjusted.

On Jan 18, 2019, at 11:35 AM, Gordon Smith <notifications@github.com<mailto:notifications@github.com>> wrote:


@jchambers-ln<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjchambers-ln&data=02%7C01%7C%7C50ceffebfa0f4c78e77808d67d62f741%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636834261341134152&sdata=SVjLaHnTRpaenliPLX6US9suhFUPbuRmTu5F%2BlY%2BS%2Bo%3D&reserved=0> can you email me a link to the offending dash?

**Comment by jchambers-ln** [comment]
This still needs to be resolved.
