### ISSUE TITLE
IE11 Issue with Choropleth zoom to fit

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#3095]
Choropleth maps don't zoom to fit correctly in IE11:

![image](https://user-images.githubusercontent.com/966863/51485404-e15fdf00-1d95-11e9-8ad4-ecb745ddaed0.png)

**Comment by GordonSmith** [comment]
The same is true for all choropleths not just the IE one shown above:  https://bl.ocks.org/GordonSmith/raw/c4816bcfeb03f2f4e9f10b256bfd2e2d/

**Comment by jbrundage** [comment]
@GordonSmith This is still a legitimate issue. And it's related to a difference in how IE11 calculates SVG bounding boxes differently.

In the blocks example IE11 calculates the bounding box based on Northern Ireland:
![image](https://user-images.githubusercontent.com/1891935/58484991-2b384780-8131-11e9-8d76-541a13115c02.png)

And the other browsers calculate the bounding box of the outer `g` element correctly:
![image](https://user-images.githubusercontent.com/1891935/58485273-b580ab80-8131-11e9-9756-c2e4778ded8b.png)

One potential solution would be to get all the appropriate bounding boxes for the child elements and then calculate their collective bounding box. We could potentially do this as a polyfill for IE11 that's conditionally included at the application layer. Thoughts?
