### ISSUE TITLE
ddl1-to-ddl2: handling multiple dashboards

### ISSUE THREAD

**Issue by drealeed** [hpcc-systems/Visualization#3111]
With DDL1s, you can have multiple top-level dashboards. with DDL2, you don't (the appearance of multiple dashboards is handled in properties).

If a ddl1 with multiple dashboards is upgraded, each dashboard shows up twice in the ddl2.

Attached is an example of a ddl1 with multiple dashboards. the "States" widget is listed twice in the dataviews section of the ddl2.

[multipleviz-ddl1.json.txt](https://github.com/hpcc-systems/Visualization/files/2817412/multipleviz-ddl1.json.txt)
[multipleviz-ddl2.json.txt](https://github.com/hpcc-systems/Visualization/files/2817413/multipleviz-ddl2.json.txt)

**Comment by GordonSmith** [comment]
Is it enough to host the multiple dashboards inside a top level tab(s) - one for each dashboard?
