### ISSUE TITLE
FieldForm + Form Validate()

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#3121]
When a forms validate method is called and returns false, it should highlight the field which failed validation. 

Also it is should display an error msg

![image](https://user-images.githubusercontent.com/966863/52532324-df48ca80-2d1a-11e9-95b6-05466a2510bd.png)

**Comment by jbrundage** [comment]
Alright, should the input border change to red and the background color to a mostly transparent red?

Also, what do you mean when you say it should display an error message? In the console or more of a popup?

**Comment by GordonSmith** [comment]
Border red / content red - which ever looks better / appropriate.

For the message either a tooltip over the input field or a string embedded as per the pic above - I suspect it becomes less important once the error highlighting is in place.

**Comment by jbrundage** [comment]
This one is still relevant. Unless we're planning on refactoring the whole form concept.

**Comment by GordonSmith** [comment]
@jbrundage bump
