### ISSUE TITLE
Google Chart Background

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#313]
Should default to transparent - see test.html.

**Comment by mlzummo** [comment]
I will make the change, however i don't know what i should be looking for in test.html (atleast i cant see it)

**Comment by GordonSmith** [comment]
The google charts have a white backgraound while the other charts have a greyish background - as dictated by the hosting page.

**Comment by GordonSmith** [comment]
http://rawgit.com/GordonSmith/Visualization/ENABLE_RAWGIT/demos/test.html
