### ISSUE TITLE
Graph/Edge->points() type definition invalid

### ISSUE THREAD

**Issue by MattMckeller** [hpcc-systems/Visualization#3139]
I believe the overloads for the points method of "Graph/Edge.ts" file is missing transitionDuration and skipPushMarkers

**Comment by AlexSmith** [comment]
I am looking at this:  
https://github.com/hpcc-systems/Visualization/blob/master/packages/graph/src/Edge.ts#L68-L77 
They appear to be there?

Note: The `points` array is only used in hierarchy mode (its to route the edges around other nodes).

**Comment by GordonSmith** [comment]
I am looking at this:
https://github.com/hpcc-systems/Visualization/blob/master/packages/graph/src/Edge.ts#L68-L77
They appear to be there?

Note: The `points` array is only used in hierarchy mode (its to route the edges around other nodes).

**Comment by MattMckeller** [comment]
Yeah that's the spot! 

It's being called from https://github.com/hpcc-systems/Visualization/blob/master/packages/graph/src/Graph.ts#L703 which is what I am mimicking after updating node positions once the layout is finished because the edges were being disconnected when I did not call it. Is this not what I should be calling?

**Comment by GordonSmith** [comment]
I don't believe you should be setting points at all - if its `undefined` the edge will take the source/target vertex pos as its positioning.
The only time its used, is with Hierarchy layout, where the layout specifically sets several points to "route" the edge around the nodes.

**Comment by GordonSmith** [comment]
@MattMckeller is this ok to close?

**Comment by MattMckeller** [comment]
I don't see the type definitions as updated?
