### ISSUE TITLE
Issue with chart bar percentage display

### ISSUE THREAD

**Issue by vivekvasudevula** [hpcc-systems/Visualization#3140]
The percentage in the chart bar is not displaying correctly for low values, Can you please help us to fix this issue.

![chart bar](https://user-images.githubusercontent.com/44681169/53215090-1bcecd00-361d-11e9-8bd9-03df5dcd4f81.PNG)

Sample Code to reproduce the issue:

import { Bar } from "@hpcc-js/chart";

new Bar()
.target("target")
.columns(["Subject", "Year 1", "Year 2", "Year 3"])
.data([
["Unknown", 2],
["Unconscious", 11],
["Shock", 5],
["Semiconscious", 7],
["Conscious", 251],
["Semiconscious", 13],
["Does Not Apply", 20],
["Turning Improperly", 34],
])
.yAxisType("linear")
.xAxisType("ordinal")
.showValue(true)
.showValueAsPercent("series")
.showValueAsPercentFormat(".2%")
.valueCentered(true)
.render()
;

@

**Comment by jbrundage** [comment]
I'll have a solution to this in the next build
