### ISSUE TITLE
Chart Panel legend size

### ISSUE THREAD

**Issue by lucashby** [hpcc-systems/Visualization#3154]
We have an issue where we have some rather long legend entries that can cause the pie charts to get uncomfortably small.  The Visualization library tends to shrink the chart area down so it can grow the legend area, but this is not really ideal as can be seen in the example below.  Would it be possible to address this somehow.  I've imagined several possible solutions, but I'm not familiar enough with the inner workings of the library to assume one solution is better than another.  One thing we tried on our side was to use CSS to have the legend entries wrap, but because they are drawn via SVG, that would have to be done at the time they are added to the screen.  One possibility might be to set a hard limit on just how wide the legend can grow (relative % perhaps to the whole container), or perhaps expose a setting that allows consuming clients to set a hard max width, but that would mean longer entries would need to wrap on things like whitespace or overflow.  Can you guys take a look and perhaps we could even have a voice conversation about it if that makes more sense.  Just let me know what you think.  Contrived example below:

```
import { ChartPanel } from "@hpcc-js/layout";
import { Pie } from "@hpcc-js/chart";

new ChartPanel().widget(new Pie().showSeriesPercentage(true))
    .target("target")
    .columns(["Subject", "Result"])
    .data([
        ["English", 45],
        ["Irish", 28],
        ["Math", 98],
        ["Geography with a super long title that messes things up", 48],
        ["Science but they get worse when there are several that don't line break or anything", 82]
    ])
    .legendVisible(true)
    .legendButtonVisible(true)
    .legend_showSeriesTotal(true)
    .legend_showLegendTotal(true)
    .titleVisible(false)
    .render()
    ;
```

![image](https://user-images.githubusercontent.com/938632/53509802-9454e400-3a8a-11e9-9b98-23469adfda2b.png)

**Comment by GordonSmith** [comment]
My initial suggestion would be to clip the legend text with a "..." but ensure the full text was available via tooltip?

**Comment by lucashby** [comment]
Well, we need one side to have the real value (either the legend or the tics on the pie chart) and I believe the hope would be at least the legend would have the real value, but if you think it would work better to clip the legend and have the tics have the full value, I think that could work, but that does mean changing some functionality that was already done to clip the tic labels now.
