### ISSUE TITLE
Request to display Count for Pie chart.

### ISSUE THREAD

**Issue by srivivekr** [hpcc-systems/Visualization#3156]
We have a requirement to display the count for the pie chart, is there a way to add an option similar to bar chart that is available [.showValue(true)]. 
![pie chart](https://user-images.githubusercontent.com/44681169/53579671-fd4e6180-3b47-11e9-823e-e0ba93428bba.PNG)

**Comment by GordonSmith** [comment]
Currently no - but should be fairly straight forward to add.
What is available today is "showSeriesPercentage":  https://raw.githack.com/hpcc-systems/Visualization/master/demos/gallery/playground.html?./samples/chart/Pie/HalfDonut.js 

And if your using a Chart Panel and legend you can get totals via the legend:  https://raw.githack.com/hpcc-systems/Visualization/master/demos/gallery/playground.html?./samples/legend/Values.js

Putting those two together you can end up with:
![image](https://user-images.githubusercontent.com/966863/53580753-356b9980-3b74-11e9-9ee0-99e3b26084f1.png)
From:
```
import { Pie } from "@hpcc-js/chart";
import { ChartPanel } from "@hpcc-js/layout";

new ChartPanel()
    .widget(new Pie().showSeriesPercentage(true))
    .target("target")
    .columns(["Subject", "Year 1", "Year 2", "Year 3"])
    .data([
        ["Geography", 75, 68, 65],
        ["English", 45, 55, -52],
        ["Math", 98, 92, 90],
        ["Science", 66, 60, 72]
    ])
    .title("Exam Results 2008->10")
    .legendVisible(true)
    .legend_showSeriesTotal(true)
    .legend_showLegendTotal(true)
    .titleVisible(false)
    .render()
    ;

```
