### ISSUE TITLE
Pie Chart is not displaying completely when ever a legend is diselected. 

### ISSUE THREAD

**Issue by srivivekr** [hpcc-systems/Visualization#3175]
This is regular pie chart, whenever the legend is diselected the pie chart is not getting displayed as expected.

![cited](https://user-images.githubusercontent.com/44681169/54154241-d3365280-4417-11e9-835b-e529d2e2cfc5.PNG)
![Cited1](https://user-images.githubusercontent.com/44681169/54154243-d5001600-4417-11e9-93d6-8525a3e1ae22.PNG)
![Cited2](https://user-images.githubusercontent.com/44681169/54154245-d6314300-4417-11e9-875c-9b2e29acae28.PNG)

**Comment by jbrundage** [comment]
FYI I'm currently looking into this. I assume this is simply a ChartPanel with a Pie `widget`? What are the parameters used to recreate this? Is it possible to recreate in the gallery/playground?

**Comment by jbrundage** [comment]
![image](https://user-images.githubusercontent.com/1891935/54210266-8ef98f80-44b5-11e9-9d0d-c05918e2c4e9.png)

**Comment by GordonSmith** [comment]
![image](https://user-images.githubusercontent.com/966863/54210737-f4f70e80-44d7-11e9-9b4c-08e9a6603ff7.png)
