### ISSUE TITLE
PDF Functionality

### ISSUE THREAD

**Issue by srivivekr** [hpcc-systems/Visualization#3186]
Hello, Is there a possibility for you guys to add the PDF Functionality into the HPCC Library just like the way you included the Excel Functionality. For the Command center project, we have the requirement to add a PDF feature where the user can be able to download the PDF Image.
![PDF](https://user-images.githubusercontent.com/44681169/54535665-6403b580-4965-11e9-8962-b30f29cc33f8.PNG)

**Comment by GordonSmith** [comment]
@srivivekr quick answer is no - specifically I don't believe it is possible to create a PDF file 100% within browser hosted JavaScript.

Some additional comments:
* We don't support "excel" functionality either, what we do is create a CSV file for download which Excel happens to be able to open.
* We could investigate a download "img/png" option, but from previous experience its never quite 100% (but it may be good enough for a quick win?) - bonus marks:  Add support for copying to clipboard as well?
* To get a 100% correct PDF of a given viz (or whole page) you would need implement it server side:
  * Technically its actually very easy (we essentially do 99% of it as part of our unit tests)
  * Customers typically don't actually want just a PDF of a single chart - so (from experience) you end up creating another web page (letter/A4 size) specifically for the PDF download and use it to render on the server.
  * The hard part is then ensuring that the server "view" matches the client "view" (assuming there is some interactivity on the client side)...

**Comment by srivivekr** [comment]
Thanks, Gordan for your prompt reply.
Can you guys please investigate the possibility of adding the download option of img/png, so we will play around to throw that in a PDF client side.
