### ISSUE TITLE
Property to allow specific total to base %'s off

### ISSUE THREAD

**Issue by lucashby** [hpcc-systems/Visualization#3189]
I have a strange question for you guys. Let's say I have a column chart of "Top 10" of something. You added the feature that allows us to show % values on the bars, and that is awesome. However, what if I need to show the % based not just on the bars in the chart, but some other total? Is there a way to do that, or would it be possible to implement some feature that would allow setting of a total to base %'s off? I can put in a GitHub issue, but wanted to ask questions first.

Jaman Brundage @jbrundage Mar 14 13:08
Sure, I'll add a new property to allow you to specify the total to base %'s off.
We also just recently added a new widget called the "BreakdownTable" that might be useful for this? It depends on your data shape
 
@lucashby but please do create a Github issue for it

**Comment by GordonSmith** [comment]
@jbrundage - I would suggest breaking this request into two (or more PRs):
 - [ ] Add a method at the "widget" level called "dataMeta" - which should accept:
* Min
* Max
* Mean
* Std Deviation 
(essentially all the bits you need to display a candlestick).
 - [ ] Update "values" to use this information (if it exists)
 - [ ] Update "%'s" to use this information (if it exists)
 - [ ] Add option to show horizontal lines to all XYAxis charts for min / max / mean
 - [ ] Add option to display a candlestick as part of the Y Axis when the meta information is available
