### ISSUE TITLE
Expose xAxisTitle similarly to yAxisTitle

### ISSUE THREAD

**Issue by lucashby** [hpcc-systems/Visualization#3191]
Would it be possible to expose the xAxisTitle so a consumer can override as needed similarly to how the yAxisTitle is exposed via a property of the chart?  In some cases, we may want a different value than the first value of our 'columns' in our data, or we may wish to not display it even though we have a value in the 'columns' in our data.

**Comment by jbrundage** [comment]
@lucashby sure no problem. I should have this ready for you in the next build.
