### ISSUE TITLE
Allow pre-sort with dgrid Table

### ISSUE THREAD

**Issue by lucashby** [hpcc-systems/Visualization#3192]
Could we have the functionality to be able to throw data into a table and tell the table to sort (via code) on a column?  It should appear as if the user had clicked on it to sort.  Basically a pre-sort using the table's mechanics and so we get the little arrow after the sort is set and the table is rendered.

**Comment by srivivekr** [comment]
Is there any update on this issue, please let us know @GordonSmith

**Comment by GordonSmith** [comment]
Whoops fell of my radar.
