### ISSUE TITLE
Script error while loading HIPIE DDL

### ISSUE THREAD

**Issue by dhanasiddharth** [hpcc-systems/Visualization#320]
Creating Graphmarshaller throws the following error with the latest build of Visualisation
![image](https://cloud.githubusercontent.com/assets/3434839/7368500/01d95224-edc6-11e4-9317-149d1676b6c0.png)
With older codebases, Visualisation renders without errors

**Comment by GordonSmith** [comment]
I will need a bit more information to be useful - which branch are you working from?

**Comment by dhanasiddharth** [comment]
I was working on latest master branch from https://github.com/hpcc-systems/Visualization
