### ISSUE TITLE
Dashboard doesn't load using @hpcc-js/marshaller": "^2.10.0

### ISSUE THREAD

**Issue by woodbr01** [hpcc-systems/Visualization#3200]
Downgrading to 2.9.3 works but trying to load dashboard on 2.10.0 throws the error shown below. This isn't a dashy dashboard.

Code called to render the dashboard

```
let component = this;
    this.dashboard.restore(ddl).titleVisible(false).hideSingleTabs(true);
    this.dashboard.target(id).render(function (d) {
      setTimeout(() => {
        console.log("Loading", ddl);
        component.container.refresh();
      }, 250);
    });
```

DDL:

```
{"version":"0.0.22","datasources":[{"type":"databomb","format":"json","payload":"[{\"Field4\":\"Retail\",\"Field5\":\"January\",\"Field2\":\"CB-0010\",\"Field3\":\"City bike (CB)\",\"Field6\":\"6\",\"Field7\":\"7991.48\",\"Field1\":\"Australia\"},{\"Field4\":\"Retail\",\"Field5\":\"April\",\"Field2\":\"KB-0012\",\"Field3\":\"Kids bike (KB)\",\"Field6\":\"40\",\"Field7\":\"12804.66\",\"Field1\":\"Singapore\"},{\"Field4\":\"Wholesale\",\"Field5\":\"June\",\"Field2\":\"TB-0011\",\"Field3\":\"Trekking bike (TB)\",\"Field6\":\"90\",\"Field7\":\"113087.02\",\"Field1\":\"India\"},{\"Field4\":\"Retail\",\"Field5\":\"February\",\"Field2\":\"CB-0010\",\"Field3\":\"City bike (CB)\",\"Field6\":\"14\",\"Field7\":\"10373.16\",\"Field1\":\"Germany\"}]","id":"datasource1","fields":[{"id":"Field1","type":"string","default":[],"children":[]},{"id":"Field2","type":"string","default":[],"children":[]},{"id":"Field3","type":"string","default":[],"children":[]},{"id":"Field4","type":"string","default":[],"children":[]},{"id":"Field5","type":"string","default":[],"children":[]},{"id":"Field6","type":"string","default":[],"children":[]},{"id":"Field7","type":"string","default":[],"children":[]}]}],"dataviews":[{"id":"dataview1","datasource":{"id":"datasource1"},"activities":[],"visualization":{"title":"salesdata_fixed","id":"viz1","chartType":"Table"}}]}
```

Error:

TypeError: Cannot read property 'id' of undefined
PDockPanel../node_modules/@hpcc-js/phosphor/dist/index.es6.js.PDockPanel.appendContent
node_modules/@hpcc-js/phosphor/dist/index.es6.js:23726
  23723 | });
  23724 | PDockPanel.prototype.appendContent = function (wa) {
  23725 |     this._content.push(wa);
> 23726 |     this._contentMap[wa.widget.id()] = wa;
  23727 | };
  23728 | PDockPanel.prototype.removeContent = function (wa) {
  23729 |     var idx = this._content.indexOf(wa);
View compiled
DashboardDockPanel../node_modules/@hpcc-js/phosphor/dist/index.es6.js.DockPanel.addWidget
node_modules/@hpcc-js/phosphor/dist/index.es6.js:23830
  23827 |     wa.title.label = title;
  23828 |     wa.padding = 8;
  23829 |     this._dock.addWidget(wa, addMode);
> 23830 |     this._dock.appendContent(wa);
  23831 |     this._dock.tabsMovable = true;
  23832 |     return this;
  23833 | };
View compiled
DashboardDockPanel../node_modules/@hpcc-js/marshaller/dist/index.es6.js.DashboardDockPanel.syncWidgets
node_modules/@hpcc-js/marshaller/dist/index.es6.js:8647
  8644 | for (var _d = 0, _e = diffWidgets.added; _d < _e.length; _d++) {
  8645 |     var w = _e[_d];
  8646 |     var element = this._ec.element(w);
> 8647 |     this.addWidget(w, this.tabTitle(element), "split-bottom", undefined, this.hideSingleTabs() ? undefined : this);
  8648 |     refit = this.syncMinSize(w) || refit; // ensure syncMinSize is called
  8649 | }
  8650 | for (var _f = 0, _g = diffPopups.added; _f < _g.length; _f++) {
View compiled
Dashboard../node_modules/@hpcc-js/marshaller/dist/index.es6.js.Dashboard.update
node_modules/@hpcc-js/marshaller/dist/index.es6.js:8893
  8890 |     return this;
  8891 | };
  8892 | Dashboard.prototype.update = function (domNode, element) {
> 8893 |     this._dockPanel.syncWidgets();
  8894 |     _super.prototype.update.call(this, domNode, element);
  8895 | };
  8896 | Dashboard.prototype.vizActivation = function (viz) {
View compiled
HTMLDivElement.<anonymous>
node_modules/@hpcc-js/layout/node_modules/@hpcc-js/common/dist/index.es6.js:8189
  8186 |         element.classed(key, classed[key]);
  8187 |     }
  8188 |     context2.preUpdate(this, context2._element);
> 8189 |     context2.update(this, context2._element);
  8190 |     context2.postUpdate(this, context2._element);
  8191 | });
  8192 | elements.exit()
View compiled
Selection.selection_each [as each]
node_modules/@hpcc-js/layout/node_modules/@hpcc-js/common/dist/index.es6.js:415
  412 | 
  413 | for (var groups = this._groups, j = 0, m = groups.length; j < m; ++j) {
  414 |   for (var group = groups[j], i = 0, n = group.length, node; i < n; ++i) {
> 415 |     if (node = group[i]) callback.call(node, node.__data__, i, group);
  416 |   }
  417 | }
  418 | 
View compiled
Dashboard../node_modules/@hpcc-js/layout/node_modules/@hpcc-js/common/dist/index.es6.js.Widget.render
node_modules/@hpcc-js/layout/node_modules/@hpcc-js/common/dist/index.es6.js:8182
  8179 |     }
  8180 | })
  8181 |     .merge(elements)
> 8182 |     .each(function (context2) {
  8183 |     var element = select(this);
  8184 |     var classed = context2.classed();
  8185 |     for (var key in classed) {
View compiled
Dashboard../node_modules/@hpcc-js/layout/dist/index.es6.js.Border2.render
node_modules/@hpcc-js/layout/dist/index.es6.js:1114
  1111 | };
  1112 | Border2.prototype.render = function (callback) {
  1113 |     var _this = this;
> 1114 |     var retVal = _super.prototype.render.call(this, function (w) {
  1115 |         if (_this._topWA) {
  1116 |             _this._topWA
  1117 |                 .widget(_this.top())
View compiled
Visualization2X.initializeDashboard
src/visualization/Visualization2X.js:90
  87 | initializeDashboard(id, ddl) {
  88 |   let component = this;
  89 |   this.dashboard.restore(ddl).titleVisible(false).hideSingleTabs(true);
> 90 |   this.dashboard.target(id).render(function (d) {
  91 |     setTimeout(() => {
  92 |       console.log("Loading", ddl);
  93 |       component.container.refresh();
View compiled
Visualization2X.componentDidMount
src/visualization/Visualization2X.js:76
  73 | }
  74 | 
  75 | componentDidMount() {
> 76 |   this.initializeDashboard(this.state.id, this.props.ddl);
  77 |   window.addEventListener("resize", this.updateDimensions);
  78 | }
  79 | 
View compiled
▶ 14 stack frames were collapsed.
(anonymous function)
src/tools/MiniApp.js:315
  312 | 
  313 | this._server.change(changed, input.name,
  314 |   (responseObj) => {
> 315 |     this.setState({
  316 |       mastate: responseObj.state,
  317 |     }, this.onStateChangeFn());
  318 |   });
View compiled
(anonymous function)
src/server/MiniAppServer2.js:67
  64 |         this.handleError(err, response, error);
  65 |       } else {
  66 |         const responseObj = JSON.parse(response.text);
> 67 |         success(responseObj);
  68 |       }
  69 |     });
  70 | }
View compiled
▶ 4 stack frames were collapsed.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.

**Comment by GordonSmith** [comment]
@woodbr01 - I believe this was resolved?

**Comment by woodbr01** [comment]
Yes
