### ISSUE TITLE
Table.getColumnAlignment is Broken in 1.20.3-rc2

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#3209]

**Comment by jchambers-ln** [comment]
I'm seeing tinny tables like less than 1/2 inch square this may be related. If not I'll open a ticket when I get back to my computer

**Comment by jbrundage** [comment]
I left an undefined variable in a method that my test case wasn't using.
Fortunately TypeScript catches this type on error in v2.x.x+ every time you
save a file.

The fix is here:  https://github.com/hpcc-systems/Visualization/pull/3210
