### ISSUE TITLE
pointShape in line chart is not responding.

### ISSUE THREAD

**Issue by srivivekr** [hpcc-systems/Visualization#3225]
![lineChart](https://user-images.githubusercontent.com/44681169/55637297-b54bdb80-5792-11e9-87ff-a4d2f28884c9.PNG)

**Comment by GordonSmith** [comment]
Also looks like all scatter charts are borked (which is the same issue no doubt):
![image](https://user-images.githubusercontent.com/966863/55637702-9878cd80-57bd-11e9-9cc5-5c0919027d36.png)
