### ISSUE TITLE
Add option to display modalIfData as a Grid child while designMode === true

### ISSUE THREAD

**Issue by jbrundage** [hpcc-systems/Visualization#3243]

**Comment by GordonSmith** [comment]
@jbrundage I suspect the issue is also equally applicable to the "flyout" case (as per the email chain)?

**Comment by jbrundage** [comment]
@GordonSmith they call the "modalIfData" a "flyout" for some reason, but the "flyout" only refers to the filter forms. So I'd say this isn't really applicable to the flyout.
