### ISSUE TITLE
Add option to set gmaps api key after viz has been loaded.

### ISSUE THREAD

**Issue by woodbr01** [hpcc-systems/Visualization#3258]
Currently if you don't set the google maps api key before viz loads then it gets set to the default key in viz and there is no way to set it. There should be a more flexible way of setting the api key that may include trying to get it from window.__hpcc_gmap_apikey each time we need to make a call to gmaps.

**Comment by woodbr01** [comment]
This is the way it's currently set.

https://github.com/hpcc-systems/Visualization/blob/6db772046744cff8ec8c43b1514ddbafe15dcb8d/packages/map/src/GMap.ts#L15

**Comment by GordonSmith** [comment]
The issue is that key is only initialized once - which is the first time the client makes a request to to the GMap API Server - each time you see it in network traffic is when google is passing it back to the server from its own client code...

**Comment by woodbr01** [comment]
Can we wait to set the key after the page loads?

**Comment by GordonSmith** [comment]
Ahhh - yes I see your point - your right that initialization can be delayed until last minute (currently its getting set when @hpcc-js/map is loaded, when it should only be set the first time GMap gets instantiated...)
