### ISSUE TITLE
"first" filter being performed on a dependent widget, not updated after widget refreshed from a driving widget

### ISSUE THREAD

**Issue by drealeed** [hpcc-systems/Visualization#326]
If you have, say, a pie chart that drives a table widget, and if the table widget has "first":"10" defined in its ddl, the top ten records are initially shown OK. But if the pie chart is clicked to update a table, only records matching the filter that were in the original top 10 shown are included.

Example here:
http://viz.hpccsystems.com/master/legacyDash.html?Hostname=10.173.147.1&Port=8010&Protocol=http&Wuid=W20150429-143016&ResultName=leeddx_vizvalidation_Comp_Ins002_DDL

**Comment by GordonSmith** [comment]
@drealeed - That link is dead, can you recreate another test?

**Comment by GordonSmith** [comment]
Assigning back to Drea for new link

**Comment by mlzummo** [comment]
@GordonSmith Status?

**Comment by GordonSmith** [comment]
@drealeed Closing as expired, please re-open if needed
