### ISSUE TITLE
DashboardDockPanel and DashboardGrid popup logic should be abstracted into a PopupManager class

### ISSUE THREAD

**Issue by jbrundage** [hpcc-systems/Visualization#3279]
- [ ] Common up popup logic into common code between Dashy and Dashboard
 - [ ] Ensure popup works in runtime as well as Dashy (in DSP)
 - [ ] Its hard to close the popup - should it autoclode on apply?  or simply clicking outside of it?

**Comment by jbrundage** [comment]
```javascript
class PopupManager {
    _popups;
    _popupIdx;
    addPopup(cp: VizChartPanel) {}
    removePopup(cp: VizChartPanel) {}
    popupPanels() {}
    popupChartPanels() {}
}
```

**Comment by GordonSmith** [comment]
Turns out the popup filter is not working in runtime Dashbaord - should probably fix that at same time.

**Comment by GordonSmith** [comment]
Also its currently not intuitive to "close" the popup.

**Comment by GordonSmith** [comment]
@lrenn FYI
