### ISSUE TITLE
to allow multiple select actions for widgets, viz widgets need to start using the "event" json attribute in HIPIE DDLs rather than "onSelect"

### ISSUE THREAD

**Issue by drealeed** [hpcc-systems/Visualization#332]
HIPIE-generated DDLs now have an events section that reflects the same structure as onSelect but allows multiple different events for different options (click, dbl-click, etc.)  The viz widgets will need to switch to checking "events" rather than "onSelect" to allow this feature to work. All HIPIE-generated DDLs have had the "events" attribute in them for the past month or so as well as "onSelect". Example from a ddl below

                "events": {
                    "click": {
                        "mappings": {
                            "myname": "myname",
                            "clean_st": "clean_st"
                        },
                        "updates": [
                            {
                                "visualization": "TableFormDefined",
                                "instance": "Ins002",
                                "datasource": "Ins002_dsOutputDefined",
                                "merge": false
                            },
                            {
                                "visualization": "StateFormDefined",
                                "instance": "Ins002",
                                "datasource": "Ins002_dsOutputDefined",
                                "merge": false
                            }
                        ]
                    }
                },
                "onSelect": {
                    "mappings": {
                        "myname": "myname",
                        "clean_st": "clean_st"
                    },
                    "updates": [
                        {
                            "visualization": "TableFormDefined",
                            "instance": "Ins002",
                            "datasource": "Ins002_dsOutputDefined",
                            "merge": false
                        },
                        {
                            "visualization": "StateFormDefined",
                            "instance": "Ins002",
                            "datasource": "Ins002_dsOutputDefined",
                            "merge": false
                        }
                    ]
                }
            },

**Comment by drealeed** [comment]
Events currently generatable by HIPIE are:
	click, dblclick, mousedown,mouseup, mouseenter,mouseleave, mousemove, mouseover, mouseout,nullEvent, featureselected, featureunselected;

**Comment by dabayliss** [comment]
@drealeed  We should add a 1.3 hipie issue to delete the OnSelect .... help focus the mind a little. I don't want the mutant visualizations to get to the customer ...

**Comment by GordonSmith** [comment]
@drealeed - what do you have in mind for:
,nullEvent, featureselected, featureunselected

**Comment by drealeed** [comment]
I don't have any particular examples of how they'd be used; they're in the list just so that HIPIE is capable of handling the full suite of known html events once they're implemented in the viz widgets.
