### ISSUE TITLE
HIPIE Visualizations work in viz.hpccsystems.com, but not in the candidate-0.9.4 dashboard test page

### ISSUE THREAD

**Issue by drealeed** [hpcc-systems/Visualization#333]
The following url fails to show a dashboard:
http://rawgit.com/hpcc-systems/Visualization/candidate-0.9.4/demos/dashboard/index.html
with url 10.173.147.1:8010/WsWorkunits/WUResult?Wuid=W20150430-123643&ResultName=leeddx_vizvalidation_Comp_Ins002_DDL specified in the form box.

The same visualization does show up at 
http://viz.hpccsystems.com/master/legacyDash.html?Hostname=10.173.147.1&Port=8010&Protocol=http&Wuid=W20150430-123643&ResultName=leeddx_vizvalidation_Comp_Ins002_DDL

**Comment by GordonSmith** [comment]
There is an issue in 0.9.4 (awaiting review) which would cause that.






Gordon





From: drealeed
Sent: ‎Thursday‎, ‎April‎ ‎30‎, ‎2015 ‎5‎:‎41‎ ‎PM
To: hpcc-systems/Visualization





The following url fails to show a dashboard:
http://rawgit.com/hpcc-systems/Visualization/candidate-0.9.4/demos/dashboard/index.html
with url 10.173.147.1:8010/WsWorkunits/WUResult?Wuid=W20150430-123643&ResultName=leeddx_vizvalidation_Comp_Ins002_DDL specified in the form box.

The same visualization does show up at 
http://viz.hpccsystems.com/master/legacyDash.html?Hostname=10.173.147.1&Port=8010&Protocol=http&Wuid=W20150430-123643&ResultName=leeddx_vizvalidation_Comp_Ins002_DDL

**Comment by drealeed** [comment]
OK, thanks.
Drea

**Comment by GordonSmith** [comment]
@drealeed I believe this is resolved now - can you confirm and close?

**Comment by drealeed** [comment]
Fixed
