### ISSUE TITLE
Receiving error in console

### ISSUE THREAD

**Issue by lucashby** [hpcc-systems/Visualization#3336]
I started getting this error in the console but I'm not sure exactly where it's coming from (although I do believe it is in one of the Visualization libs):

Uncaught (in promise) TypeError: Cannot read property 'getAttribute' of null
    at V.attr (<anonymous>:1:9148)
    at i.update (<anonymous>:1:56702)
    at SVGGElement.<anonymous> (<anonymous>:1:124657)
    at V.each (<anonymous>:1:8990)
    at i.e.render (<anonymous>:1:124548)
    at <anonymous>:1:125138
    at new Promise (<anonymous>)
    at i.e.renderPromise (<anonymous>:1:125110)
    at t.<anonymous> (<anonymous>:1:36713)
    at <anonymous>:1:1916

When I click the line in Chrome and have it 'pretty-print' the js, the top of the file does say the following:

!function(t, e) {
    "object" == typeof exports && "undefined" != typeof module ? e(exports, require("@hpcc-js/util")) : "function" == typeof define && define.amd ? define(["exports", "@hpcc-js/util"], e) : e((t = t || self)["@hpcc-js/common"] = {}, t["@hpcc-js/util"])

**Comment by GordonSmith** [comment]
FWIW - I have fixed another (probably unrelated) one of these recently.  I suspect we need to augment our unit tests to include an empty `columns` and `data` test for each viz...

**Comment by GordonSmith** [comment]
Actually (depending on how your bundling) our latest versions now have working source maps, which should help this type of scenario (assuming you have enabled sourcemaps in your environment?)
