### ISSUE TITLE
404 response for dojo/resources/blank.gif

### ISSUE THREAD

**Issue by lesterlpena** [hpcc-systems/Visualization#3343]
It has very low priority but the majorities of the graphs request an unknown gif image, adding a 404 Not found response.

To reproduce it:
https://raw.githack.com/hpcc-systems/Visualization/master/demos/gallery/playground.html?./samples/table/Basic.js

and check the network tab

**Comment by GordonSmith** [comment]
Thanks - I have noticed this before and will be revisiting the next time I update the `@hpcc-js/dgrid-shim` dependencies - I don't believe it has any negative impact.
