### ISSUE TITLE
StackedBar chart

### ISSUE THREAD

**Issue by chuajoey** [hpcc-systems/Visualization#345]
![image](https://cloud.githubusercontent.com/assets/12235336/7455161/3a0418cc-f2bd-11e4-8e89-f3967961d1e7.png)

**Comment by mlzummo** [comment]
Am Charts and Google both have a stacked barchart, the publish param to turn this on is "isStacked"

**Comment by chuajoey** [comment]
I'd like it to support a "waterfall" mode - i.e., if any of the "bar" is negative, it should pull the entire stacked bar down so that the top of the bar is the net value (sum of the bars) on the y-axis.

**Comment by mlzummo** [comment]
I think AmCharts might support this out of the box.

**Comment by chuajoey** [comment]
It supports negative numbers, but not quite correctly if the bars are meant to be cumulative.  For example, the top of the column in this one should be at 2.8 rather than at 5:

![image](https://cloud.githubusercontent.com/assets/12235336/7456165/a865cee8-f2c5-11e4-9958-6b027f2ad909.png)

**Comment by chuajoey** [comment]
btw, c3 also supports stacked bars (using "group")... but same problem if the bars are cumulative.
