### ISSUE TITLE
Issue with "Total" element in IE

### ISSUE THREAD

**Issue by lucashby** [hpcc-systems/Visualization#3450]
In IE 11 (Version: 11.476.18362.0), there is a visual issue with "Total" element for bar/column charts, line charts, and pie charts (just the ones I've noticed although there could be others that have the same issue):

![image](https://user-images.githubusercontent.com/938632/70161006-663fa880-1689-11ea-9e98-112197320837.png)

**Comment by jbrundage** [comment]
I've recreated the issue locally and am investigating.
