### ISSUE TITLE
Implementation of Google Street View, Terrain View on Leaflet if mapType is 'Google'

### ISSUE THREAD

**Issue by apcrash** [hpcc-systems/Visualization#3452]
Hi,

We would like to request for these features to be controllable and set to enabled or disabled if possible.

**Comment by GordonSmith** [comment]
This will need further discussion as the Leaflet implementation for this does not allow simply enabling "Street View", but we could add hyperlinks to pin tooltips to open the street view in a new window or popup dialog?
