### ISSUE TITLE
Chart Panel (Pie Chart) Scrollbar Covering Text

### ISSUE THREAD

**Issue by lucashby** [hpcc-systems/Visualization#3488]
Thank you for fixing all these little bugs so quickly.  You guys rock!

I've got one more, which I tried to fix myself a bit with some CSS, but alas I could not seem to get it to do what I needed.  

When using a pie chart and setting the '.legend_labelMaxWidth' on the ChartPanel, the scrollbars do appear, which is awesome, but there seems to be a bit of missing padding on the right for the vertical scrollbar and the text sometimes gets covered by it:

![image](https://user-images.githubusercontent.com/938632/72813265-0c8f3f80-3c31-11ea-927b-e19827da4266.png)

**Comment by lucashby** [comment]
Once again, you guys rock!  When should I be able to update my npm package?

**Comment by jbrundage** [comment]
@lucashby a fix should be available via npm in the next build (most likely on Monday)
