### ISSUE TITLE
Request feature for bar chart

### ISSUE THREAD

**Issue by apcrash** [hpcc-systems/Visualization#3568]
We would like to request for the bar chart to have the following features:

- Allow label to be placed in the bar chart along with the value on the right most part. If the label is longer than the bar chart it should be ellipsized. The value has more priority than the label.

- To be able to add an icon on the left side of the y-axis.

Here's the proposed image:
![image](https://user-images.githubusercontent.com/832775/79315898-35745780-7f36-11ea-84d0-2e98f82294ae.png)

**Comment by GordonSmith** [comment]
@jbrundage can you open a separate issue for the "Icon" label feature.
@apcrash Can we assume the "Icon Label" will be similar to a Font Awesome type Icon (similar to a Graph Vertex Icon)?

**Comment by apcrash** [comment]
@GordonSmith yes

**Comment by jbrundage** [comment]
When a bar is very thin with no room to display either the inner label *or* the value... what is the expected behavior?

**Comment by GordonSmith** [comment]
By thin do you mean width or height?  
* Width:  The value pops the right (like it does today) and the label becomes ellipses as per the above comment
* Height:  The font gets smaller like value does today.
