### ISSUE TITLE
Bar Chart Inner Text Ellipsis overlaps value

### ISSUE THREAD

**Issue by apcrash** [hpcc-systems/Visualization#3626]
Hi,

It seems that bar chart inner text ellipsis overlaps value. See example:

![image](https://user-images.githubusercontent.com/832775/83875323-7a17b480-a769-11ea-992d-a6a875f74e68.png)

**Comment by GordonSmith** [comment]
Looks like the ellipses ignore the value width?

**Comment by jbrundage** [comment]
I've not been able to recreate this issue, but I suspect it's related to the font family. Is a custom font family being applied to that inner text?

**Comment by jbrundage** [comment]
@apcrash I've been unable to experience this issue. Could you include the properties the chart is using in your application?
![image](https://user-images.githubusercontent.com/1891935/84168877-ee8e7400-aa45-11ea-94f7-ff517e9b54cd.png)
