### ISSUE TITLE
Serialization Test broken

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#369]

**Comment by mlzummo** [comment]
In Persist.js the deserialize method attempts to build the include path using the widget's class:
var path = "src/" + state.__class.split("_").join("/");

**Comment by mlzummo** [comment]
var classSplit = state.__class.split(' ');  
            var path = "src/" + classSplit[classSplit.length-1].split("_").join("/");

**Comment by jbrundage** [comment]
This fixes it (assuming the appropriate include path can reliably be retreived from the end of the widget._class string.

var classSplit = state.__class.split(' ');
var path = "src/" + classSplit[classSplit.length-1].split("_").join("/");
