### ISSUE TITLE
Timeline Issue

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#3761]
New timeline has some issues:
![image](https://user-images.githubusercontent.com/966863/107642888-5d733b00-6c6d-11eb-8536-b9098ef7891f.png)

Old version:
![image](https://user-images.githubusercontent.com/966863/107643058-93b0ba80-6c6d-11eb-9900-e533ef353f9e.png)

https://play.hpccsystems.com:18010/?Wuid=W20210209-134408&Widget=GraphsWUWidget

**Comment by GordonSmith** [comment]
@jbrundage did this get resolved?

**Comment by jbrundage** [comment]
Yes
