### ISSUE TITLE
Date Range widget

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#389]
Please see HIPIE issue https://github.com/hpcc-systems/HIPIE/issues/827

We will need a min max widget for date range, either a slider or calendar chooser or both.

**Comment by GordonSmith** [comment]
Partial solution(s) in 1.10.0 (or earlier), still need to add support to slider range.

**Comment by jchambers-ln** [comment]
please post to https://github.com/hpcc-systems/DSP/issues/385 once this is complete

**Comment by GordonSmith** [comment]
@jchambers-ln (this is marked 1.12) is that ok?
