### ISSUE TITLE
Feature request: Allow setting of position of annotation icons in different directions for the Link Chart

### ISSUE THREAD

**Issue by paggal01** [hpcc-systems/Visualization#3990]
Hi,

I would like to request for a feature where we can set the placement of different annotations around the Vertex. I would also like for it to have event emitters that can reach the vertex and graph.

A working example would be an expandable (+) icon on the top right of the node where we can click to expand the link chart and add new vertices that are connected to it.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/99411447/176387665-ba4987bf-b52e-44e3-9a1e-372d0994c706.png)
.

**Comment by GordonSmith** [comment]
@jbrundage at the moment we have annotations located at the RHS of the main label.  But it would also be useful to have them at:
* Icon North East
* Icon North West
* Icon North
* Text South
* Text West

Also annotations should emit a click, dblclick and context click events, in such a way that the receiver knows where it originated from

**Comment by jbrundage** [comment]
Here's a screen cap of the demo page I'm working on for this:
![image](https://user-images.githubusercontent.com/1891935/181768265-b32c3219-e8a5-473e-b15b-da9452b87125.png)
