### ISSUE TITLE
Fix security issue detected by CheckMarx tool.

### ISSUE THREAD

**Issue by rubenlnr** [hpcc-systems/Visualization#4069]
After running a code analysis using CheckMarx  tool we got  a report with a security issue in this line: 
https://github.com/hpcc-systems/Visualization/blob/trunk/packages/common/src/Utility.ts#L490

You can check an attached screenshot 
![Issue](https://user-images.githubusercontent.com/116656755/219168017-c6dd595e-e9c9-4756-a946-cedc6318fa79.png)

Issue Description

![pol1](https://user-images.githubusercontent.com/116656755/219167562-fe67fd8d-01c5-4354-a53a-aef47e75deeb.png)
![pol2](https://user-images.githubusercontent.com/116656755/219167570-c0ebe874-4b14-4ae8-b12e-e2bd0178ee66.png)
![pol3](https://user-images.githubusercontent.com/116656755/219167577-fe30f132-c541-4609-a50c-d441049fe0d7.png)

**Comment by rubenlnr** [comment]
Thanks for trying to fix the problem but we tested again and the same error remains. I think is related to the use of "href" without validate it. Check this screenshot:
![PrototypePollution](https://user-images.githubusercontent.com/116656755/220965598-226c232e-67da-4800-97e7-3b4c0e4b637b.png)

**Comment by rubenlnr** [comment]
These links are related the same issue: 
https://brightsec.com/blog/prototype-pollution/
https://stackoverflow.com/questions/64530473/how-can-i-prevent-window-location-replace-from-being-overwritten

Thank you for your work!

**Comment by GordonSmith** [comment]
In this context it has to be a false positive report:
1.  "href" is a string (and a valid URL at that), so unless I run an eval on one of the extracted params, there is not much damage that can be done.
2. urlParam is only actually used in a few demo apps:  https://github.com/hpcc-systems/Visualization/search?q=urlParams
