### ISSUE TITLE
Table Pagination Row Count

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#415]
Table with pagination turned on, should be able to automatically adjust its "row count" so that it always fits the available space.

**Comment by mlzummo** [comment]
fixed via #428

**Comment by GordonSmith** [comment]
@mlzummo FYI - Had you added "Fixes #415" to your commit message (or Fixes GH-415) it would have been automatically referenced here and it would automatically close this issue once it makes its way into the master branch...

**Comment by GordonSmith** [comment]
Closing Fixed.
