### ISSUE TITLE
Refactor Test Data

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#442]
Test Data should only be loaded on demand and should not be included within the JS directly.

**Comment by mlzummo** [comment]
use a require call within testData function to load the testData obj on demand? ... would need a render callback call due to async nature

**Comment by mlzummo** [comment]
testData = function(widget) { 
  switch(widget.classID()) { 
    ... 
} 
}
testData would call widget.data with the data

**Comment by mlzummo** [comment]
or test.createTestWidget(classID) and it would return a pre-loaded widget ready to be rendered

**Comment by GordonSmith** [comment]
@dtsnell4 - here is a suggested approach:  http://rawgit.com/GordonSmith/Visualization/GH-442/demos/dermatology.html

**Comment by dtsnell4** [comment]
@GordonSmith No problem. Should I assume this is the priority of my issues?

**Comment by GordonSmith** [comment]
After any 1.6.0 issues (not the DSP ones) but it is fairly important and the circular refs are killing us.

**Comment by jbrundage** [comment]
@GordonSmith @mlzummo @dtsnell4 
Gordon, in your email you mentioned *"The other main limitation of testData is that it can only load one “test/sample” but for things like the Column Widget it would be nice to have several tests (date, ordinal, range etc.)."*

If we can/will offer several different "test" data sets for our various charts, how can we standardize the selection of these different testData options? (ie: widget.testData(0) or widget.testData(1) along with widget.getTestDataSets())

Offering these different testData sets will also allow us to showcase the wide range of these charts' capabilities in terms of publish params. For example, the amchart/Bar is capable of displaying data in many different ways based on publish parameters. And certain publish param configurations are only appropriate for certain types of data (ie: Stacked100% vs Stacked3D etc)

Thoughts?

**Comment by GordonSmith** [comment]
@dtsnell4 Did you look at my suggested approach - I don't think "testData" will exist any more and it more a ```testFactory.create("hpccChart", "column", "rangeDemo", function(widget) {...});``` paradigm.

And all of that is 100% out of the "src" folder and in the "test" folder?

**Comment by dtsnell4** [comment]
I have been looking in between other issues...  will pose some questions shortly

**Comment by dtsnell4** [comment]
I like what you did with this, very well thought out and should flexible as new data sets come up.  

I get the premise of Factory.js...  simply call Factory.create(path_to_factory, widget_type, dataset_type, callback) and the callback in the page handles what to do with the returned widget.   dataFactory.js is also very straightforward and elegant, just call with the type of data (1d, 2d, ND, etc) and the data set (subject, time, linear, etc.).

ChartFactory.js is also very simple to understand, my only question is how were you planning on extending it to the other charts?  My initial thought is that ChartFactory will just add objects for the rest of the HPCC widgets.  There will then be a AMChartFactory.js, C3ChartFactory.js, GoogleChartFactory.js etc. with the appropriate objects for their widgets.  Is that correct, or were you planning on ChartFactory.js to hold all of the widgets in one file?

**Comment by GordonSmith** [comment]
I think one per folder works - I don't have a feel for how big the file will get (just from a source code navigation point of view), The way its set up you can start with one and then break into others as needed?  Or just start with one per folder...

**Comment by GordonSmith** [comment]
The one important design consideration is that the actual widget's source file isn't loaded up front, but only on demand.

**Comment by dtsnell4** [comment]
I will probably start by expanding Chart, I'd like to see how other data fits in and we can get an idea how big things will get.  Once thats done doing the others should be fairly painless.  I will show you my progress once I do a few more to make sure I'm heading down the right road.

**Comment by GordonSmith** [comment]
Sounds good...

**Comment by dtsnell4** [comment]
@GordonSmith I added the rest of the HPCC charts and everything went as expected, until I got to MultiChart of course...  http://rawgit.com/dtsnell4/Visualization/GH-442/demos/dermatology.html

**Comment by GordonSmith** [comment]
I think its just because your using 1D data?

**Comment by GordonSmith** [comment]
2D will work with the most charts.  But you will have a sample for 2D + ND

**Comment by dtsnell4** [comment]
@GordonSmith here is the latest if you are interested in taking a look.  Added a few more libraries, including Tree as I was interested in adding some new data.  Needs tweaking of course but so far so good.  http://rawgit.com/dtsnell4/Visualization/GH-442/demos/dermatology.html

**Comment by GordonSmith** [comment]
@dtsnell4 Looking good - a couple of thoughts which may come into play in the future:
* We may want the ability to delay load some data samples if they are very large
* You should be removing the "testData" methods as you go along.
* Dermatology may need a better interface for selecting which sample you want to pick (rather then 1 large drop list...

**Comment by dtsnell4** [comment]
@GordonSmith I agree with everything, what are your thoughts about selecting data samples?  Add a drop down to the property editor?  A publish parameter?  (that would be the easiest, but then you have still have a reference to test data in the widget js which is what we are trying to move away from)

**Comment by GordonSmith** [comment]
A tree structure would be good?

**Comment by dtsnell4** [comment]
Sorry, what do you mean by that?

**Comment by GordonSmith** [comment]
Updating the dermatology page with a better selector (given how many samples we potentially could have) is low priority for now - but a drop select with a tree in it would be good?  I am open to suggestions.

**Comment by dtsnell4** [comment]
@GordonSmith I've think I've finished adding all the charts to the new Dermatology page.  There are a couple bugs I am still chasing down.  Also I did not implement the tree selector yet, but I have a plan and I will begin that next.  I just wanted to let you see it, there's a lot there and will take some time. If it looks good I will finish up the tree menu and issue a PR.

https://securedev02.accurint.com/snelda01/VIZ/demos/dermatology.html

Looking forward to the comments.

cc @mlzummo @jbrundage in case you want a preview

**Comment by GordonSmith** [comment]
Can you do a rawgit link?

**Comment by dtsnell4** [comment]
Sorry, I just pushed  http://rawgit.com/dtsnell4/Visualization/GH-442/demos/dermatology.html

**Comment by dtsnell4** [comment]
And yes, to my knowledge everything is added...  if you see anything missing please let me know.

**Comment by GordonSmith** [comment]
For the layouts can you replace the TextBox samples with actual charts like we used to have in the v1.4.0 branch:  https://github.com/hpcc-systems/Visualization/blob/v1.4.0/src/layout/Grid.js

(We had to remove them due to the circular references - which is also why we need to make this change!) - then you can issue the PR.

**Comment by GordonSmith** [comment]
(PR should be for 1.8.0)

**Comment by dtsnell4** [comment]
@Gordon, should I make the tree menu first, or should that be a separate issue and PR?

**Comment by GordonSmith** [comment]
Do both togeather
