### ISSUE TITLE
Interactive charts not working correctly for C3 chart

### ISSUE THREAD

**Issue by dineshshetye** [hpcc-systems/Visualization#444]
Ran into this issue when a Chloropeth updates a pie. Instead of refreshing the C3 pie/C3 chart a new wedge is getting added to the pie. It works for fine for Table, Google pie, d3 pie. Let me know if you need more information on this.

![image](https://cloud.githubusercontent.com/assets/1731313/7893919/e673ea02-0630-11e5-9268-112b3660b759.png)

**Comment by GordonSmith** [comment]
Can you switch the view to Table and double check the data (and paste it here)?

**Comment by dineshshetye** [comment]
![image](https://cloud.githubusercontent.com/assets/1731313/7899489/977e5780-06f2-11e5-863f-ae7061350f2d.png)

![image](https://cloud.githubusercontent.com/assets/1731313/7899492/b2e4b06e-06f2-11e5-8dac-f22442848fb9.png)

**Comment by GordonSmith** [comment]
Ah ok - interesting.
