### ISSUE TITLE
Add Persist ability to apply themes by deserializing an array of _proto_ serial strings

### ISSUE THREAD

**Issue by jbrundage** [hpcc-systems/Visualization#446]

**Comment by GordonSmith** [comment]
@jbrundage I suspect I asked you to open this for me, but I can't remember the full details?

**Comment by jbrundage** [comment]
@GordonSmith I think we've come to a different understanding of how this should be implemented.

Here's a PR with my suggested implementation:
https://github.com/hpcc-systems/Visualization/pull/686

**Comment by jbrundage** [comment]
@GordonSmith I think this can be closed, yes?
