### ISSUE TITLE
Dermatology Property Editor should be customizable

### ISSUE THREAD

**Issue by prakash-sukumar** [hpcc-systems/Visualization#455]
User should have the ability to customize the property editor to filter out the fields displaying, instead of displaying all the fields. Say for example propEditor.showProperties([widgethtml:"designmode",widgetcontent :"surfaceTitlePadding,surfaceTitleFontSize","title","widget"])

**Comment by jbrundage** [comment]
@GordonSmith Can we add this to 1.8.0?

**Comment by GordonSmith** [comment]
Is this the same excludeTags or is just similar?

**Comment by jbrundage** [comment]
It's similar, I was about to create a PR with this fix and then I realized it wasn't a part of 1.8.0
