### ISSUE TITLE
Google Bar throws an exception “Data column(s) for axis #0 cannot be of type string”

### ISSUE THREAD

**Issue by dineshshetye** [hpcc-systems/Visualization#459]
‘Google Bar’ throwing an exception “Data column(s) for axis #0 cannot be of type string”. Looks like it expects one column to be an Integer value (and in our case a String value is being passed).

![image](https://cloud.githubusercontent.com/assets/1731313/8038343/f22efd76-0dd0-11e5-90bd-7b5829a75fe4.png)

**Comment by mlzummo** [comment]
@dineshshetye do you have any code that demonstrates this bug?

**Comment by GordonSmith** [comment]
@mlzummo Change the values in TestData to strings...

**Comment by mlzummo** [comment]
do we want to iterate all the data being passed into the chart and convert to the appropriate type (str->int) ?

**Comment by GordonSmith** [comment]
I suspect that is what will need to be done.  I would use parseFloat rather than other techniques as we want it to fail (rather than return 0) if there is non numeric values.

**Comment by GordonSmith** [comment]
@dineshshetye - Can you open a corresponding issue for HIPIE as the values should really be numeric at source - this is only a workaround for the actual issue.

**Comment by dineshshetye** [comment]
Created an issue in HIPIE: https://github.com/hpcc-systems/HIPIE/issues/897
