### ISSUE TITLE
Primary hosting of splash page, demos, tutorial/doc and tools

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#461]
@GordonSmith Were you able to find out any more info about that?

**Comment by dtsnell4** [comment]
@GordonSmith @jbrundage @mlzummo I know we discussed serving these pages directly from github.  They actually make it very easy...   [https://pages.github.com/](https://pages.github.com/).   

You can also use custom domain names and subdomains through a DNS provider if needed.  Food for thought.

**Comment by GordonSmith** [comment]
The problem is with hosting demos that way - I was doing it for a while, but the whole rawgit thing was easier.
