### ISSUE TITLE
need to move widget.class up two levels into parent container

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#469]
need to move widget.class up two levels into parent container

**Comment by GordonSmith** [comment]
We need to ensure the specific overlay DIV has the same classes as the SVG <g> widget.

**Comment by GordonSmith** [comment]
@mlzummo I have forgotten what this issue actually is?

**Comment by mlzummo** [comment]
@GordonSmith I think this was actually solved when we went with widget.class += " some_other_class" ... if so then this can be closed
