### ISSUE TITLE
AMChart Floating Column example HTML will not load

### ISSUE THREAD

**Issue by dtsnell4** [hpcc-systems/Visualization#474]
In the Playground, select the AMChart Floating Column and click the Example Code tab.  Note the chart should have loaded fine in the left panel.   Click the "Demo Example Code (Plain)" link which opens the sample html in a new tab.  The chart does not load and the console error is "Uncaught TypeError: Cannot read property 'data' of undefined". It apparently dies somewhere in the columns() method.  Again, the chart loads fine on the left with the exact same data.

![floatingcolumn](https://cloud.githubusercontent.com/assets/4304235/8092136/d3c92a62-0f85-11e5-8f35-ecbcff48dc0f.PNG)

**Comment by GordonSmith** [comment]
Looks like "columns" is not returning "this".
