### ISSUE TITLE
Overlay Choropleths onto Google Maps

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#501]

**Comment by mlzummo** [comment]
I don't understand how that will work? google actually has there own choropleth maps beyond there google maps platform but there flash based. Cant find their link but here is an example: 
http://digitalsplashmedia.com/2014/07/creating-choropleth-maps-with-google-fusion-tables/

Could you explain this a bit more/perhaps an example?

**Comment by GordonSmith** [comment]
We are currently able to render items onto google maps using lat and long (see test page). If we can calculate the choropleth in terms of lat and long we will be able to display that on top of the google maps.

**Comment by GordonSmith** [comment]
Resolved
