### ISSUE TITLE
Widgets does not list all the chart type

### ISSUE THREAD

**Issue by prakash-sukumar** [hpcc-systems/Visualization#502]
When rendering charts using Graph Marshaller, the widgets does not list all the chart types.But when i look at the ECL watch "https://viz.hpccsystems.com/v1.0.0/apps/legacyDash.html?Hostname=216.19.105.2&Port=18010&Protocol=https&Wuid=W20150618-022527&ResultName=thanse01_sideeffect_Comp_Ins003_DDL" the widgets list all the chart types.

**Comment by prakash-sukumar** [comment]
As we no longer using the Graph Marshaller anywhere in DSP, Can we close this issue ? @dineshshetye

**Comment by GordonSmith** [comment]
Closing as obsolete.
