### ISSUE TITLE
Add "Border Layout"

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#517]
A border layout will look like this:
![image](https://cloud.githubusercontent.com/assets/966863/8325859/8a993060-1a54-11e5-8312-f940954257b9.png)

Where the top/left/right/bottom are fixed size and the centre will scale as the page sizes

Note:  The "left" is the image is not correct should look the same as the right...

**Comment by jbrundage** [comment]
This sounds like fun. I'll begin working on it today.

**Comment by GordonSmith** [comment]
Fixed by GH-557
