### ISSUE TITLE
Persist.serialize(graph) not working as expected

### ISSUE THREAD

**Issue by RajalakshmiElumalaiCts** [hpcc-systems/Visualization#520]
Persist.serialize(Vertex/Edge/Graph) is generating the serialized string.But while deserializing/recreating the objects(Vertex/Edge/Graph) from the serialized string, it is not behaving as expected.

@GordonSmith

**Comment by GordonSmith** [comment]
Work around example provided - pushing proper fix out to minor version.

**Comment by GordonSmith** [comment]
Pushing back as Graph Widget is due a re-write.

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
