### ISSUE TITLE
Persist.serialize() not working for Form Data

### ISSUE THREAD

**Issue by prakash-sukumar** [hpcc-systems/Visualization#522]
Serializing the JSON to form object is not working

sample json data for form widget : 
formtestWidget =[{
         "__version": 3,
         "__class": "form_Form",
         "__id": "scoredform",
         "__properties": {
           "inputs": [
             {
               "__version": 3,
               "__class": "form_Input",
               "__id": "_w7",
               "__properties": {
                 "name": "productline",
                 "label": "ProductLine",
                 "type": "textbox"
               }
             },
             {
               "__version": 3,
               "__class": "form_Input",
               "__id": "_w9",
               "__properties": {
                 "name": "revenue",
                 "label": "Revenue",
                 "type": "textbox"
               }
             },
             {
               "__version": 3,
               "__class": "form_Input",
               "__id": "_w11",
               "__properties": {
                 "name": "ScoreCombine",
                 "label": "Score Combine",
                 "type": "textbox"
               }
             },
             {
               "__version": 3,
               "__class": "form_Input",
               "__id": "_w13",
               "__properties": {
                 "name": "RecordsToReturn",
                 "label": "Records to Return",
                 "value": "2",
                 "type": "textbox"
               }
             },
             {
               "__version": 3,
               "__class": "form_Input",
               "__id": "_w15",
               "__properties": {
                 "name": "Threshold",
                 "label": "Threshold",
                 "type": "textbox"
               }
             }
           ]
         }
}];

with the above variable i am not able to serialize using Persist

var formPersist = Persist.serialize(formtestWidget);

since the above code is not working , not able to execute the below code and persist the form inputs in the targeted div.

Persist.create(formPersist,function(formWidget){
           formWidget.target(params.formId).render();
 });

**Comment by GordonSmith** [comment]
@prakash-sukumar your example looks wrong:  
To create a string version of an object you call 
```
var str = Persist.serialize(widget);
```
And then to recreate a widget from that string you call:
```
Persist.create(str, function(Widget) {
    widget.target("xxx").render();
});
```

**Comment by jbrundage** [comment]
You can use your formtestWidget in its current state like this 
```Persist.create(formtestWidget[0], function(Widget) {
    widget.target("xxx").render();
});```

**Comment by GordonSmith** [comment]
Closing invalid
