### ISSUE TITLE
Add "Ordinal" Legend Widget

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#523]
Add a legend widget which "just works" with any of our chart APIs

I think it should be derived from other/Table with CSS styling to hide the borders.  This will allow automatic paging or scrolling as users see fit.

**Comment by jbrundage** [comment]
Should this Legend Widget have a "widgetArray" publish parameter containing references to widgets that it's "attached" to? 
Potentially...: 
* ...allowing the Legend widget to specify the color palette for the widgets it references? 
* ...allowing the Legend widget to interact with its referenced widgets (hover effects and/or filtering?)

**Comment by GordonSmith** [comment]
Resolved
