### ISSUE TITLE
TitleWidget

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#541]
A hybrid Title/Toolbar to replace the existing HTML Surface Title.

```
[(i)          My Title              <w><w><w>]
```

Type of thing.

**Comment by mlzummo** [comment]
@GordonSmith I am thinking of just closing this thoughts? ... J has a pretty cool toolbar that uses the grid i had a version that worked ok but nothing that can replace the title ....

**Comment by GordonSmith** [comment]
I am fine with that
