### ISSUE TITLE
GEOHASH on a choro widget

### ISSUE THREAD

**Issue by dabayliss** [hpcc-systems/Visualization#561]
Today our choro follows purely geo-political boundaries.

There are times when pure geo boundaries are more appropriate. We would like to add

GEOHASH(x)

to the choro interface ( @drealeed this will eventually hit you ) - this provides for aggregations using geohashes. I have C++ to turn a given geohash into lat/long - I suspect we could convert to JS or track down a JS version if required.

V2 would support

GEOHASH(x,2,7)

where the two numbers show the maximum and minimum level of drilling supported. this would allow you to zoom in and out of a geohashed choro.

**Comment by GordonSmith** [comment]
I don't understand what you mean by "maximum and minimum level of drilling supported"?  If a GEOHASH(x) brings me to a lat/long, what do the 2, 7 equate to?

**Comment by dabayliss** [comment]
A pure geohash is a 12 byte string that identifies a patch of earth about the size of a bed. You can 'truncate' the right of this string to give you a series of nested boxes.

Thus the US is covered by about 16 geohashes of length 2. This might be my initial display. Each of the two byte codes gives you a bounding box - and I provide a count for each of the boxes. You now double click on one of the sixteen boxes and it opens up into 32 geohashes - each of length 3. Again I can give you the counts.

The 2 and 7 in the context would be the shortest (biggest area) geohash I can aggregate for you and the 7 would be the smallest (finest detail) I can give you

**Comment by GordonSmith** [comment]
Got it - Good description here:  https://github.com/davetroy/geohash-js (JS looks good on initial inspection) - includes a calculateAdjacent also...

**Comment by GordonSmith** [comment]
Resolved
