### ISSUE TITLE
Surface Height/Width throws JS errors when attempting to set to 0 or less

### ISSUE THREAD

**Issue by jbrundage** [hpcc-systems/Visualization#565]
There are a few use cases that can result in attempting to set a layout/Surface object to height or width of 0 or less.

For example... setting one of the layout/Border sections to a height or width of 22 or less results in a 0 width or height Surface object and it will cause the other sections to resize appropriately while the error'd section will continue to display its original dimensions (causing weird overlapping issues).

Another example is a layout/Grid Cell not having enough room (with padding, border and gutter) to display its Surface objects with 1px or larger dimensions... this will also throw JS errors though it doesn't currently break any functionality.

**Comment by GordonSmith** [comment]
@jbrundage This is higher priority now as it is creating a lot of noise in the test suite - FWIW I have fixed a bunch of the similar issues (rect invalid shape etc...)

**Comment by GordonSmith** [comment]
tests are clean now - closing.
