### ISSUE TITLE
Merge -- two controlling widgets controlling a single widget

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#580]
The HIPIE DUD and resulting ddl appear to be rendered right but the visualization doesn't act as expected please see the following issue for more detail:

https://github.com/hpcc-systems/DSP/issues/558

**Comment by mlzummo** [comment]
Is this still occurring on the table widget (the referenced issue was caused by the table not re-rendering the widget after selection/update) .. can you provide another example?

**Comment by jchambers-ln** [comment]
This is still occurring  in Thor based but not Service based visualizations.

**Comment by drealeed** [comment]
Example of the problem:
http://rawgit.com/GordonSmith/Visualization/master/demos/marshaller/index.html?Hostname=10.173.147.1&Port=8010&Protocol=http&Wuid=W20150720-120716&ResultName=leeddx_testmergeinteractivitydashboard_Comp_Ins003_DDL

DDL:
  
     [{"visualizations":[{"id":"pietest","source":{"output":"View_pietest","mappings":{"weight":"salesvolume_SUM","label":"productline"},"id":"Ins003_dsOutput"},"type":"PIE","title":"pietest","fields":[{"id":"productline"},{"id":"salesvolume_SUM"}],"properties":{"charttype":"C3_PIE"},"events":{"click":{"mappings":{"productline":"productline"},"updates":[{"visualization":"testableinttarget","instance":"Ins003","datasource":"Ins003_dsOutput","merge":true}]}},"onSelect":{"mappings":{"productline":"productline"},"updates":[{"visualization":"testableinttarget","instance":"Ins003","datasource":"Ins003_dsOutput","merge":true}]}},{"id":"testtable","source":{"output":"View_testtable","mappings":{"value":["productline","quarter","salesvolume","revenue"]},"id":"Ins003_dsOutput"},"label":["productline","quarter","salesvolume","revenue"],"type":"TABLE","title":"testtable","fields":[{"id":"productline","properties":{"label":"productline"}},{"id":"quarter","properties":{"label":"quarter"}},{"id":"salesvolume","properties":{"label":"salesvolume"}},{"id":"revenue","properties":{"label":"revenue"}}],"properties":{"charttype":"TABLE"},"events":{"click":{"mappings":{"quarter":"quarter"},"updates":[{"visualization":"testableinttarget","instance":"Ins003","datasource":"Ins003_dsOutput","merge":true}]}},"onSelect":{"mappings":{"quarter":"quarter"},"updates":[{"visualization":"testableinttarget","instance":"Ins003","datasource":"Ins003_dsOutput","merge":true}]}},{"id":"testableinttarget","source":{"output":"View_testableinttarget","mappings":{"value":["productline","quarter","salesvolume","revenue"]},"id":"Ins003_dsOutput"},"label":["productline","quarter","salesvolume","revenue"],"type":"TABLE","title":"testableinttarget","fields":[{"id":"productline","properties":{"label":"productline"}},{"id":"quarter","properties":{"label":"quarter"}},{"id":"salesvolume","properties":{"label":"salesvolume"}},{"id":"revenue","properties":{"label":"revenue"}}],"properties":{"charttype":"TABLE"}}],"datasources":[{"filter":["productline","quarter"],"outputs":[{"from":"Ins003_dsOutput_View_pietest","id":"View_pietest","notify":["pietest"]},{"from":"Ins003_dsOutput_View_testtable","id":"View_testtable","notify":["testtable"]},{"filter":["productline","quarter"],"from":"Ins003_dsOutput_View_testtable","id":"View_testableinttarget","notify":["testableinttarget"]}],"WUID":true,"id":"Ins003_dsOutput"}],"id":"Ins003_testmergeinteractivitydashboard","label":"testmergeinteractivitydashboard","title":"testmergeinteractivitydashboard"}]

**Comment by senthilkumar2githup** [comment]
@mlzummo [here is another example](http://viz.hpccsystems.com/master/legacyDash.html?Hostname=216.19.105.2&Port=18010&Protocol=https&Wuid=W20150717-034023&ResultName=thanse01_mergetest_Comp_Ins003_DDL).

**Comment by senthilkumar2githup** [comment]
and the workunit is [W20150717-034023](https://216.19.105.2:18010/?Wuid=W20150717-034023&Widget=WUDetailsWidget#/stub/Summary)

**Comment by mlzummo** [comment]
@senthilkumar2githup I can't access that IP Address

**Comment by senthilkumar2githup** [comment]
@mlzummo can i have ur email,so that i can share the cluster credentials?

**Comment by mlzummo** [comment]
mathew.zummo@lexisnexis.com ... I need a 10.X address though I think. I literally can't route to that IP

**Comment by senthilkumar2githup** [comment]
@mlzummo in that case dinesh will provide you with the example on 10.X address.
@dineshshetye

**Comment by drealeed** [comment]
Did the 10. address I provided above not work?
