### ISSUE TITLE
HPCC Table rendering problem when changing columns data

### ISSUE THREAD

**Issue by dunguyen-kms** [hpcc-systems/Visualization#582]
The hpcc table has problem with headers when I change columns data

- Columns is [column1, column2, column3]. You will see
![hpcc-table1](https://cloud.githubusercontent.com/assets/12228166/8743097/466de968-2c96-11e5-9a3c-f57ecd4381bb.jpg)

- Columns is [cloumn1, column4, column3, column5]. You expect
![hpcc-table2-expected](https://cloud.githubusercontent.com/assets/12228166/8743122/9cfaf104-2c96-11e5-87a7-41c38c3be7c3.jpg)
But you will see
![hpcc-table2](https://cloud.githubusercontent.com/assets/12228166/8743271/75217dc8-2c97-11e5-975d-d35861e6e0ef.jpg)

The column order has problem when you re-render table again and new columns have some old existing column.

**Comment by mlzummo** [comment]
tableWidget
    .columns([])
    .data([])
    .render()
    .columns(newCols)
    .data(newData)
    .render()
;

is the current work around for that

**Comment by dunguyen-kms** [comment]
@mlzummo - b/c of performance, I delay the render() function by using setTimeOut method when the data or columns change. So this workaround does NOT work in my case

**Comment by mlzummo** [comment]
@dunguyen-kms can you provide me a link to where i can run/view the code your using?

**Comment by dunguyen-kms** [comment]
@mlzummo I actually want to show you those lines of code. But this is an internal project so I can't.
I wrap the HPCC table to an Angular directive. And I also use setTimeOut to delay rendering whenever there's something change in columns and data. That's the reason why I can't use the workaround in this case
