### ISSUE TITLE
Not sure if table sorting is working 100%

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#585]
![image](https://cloud.githubusercontent.com/assets/1057527/8778221/87afb8d0-2eca-11e5-88da-a97dee0401f1.png)

**Comment by drealeed** [comment]
Looks like it's sorting alphanumerically instead of numerically. Which I would actually expect, since the ddl doesn't contain any info on the type of field. Does sorting differ by field type? Does it look somewhere in the ddl for the field type? If not can I suggest adding it here:

"fields": [
                    {
                        "id": "quantityinstock",
                        "properties": {
                            "type":"integer",
                            "label": "quantityinstock"
                        }
                    },
                    {
                        "id": "buyprice",
                        "properties": {
                            "type":"real",
                            "label": "buyprice"
                        }
                    },
                    {
                        "id": "productcode",
                        "properties": {
                            "type":"string",
                            "label": "productcode"
                        }
                    },
                    {
                        "id": "productline",
                        "properties": {
                            "type":"string",
                            "label": "productline"
                        }
                    },
                    {
                        "id": "productdescription",
                        "properties": {
                            "type":"string",
                            "label": "productdescription"
                        }
                    }

**Comment by GordonSmith** [comment]
@drealeed I consider the fact ESP/Hipie returns numerics as strings a HIPIE/ESP issue.  But I am happy to use the field type to force a conversion.
