### ISSUE TITLE
Thor based visualizations with fixed length strings

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#588]
If you have a thor based (WUID) based visualization that has a field of String3 and this field has mostly two digit codes in it then the value you get is padded.  So for String3 State; you will get " GA" not "GA" and thus it will not get visualized correctly on choropleth (and maybe others).  Suggested fix.. trim leading (and maybe trailing) spaces from the value.  There isn't a way to do the trim in thor or hipie.

**Comment by mlzummo** [comment]
@jchambers-ln can you provide a HipieRoxie full URL example of the problem, I can then use that url and pass it to my local copy of the marshallerand make the necessary modifications for testing.

**Comment by dineshshetye** [comment]
@mlzummo Below is the URL that demonstrates this issue

http://rawgit.com/mlzummo/Visualization/GH-590-FORM_DDL_DEFAULT_W_CB/demos/marshaller/index.html?Hostname=10.173.147.1&Port=8010&Protocol=http&Wuid=W20150723-183400&ResultName=shetyedv_dash072304_Comp_Ins075_DDL
