### ISSUE TITLE
Feature Request: Add support for render callback @ future date

### ISSUE THREAD

**Issue by mzummo** [hpcc-systems/Visualization#593]
widget.renderCallback = function() { //dostuff };
surface.contents(widget);
surface.render();

the call to surface/grid etc will eventually call the widgets render callback;
 render will check to see if renderCallback is not undefined

**Comment by GordonSmith** [comment]
render already supports callbacks:  ```widget.render(function(...) {...});```

**Comment by mlzummo** [comment]
yes but this allows support for calling a callback on every iteration of
render or loading the callback into a widget before it becomes part of a
surface or a grid object which ultimately calls render, take a look at how
i use it in the example pull request

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
