### ISSUE TITLE
xAxisTitle and yAxisTitle are not being displayed.

### ISSUE THREAD

**Issue by dineshshetye** [hpcc-systems/Visualization#598]
xAxisTitle and yAxisTitle are not being displayed. This issue can be seen on the dermatology test page for charts having axes.

**Comment by mlzummo** [comment]
@dineshshetye Have you tried setting these values before render also what charts are having this issue?

**Comment by dineshshetye** [comment]
Does not work for C3 charts. It works for other types (D3, Google, Am).

**Comment by mlzummo** [comment]
the way c3 was implimented those values can only be set before initial render:

See the below link you will see that the config object is in .enter() (called only on intial loading of the widget)
https://github.com/hpcc-systems/Visualization/blob/master/src/c3chart/CommonND.js#L89

**Comment by dineshshetye** [comment]
Thanks @mlzummo I will close this issue.
