### ISSUE TITLE
Create/enable legend for AmCharts

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#606]

**Comment by GordonSmith** [comment]
Should use:  GH-578

**Comment by mlzummo** [comment]
@jbrundage can i see an example of your legend working with c3/google/HPCC scatter chart?

**Comment by jbrundage** [comment]
Here it is with the MegaChart:
https://rawgit.com/jbrundage/Visualization/LEGEND_MEGA_CHART/demos/dermatology.html?src/chart/MultiChart&showLegend=true

**Comment by mlzummo** [comment]
going to use MEGACHART instead
