### ISSUE TITLE
Issue selecting on a graph

### ISSUE THREAD

**Issue by drealeed** [hpcc-systems/Visualization#609]
I have a dashboard with a table that updates a graph. The graph also updates itself.

Clicking on "Donald Byr" in the table updates the graph with the info for Donald Byr + child nodes. The ajax callback to roxie is http://10.173.147.1:8002/WsEcl/submit/query/roxie/leeddx_issue_343_defaultuid.Ins001_Service/json?jsonp=jsonp_callback_485325&refresh=false&name_changed=true&name=Donald%20Byr 

But clicking on the Donald Byr node in the graph updates the graph with no data. The ajax callback is http://10.173.147.1:8002/WsEcl/submit/query/roxie/leeddx_issue_343_defaultuid.Ins001_Service/json?jsonp=jsonp_callback_103891&refresh=false&name_changed=true&name= 

Dashboard url: http://rawgit.com/GordonSmith/Visualization/master/demos/marshaller/index.html?Hostname=10.173.147.1&Port=8010&Protocol=http&Wuid=W20150729-134314&ResultName=leeddx_issue_343_defaultuid_Comp_Ins001_DDL

**Comment by GordonSmith** [comment]
@drealeed Is this still an issue - or can I close and reopen as needed?

**Comment by drealeed** [comment]
This is still happening against the 1.10.0-rc6:
http://rawgit.com/hpcc-systems/Visualization/v1.10.0-rc6/demos/marshaller/index.html?Hostname=10.173.147.1&Port=8010&Protocol=http&Wuid=W20150729-134314&ResultName=leeddx_issue_343_defaultuid_Comp_Ins001_DDL

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
