### ISSUE TITLE
Support for Zoom in via brushes

### ISSUE THREAD

**Issue by arjunachala** [hpcc-systems/Visualization#611]
![image](https://cloud.githubusercontent.com/assets/999180/8967834/6fb6624e-3607-11e5-9d36-0f722e337244.png)

**Comment by mlzummo** [comment]
also in addition possibly have events drive changes in publish params to use for example the slider as a "zoom brush" ... possible changes in marshaller to do this?

**Comment by GordonSmith** [comment]
FYI the C3 charts support this already via "subchart(true)":  http://rawgit.com/GordonSmith/Visualization/DERM_PARAM/demos/dermatology.html?src/c3chart/Line&subchart=1

**Comment by arjunachala** [comment]
Ah! Very good.

@mlzummo @jbrundage Can we add the subchart(true) support to the AM charts?

**Comment by GordonSmith** [comment]
@mlzummo I am marking this as 1.6.0 as I think its a simple switch for amCharts?

**Comment by mlzummo** [comment]
@GordonSmith 1.12 or 2.X feature

**Comment by gopala-rudraraju** [comment]
The brush zoom and slide feature works great. Is it possible to use the same brush for filtering?
I mean, the dependent widgets should be filtered on the chosen brushing. Take a look at the following viz by github. I would love to see this on all possible types of widgets(line, bar, scatter, bubble  etc).
https://github.com/hpcc-systems/Visualization/graphs/contributors?from=2014-10-21&to=2015-03-11&type=c

**Comment by GordonSmith** [comment]
For DSP/Hipie that is a work in progress (adding support for multi-selection + range).  In hand coded dashboards its available now:  http://rawgit.com/hpcc-systems/Visualization/master/demos/dermatology.html?src/chart/Line.timeX&interpolate=linear&interpolateFill=true&selectionMode=true&xAxisType=time&xAxisTypeTimePattern=%25Y-%25m-%25dT%25H%3A%25M%3A%25S&xAxisOverlapMode=stagger&xAxisDomainPadding=0&yAxisType=linear

Also note that the HPCC charts now support this zoom feature:
http://rawgit.com/hpcc-systems/Visualization/master/demos/dermatology.html?src/chart/Column.timeX&xAxisType=time&xAxisTypeTimePattern=%25Y-%25m-%25dT%25H%3A%25M%3A%25S&xAxisOverlapMode=stagger&xAxisDomainPadding=0&xAxisFocus=true&yAxisType=linear
http://rawgit.com/hpcc-systems/Visualization/master/demos/dermatology.html?src/chart/HexBin&xAxisType=linear&xAxisOverlapMode=stagger&xAxisDomainPadding=0&xAxisFocus=true&yAxisType=linear

**Comment by GordonSmith** [comment]
HPCC Charts support this now.
