### ISSUE TITLE
form deserialization not working as expected

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#614]
the form child widgets (inputs) deserialization does not work as expected, child widget id's in  this.inputs() does not match whats on page. (however this is not the case in dermatology)

**Comment by mlzummo** [comment]
with DDL URL and persisted marshaller

**Comment by GordonSmith** [comment]
@mlzummo Is there an example I can work with?

**Comment by mlzummo** [comment]
@GordonSmith this was actually part of a larger issue which has a PR against your fork

**Comment by GordonSmith** [comment]
Can you reference it here?

**Comment by mlzummo** [comment]
@GordonSmith https://github.com/GordonSmith/Visualization/pull/30

**Comment by GordonSmith** [comment]
@mlzummo I have just re-tested this and I believe it is now working as expected - please re-open if you can reproduce.
