### ISSUE TITLE
comms (form) ... auto submit by grabbing default data

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#626]

**Comment by GordonSmith** [comment]
The concept is to check for default values assigned to forms and use those as the initial call - it still doesn't feel like the correct fix...

**Comment by GordonSmith** [comment]
@mlzummo We need to discuss your current implementation as it is now in use by clients.

**Comment by GordonSmith** [comment]
@mlzummo - this is going to be implemented within DSP so am closing here - reopen if I am mistaken
