### ISSUE TITLE
Refactor surfaces such that there is no more separate resizeSurface & surface (combine)

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#634]

**Comment by GordonSmith** [comment]
Simplest way to do that is to rename Surface to "__SurfacePrivate" and rename ResizeSurface to Surface.

**Comment by mlzummo** [comment]
@GordonSmith ... is this something we can move forward with?

**Comment by GordonSmith** [comment]
Closing as this would break comparability
