### ISSUE TITLE
user friendly dermatology setting per widget

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#636]
We need a feature to allow an optional button to be enabled on each widget that allows the user to customize the settings for that widget.  I lean toward a pop out menu however any approach that is user friendly is good for me.

**Comment by GordonSmith** [comment]
@jchambers-ln I am leaning towards filtering the existing "propertyEditor list" based on selection of widgets in the grid.  See:  GH-662.
@jbrundage Once GH-662 is complete, you can use that selection to determine what is shown in the property editor (including multi select).

**Comment by jbrundage** [comment]
@GordonSmith Has this been resolved with #776?

**Comment by GordonSmith** [comment]
Closing and nagging about you not adding "fixes GH-776" to your commit msg.
