### ISSUE TITLE
Ability to deserialize _some_ properties into a _existing_ widget

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#649]
Need to be able to selectively deserialize properties into an existing widget.

**Comment by mlzummo** [comment]
@GordonSmith This already solved?

**Comment by GordonSmith** [comment]
@jbrundage Did your fix get merged?

**Comment by jbrundage** [comment]
@GordonSmith I'm not sure of a way to deserialize properties into an existing widget other than applying a new **window.__hpcc_theme**. Is that the fix you're referring to?

**Comment by GordonSmith** [comment]
That ability does exist - but there is no filter option:  https://github.com/hpcc-systems/Visualization/blob/master/src/other/Persist.js#L197-L240
(deserializeFromObject means deserialize from a persist state object)

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
