### ISSUE TITLE
Zipcode projection MAP -> https://gist.github.com/jefffriesen/6892860

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#661]
https://gist.github.com/jefffriesen/6892860

**Comment by GordonSmith** [comment]
FYI the only reason we haven't included zips is its too heavy to display them all (counties is bad enough) on typical hardware.

**Comment by mlzummo** [comment]
what about rendering a map with webgl?

**Comment by mlzummo** [comment]
@GordonSmith 

http://bl.ocks.org/migurski/5024953

**Comment by GordonSmith** [comment]
Its better than google maps?

**Comment by mlzummo** [comment]
http://pathgl.com/ ?

**Comment by mlzummo** [comment]
@GordonSmith 
we can support zoom level GEOJSON data swapping such that on a certain zoom level where only a state would be visible we can then load in the zip code level data?

got the idea from here:
http://stackoverflow.com/questions/19825574/leaflet-switch-geojson-based-on-zoom-level

**Comment by GordonSmith** [comment]
With the TopoJSONChoropleth we can load zip codes on a per state basis (if we want).
