### ISSUE TITLE
Amchart Polar causes PhantomJS to crash

### ISSUE THREAD

**Issue by anmoljagetia** [hpcc-systems/Visualization#664]
Amchart Polar causes PhantomJS to crash when creating an instance of it.

All other widgets can be instantiated and loaded for testing. A few other widgets also have the problem of not having sufficient properties to run it using the *default* setting of the widget, but none of them could cause PhantomJS to crash. There are a few dump files, from PhantomJS, that can be found [here](http://ge.tt/5PBwSrL2?c).

The code that I am using to run the tests is :

```JavaScript
            describe('Creating instances of the widgets', function () {
                widgets.forEach(function (path) {
                    it(path, function (done) {
                        require([path], function (Widget) {
                            var testObject = new Widget();
                            if (typeof testObject.testData === "function") {
                                testObject
                                    .target("testWidget")
                                    .testData()
                                    .render()
                                ;
                            } else {
                                testObject
                                    .target("testWidget")
                                    .render()
                                ;
                            }
                            true.should.equal(typeof testObject === "object");
                            done();
                        });
                    });
                });
            });
```

**Comment by mlzummo** [comment]
@anmoljagetia your link is blocked here ... also could you provide a branch i can clone locally to reproduce this error?

**Comment by anmoljagetia** [comment]
@mlzummo I think Gordon resolved it in his PR, by increasing the timeout. I am also not able to reproduce this anymore.

**Comment by mlzummo** [comment]
@anmoljagetia must be, when you get the chance or are further along with it can you send some links of phantomJS rendering some charts?

**Comment by anmoljagetia** [comment]
I also found out that it could be due to some exception being thrown, and the Mocha-PhantomJS interface doesn't handle it well. More information [here](http://stackoverflow.com/questions/26882155/script-error-0-when-trying-to-run-async-test-in-mocha-phantomjs).

I am presently not working on tests for charts, but it would be really *interesting* to see PhantomJS rendering some charts.

**Comment by mlzummo** [comment]
@anmoljagetia do you have an IM i can reach you at?

**Comment by anmoljagetia** [comment]
@mlzummo I am anmoljagetia@gmail.com on Hangouts (Gordon and I usually use this), and I am anmoljagetia on Skype. I am also available on Gitter.

**Comment by mlzummo** [comment]
@GordonSmith Resolved Please Close
