### ISSUE TITLE
Non AMD pages now broken.

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#680]
The non-amd test page broke with the following changes:
https://github.com/hpcc-systems/Visualization/commit/bded18296cd343c9cec4ea1bd8ec05e0e571089f

I think the fix is to remove the ```// jshint ignore:line``` and change ```g_defaultSerials``` to ```window.g_defaultSerials```

**Comment by mlzummo** [comment]
fixed via GH-680
