### ISSUE TITLE
Axes title not showing up after it changes.

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#693]

**Comment by GordonSmith** [comment]
@dineshshetye Is this what you are referring to:
![image](https://cloud.githubusercontent.com/assets/966863/9220735/86d2431e-40dc-11e5-9421-2216c3ffac85.png)

**Comment by dineshshetye** [comment]
Yes that also will work. Maybe having the labels at the center of the axes will look better.

![image](https://cloud.githubusercontent.com/assets/1731313/9227123/fd3c4cea-40df-11e5-9b1e-8bd7252ca1c0.png)

**Comment by mlzummo** [comment]
@GordonSmith believe this one is fixed

**Comment by GordonSmith** [comment]
Its part of the mega chart work which is waiting on the legend centering issue.

**Comment by GordonSmith** [comment]
Resolved
