### ISSUE TITLE
Provide easily accessible, comprehensive list of charttype values

### ISSUE THREAD

**Issue by drealeed** [hpcc-systems/Visualization#698]
Currently the values allowed in the ddl for charttype are listed in HIPIEDDL.js and MultiChart.js, It would be very useful if there were some function in the marshaller and/or list on the dermatology test page that includes the entire list of allowable charttype values so that plugin developers, the dashboard app  etc. could check it to get the latest list of available charts.

**Comment by GordonSmith** [comment]
Do you want the entire list of known widgets that are available?  I would suggest augmenting the following list:  https://github.com/hpcc-systems/Visualization/blob/master/test/widgets.js with their official "persist" class names (chart_Column, amchart_Area, etc.)  Being in unit tests it will always be correct.

**Comment by mlzummo** [comment]
@mlzummo @GordonSmith This should be merged into documentation

**Comment by GordonSmith** [comment]
It would be easy to create a web page that listed them?

**Comment by mlzummo** [comment]
im going to be doing some work with our docs with mkdocs https://github.com/mkdocs/mkdocs
which will also go up on the wiki as well ... so i will add this in there when i start work on this when i get back

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.

**Comment by jchambers-ln** [comment]
Still a useful concept... but as 2.0 moves forward less important.
