### ISSUE TITLE
Error when localStorage is not primed

### ISSUE THREAD

**Issue by buunguyen** [hpcc-systems/Visualization#700]
This [line](https://github.com/mlzummo/Visualization/blob/d8a10824a78a6da7506163c5c8854e4090fbca29/src/other/ThemeEditor.js#L28) throws error if `localStorage.themeEditorThemes` is undefined. So is this line [https://github.com/mlzummo/Visualization/blob/d8a10824a78a6da7506163c5c8854e4090fbca29/src/other/ThemeEditor.js#L34].

Per discussion with @jbrundage, will submit PR to handle the case when those values are undefined.

**Comment by mlzummo** [comment]
@buunguyen my latest pr which includes another fix to amcharts IMG path handles this already let me know if its ok or if i should change it?

**Comment by buunguyen** [comment]
Great. If you already fix it then I won't submit another PR. Can you link that PR to close this issue?

**Comment by GordonSmith** [comment]
@buunguyen Is that ok - I am not sure if you want this in master or 1.4.4
