### ISSUE TITLE
how should a bubble chart work in relation to its testData? in linear and ordinal mode?

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#701]

**Comment by GordonSmith** [comment]
linearMode and ordinalMode should have different sets of testData - if you look at xyAxis it has several different testData sets (same forl chart/Column)

**Comment by mlzummo** [comment]
@GordonSmith ... i am adding ordinal and linear to amcharts, and i'd like to see if i can actually combine the scatter and the bubble... however for the ND data of ordinal mode im wondering how that should be interpreted for bubble size? ... in linear i just add a new column

**Comment by GordonSmith** [comment]
It might need a new data shape (bubble)
