### ISSUE TITLE
2d chart mode shouldn't include nd chart types

### ISSUE THREAD

**Issue by buunguyen** [hpcc-systems/Visualization#703]
If chart mode of MultiChartSurface is set to 2D, it will list both 2D and ND chart types.

**Comment by GordonSmith** [comment]
Which is correct as 2D data will display fine in NDCharts (the opposite is not true).

**Comment by buunguyen** [comment]
Doesn't that mean ND mode should include 2D charts but not the other way around (as the current code does)?

**Comment by GordonSmith** [comment]
No 2D data can be displayed in the ND Charts, but ND Data cannot be displayed in 2D Charts, example:
IOW How would you display this info in http://rawgit.com/hpcc-systems/Visualization/master/demos/dermatology.html?src/chart/Column in a Pie chart?

**Comment by buunguyen** [comment]
I understand that but thought it means the code should do the opposite, i.e. ND mode will include charts of 2D and ND while 2D mode only include charts of 2D. I guess I don't know the context in which `mode` is used. If it's correct then it's fine, I'll close this pr.

**Comment by GordonSmith** [comment]
It didn't help that it was wrong for a good while!  I read it as "show me the charts that are compatible with the given data shape."
