### ISSUE TITLE
Table pagination is broken in 1.4.2

### ISSUE THREAD

**Issue by buunguyen** [hpcc-systems/Visualization#705]
When `pagination` is set to true, the widget throws this error

```
Uncaught TypeError: Cannot read property 'getComputedStyle' of null
```

**Comment by mlzummo** [comment]
I can't replicate this:

http://rawgit.com/hpcc-systems/Visualization/v1.4.2/demos/dermatology.html?src/other/Table

@buunguyen Can you provide a link that demonstrates this issue?

**Comment by buunguyen** [comment]
@mlzummo try edit demos/test.html, add pagination(true) to table:

```js
  new Table()
        .target("table")
        .testData()
        .pagination(true) // add this
        .render()
```

**Comment by GordonSmith** [comment]
FYI You can emulate that with the following URL:  http://rawgit.com/hpcc-systems/Visualization/master/demos/dermatology.html?src/other/Table&pagination=1

**Comment by buunguyen** [comment]
@mlzummo I've just tested, the fix works. Regarding the quality of code change, @GordonSmith please help review.

@GordonSmith nice tip!
