### ISSUE TITLE
Some publish params can't be reset to null

### ISSUE THREAD

**Issue by jbrundage** [hpcc-systems/Visualization#708]
Once a publish param has been set with a valid value... if you **_reset** it or set it to **null** again... it will fail to revert back to its initial state (ex: *surfaceBorderWidth*)... **null** will be interpreted differently based on how the publish parameter is implemented.

This is causing issues when switching between Themes.

Reproducing the issue:
1. https://rawgit.com/hpcc-systems/Visualization/master/demos/dermatology.html?src/layout/Grid
2. Run this test in the console:
   * console.log(currWidget.content()[0].surfaceBorderWidth())
      * You'll see that it's *null* though the border is currently 1px wide (based on its Surface.css style)
   * currWidget.content()[0].surfaceBorderWidth(5).render()
      * You'll see the border become 5px wide
   * currWidget.content()[0].surfaceBorderWidth(null).render()
      * You'll see the border become 0px wide instead of reverting to the 1px css style

**Comment by GordonSmith** [comment]
I believe https://github.com/hpcc-systems/Visualization/pull/728 will fix this issue - but some widgets need to check for "_modified" when setting the style (if they add "px" to the value for example)
