### ISSUE TITLE
descending sort not working

### ISSUE THREAD

**Issue by drealeed** [hpcc-systems/Visualization#722]
I have a table sorted by st descending, then sum_seq descending, then base_count descending. The st field doesn't seem to be sorted descending.

Example:
http://rawgit.com/GordonSmith/Visualization/master/demos/marshaller/index.html?Hostname=10.173.147.1&Port=8010&Protocol=http&Wuid=W20150814-165200&ResultName=leeddx_issue_1000_sort_fieldreference_Comp_Ins002_DDL

DDL:

     [
      {
        "visualizations": [
            {
                "id": "TableReferenceBoth",
                "source": {
                    "output": "View_TableReferenceBoth",
                    "mappings": {
                        "value": [
                            "st",
                            "city",
                            "seq_SUM",
                            "Base_COUNT"
                        ]
                    },
                    "id": "Ins002_dsOutputFromInput",
                    "sort": [
                        "-st",
                        "-seq_SUM",
                        "-Base_COUNT"
                    ]
                },
                "label": [
                    "st",
                    "city",
                    "seq_SUM",
                    "Base_COUNT"
                ],
                "type": "TABLE",
                "title": "Field Reference in bq and sort, no \"INPUTS.\" specified",
                "fields": [
                    {
                        "id": "st",
                        "properties": {
                            "label": "st"
                        }
                    },
                    {
                        "id": "city",
                        "properties": {
                            "label": "city"
                        }
                    },
                    {
                        "id": "seq_SUM",
                        "properties": {
                            "label": "seq_SUM"
                        }
                    },
                    {
                        "id": "Base_COUNT",
                        "properties": {
                            "label": "Base_COUNT"
                        }
                    }
                ]
            }
        ],
        "datasources": [
            {
                "outputs": [
                    {
                        "from": "Ins002_dsOutputFromInput_View_TableReferenceBoth",
                        "id": "View_TableReferenceBoth",
                        "notify": [
                            "TableReferenceBoth"
                        ]
                    }
                ],
                "WUID": true,
                "id": "Ins002_dsOutputFromInput"
            }
        ],
        "id": "Ins002_SortPassthroughOutput",
        "label": "SortPassthroughOutput",
        "title": "Sort Passthrough Output"
        }
     ]

**Comment by mlzummo** [comment]
seems like "i" is not incriminating ... i have no idea why just yet

https://github.com/hpcc-systems/Visualization/blob/master/src/marshaller/HipieDDL.js#L337

**Comment by mlzummo** [comment]
actually line 354 is causing it to return before it can get to the next iteration
