### ISSUE TITLE
Child Dataset support for table and other widgets

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#724]
https://github.com/hpcc-systems/DSP/issues/259

Now that HIPIE supports child datasets one may need to display this as a table and/or other widget.  We need to make sure Visualization supports this.

**Comment by GordonSmith** [comment]
Marshaller support still needed.  Is dependent on:  https://github.com/hpcc-systems/HIPIE/issues/1228

**Comment by jchambers-ln** [comment]
Required by https://github.com/hpcc-systems/DSR/issues/29
