### ISSUE TITLE
cascading dermatology settings

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#725]
Is it possible to load a generic dermatology that has all data points, followed by a more specific one that only has certain data points in a way that they merge together? 

Specific requirement is,
Create a dashboard with all the chart sizes, labels, titles
Extend the dematology associated with taht dashboard related to a GCID that changes title bar colors multiple times.

**Comment by GordonSmith** [comment]
Not as it stands, but it would be trivial for you to merge two dermatology persist string together (just convert to objects and walk the new one overwriting the older one as you go)?

**Comment by jchambers-ln** [comment]
Ok Thanks I'll update the underlying issue.
