### ISSUE TITLE
Show a DDL containing multiple visualizations as a set of tabbed panels

### ISSUE THREAD

**Issue by drealeed** [hpcc-systems/Visualization#739]
One dashboard per tab, the dashboard title defined as the title of the tab.

The visualization set labeled as "primary":true would be shown as the default open tab. If no visualizations are listed as primary, the first visualization set in the list would be shown by default.

Example roxie-based dashboard with multiple dashboards:
http://viz.hpccsystems.com/v1.2.2/apps/legacyDash.html?Hostname=10.173.147.1&Port=8010&Protocol=http&Wuid=W20150811-093946&ResultName=leeddx_vizvalidation_Comp_Ins002_DDL

Wuid-based:
http://viz.hpccsystems.com/v1.2.2/apps/legacyDash.html?Hostname=10.173.147.1&Port=8010&Protocol=http&Wuid=W20150811-093946&ResultName=leeddx_vizvalidation_Comp_Ins003_DDL

Heads up: an upcoming feature is the ability for onClick on a widget to update a widget in another dashboard. In this case, the desired behaviour would be to automatically switch to the other dashboard's tab, if the only widgets being updated were on that dashboard. I don't have an example of that yet.

**Comment by GordonSmith** [comment]
Resolved with:  GH-866
