### ISSUE TITLE
Zebra Table

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#743]

**Comment by mlzummo** [comment]
@GordonSmith @dineshshetye is it ok to use CSS3 selector to do this

tr:nth-child(even) {
  background-color: red;
}
tr:nth-child(odd) {
  background-color: white;
}

**Comment by GordonSmith** [comment]
I would have thought that would be the correct solution - with the possible "publish" option to override locally (you will need to do a ```if (idx%2) ...``` type calculation for the row.

**Comment by GordonSmith** [comment]
Resolved
