### ISSUE TITLE
Property Editor (Widget Click Drill Down) (possible additional popup)

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#744]

**Comment by GordonSmith** [comment]
@mlzummo Can you provide more information?

**Comment by mlzummo** [comment]
@GordonSmith @jbrundage this is the issue where we need to be able to click on a widget and have the property editor on the right hand side only show the properties (PP's) for that particular widget that was selected. (also @jbrundage do you have the branch still where there is a popup with editable props that is shown when a widget is selected as opposed to the static positioned property editor)

**Comment by jbrundage** [comment]
As of 1.6.0 the PropertyEditor will filter out all non-selected cells in a Grid (if at least one cell is selected) #796

**Comment by jbrundage** [comment]
Yes, here's the branch where I added "propertyMode" to the Grid (allowing the user to click a Grid Cell to display that Cell's params in a modal):
https://rawgit.com/jbrundage/Visualization/PropertyEditor_Enhancements/demos/dermatology.html?src/layout/Grid&propertyMode=true
