### ISSUE TITLE
Ability show what widget will update another and filter fields

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#747]

**Comment by jbrundage** [comment]
What is this?

From the title it seems like the goal is to somehow visually indicate which widgets will update other widgets? Any thoughts on how this should be accomplished?

**Comment by GordonSmith** [comment]
Its only of interest in the HTML Marshaller and I can expose a method which will tell you - but I suspect when a user moves over one widget which updates others, the others should get highlighted (not dissimilar to some of the drag and drop highlighting?

**Comment by GordonSmith** [comment]
Further - it might end up being related to how we may want to highlight items in the legend and the chart as well?

**Comment by jbrundage** [comment]
So I'll add an onHover method to layout/Cell.js like this:
```javascript
Cell.prototype.onHoverEnter = function (widgetArr){
    for(var i in widgetArr){
        this.createOverlayUpdateIndicator(widgetArr[i]);
    }
}
Cell.prototype.onHoverExit = function (widgetArr){
    for(var i in widgetArr){
        this.removeOverlayUpdateIndicator(widgetArr[i]);
    }
}
```
And I'll call **onHover(...with the response from your exposed method...)**. Does this make sense or am I misunderstanding?

**Comment by jbrundage** [comment]
@GordonSmith Do you have any input regarding this enhancement?

**Comment by GordonSmith** [comment]
Its only going to be used in marshaller/HTML and I will need to add a method that will tell you the list to highlight...

**Comment by jbrundage** [comment]
In #947 I added an 'array' publish param that will highlight dom elements by ID. 

To be used like this:
Grid.content()[0].indicateTheseIds(*["_w10","_w15","_w27"]*)

Can your method simply return the dom IDs of the widgets to highlight?

**Comment by GordonSmith** [comment]
Yes it can.
