### ISSUE TITLE
Add second Y Axis to HPCC Charts

### ISSUE THREAD

**Issue by mzummo** [hpcc-systems/Visualization#748]

**Comment by GordonSmith** [comment]
@mounicarachakonda @jpellock 
I would break it down to the following steps (and issue a PR for review for each step):
* Add second "valueAxis" and initialize it with the same values as the first valueAxis (but display it on the other side of the chart).
* Add all the publishProperties for the second axis.
* Add a mechanism for specifying which columns go to valueAxis1 and which go to valueAxis2
* Ensure the x/y pixel calculations go via the correct axis.

**Comment by GordonSmith** [comment]
Expired - please reopen if needed.
