### ISSUE TITLE
Add second Y Axis to Google Charts

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#749]

**Comment by dtsnell4** [comment]
@GordonSmith Only the latest version of Google Materials Charts support the multi y-axes. (you can in fact have more than two).  I believe I remember hearing we wanted to upgrade to Material anyway, so I suppose this is a good time.  This also applies to Line and Scatter charts.  The rest of the charts do not support multi axes.

As part of this new version, they have done away with the column chart, and simply use the bar chart with the orientation set to horizontal or vertical, just as we do. 

Does that mean that google/Column.js should go away?

**Comment by mlzummo** [comment]
@dtsnell4 @GordonSmith  yes, ... i think we need to standardize on using 1 or the other though cause in amcharts im using Bar when it can really be named column ... perhaps we should standardize on Column (meaning you would remove bar) ?
