### ISSUE TITLE
Add second Y Axis to AmCharts

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#750]

**Comment by mlzummo** [comment]
@GordonSmith need a datashape to go off of

**Comment by GordonSmith** [comment]
The INDChart shape is fine - need a way to tell the chart "which" columns should use the second Y axis (typically you use this if you have two columns based on a different scales (col a could be pct and col b could be $$)

**Comment by mlzummo** [comment]
@GordonSmith the grouped column chart uses all these data points already ...  im not sure how we would use a second yaxis on a grouped column chart off the top ... but if its possible then we need to add more to the data structure

**Comment by mlzummo** [comment]
@GordonSmith also should we have a publish param that gets enabled or disabled or do we read the data shape to determine?

**Comment by GordonSmith** [comment]
No your mixing up the widget data and the data you feed into your am chart...
