### ISSUE TITLE
Multi Series Charts (line and bar)

### ISSUE THREAD

**Issue by mzummo** [hpcc-systems/Visualization#751]

**Comment by GordonSmith** [comment]
@mlzummo Can we get more information for this?

**Comment by dineshshetye** [comment]
This is our long term plan:

![image](https://cloud.githubusercontent.com/assets/1731313/9801126/333855bc-57df-11e5-9645-8f5301c7f416.png)

**Comment by jchambers-ln** [comment]
Would be helpful to extend this to combining several charts such as line and area etc.

**Comment by GordonSmith** [comment]
Resolved in 2.0
