### ISSUE TITLE
Property Editor Filter on Private, Advanced etc.

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#753]
In an effor to improve the whole property editor experience, we should hide private/advanced by default and optionally let the user show them.

For Cell / Surface can we move the "widget" property up higher so that its near the top of the list of properties and mark all the row/rowSpan properties as private.

**Comment by GordonSmith** [comment]
For the UI @mlzummo is going to be doing a "Group of checkboxes" control.

**Comment by jbrundage** [comment]
@GordonSmith Property Editor does omit "Private" and "Advanced" publish parameters as of #657

**Comment by GordonSmith** [comment]
I think we can mark this fixed now.  (except I broke it in 1.6.0) will close once I fix my regression,.
