### ISSUE TITLE
Add second Y Axis to C3

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#766]

**Comment by jbrundage** [comment]
@mlzummo @dtsnell4 @GordonSmith Do we have a test/xxxxxxFactory example of the standard/expected columns+data format that would result in a chart with two Y-Axes?

**Comment by GordonSmith** [comment]
Not that I know off...

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
