### ISSUE TITLE
Table pagination bugs in 1.4.6

### ISSUE THREAD

**Issue by buunguyen** [hpcc-systems/Visualization#771]
There are two separate bugs although could be related:

* Items-per-page isn't honored
* After changing page, the row count is automatically changed

Demo page: https://github.com/buunguyen/Visualization/commit/9f0eedeab62b32c81c95c284e69e0ec36ad0c1bc.

**Comment by GordonSmith** [comment]
Resolved by:  https://github.com/hpcc-systems/Visualization/pull/804
