### ISSUE TITLE
HIPIE Interaction

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#790]
Big topic - basically need to improve the whole HIPIE->DDL->Viz lifecycle.  In a lot of cases, just make it work.

**Comment by mlzummo** [comment]
@GordonSmith Can you provide some examples and your thought process around this?

**Comment by dabayliss** [comment]
@GordonSmith once you have defined what you mean - please keep me in this loop. There are a LOT of server side performance issues in here

**Comment by GordonSmith** [comment]
This was a precursor to our Viz II discussions and is effectively a duplicate of https://github.com/hpcc-systems/Visualization/issues/1623:
* Push mappings into dermatology
* HIPIE ability to read persist strings.
