### ISSUE TITLE
MultiChart Surface: C3 chart Legend overlaps the surface menu while switching between charts in Firefox browser

### ISSUE THREAD

**Issue by gnansu** [hpcc-systems/Visualization#806]
The normal behavior of multichart surface is when we switch charts it blanks the surface (hides the chart and the legend) and once the new chart is selected, it renders the new chart. I'm seeing a different behavior in firefox browser.  If the current chart is any C3 chart (line, column, bar) and when I click the surface menu, the legend, the chart axis does not hide. Hence the legend overlaps the menu. 

This hinders the user from switching from C3 charts to any other chart.

When the current chart is any google chart, this does not happen.  Everything is fine while using Google Chrome.

**Comment by gnansu** [comment]
Any updates on this?

**Comment by mlzummo** [comment]
@GordonSmith Can we hack this so that showLegend(false) is set during menu render?

**Comment by mlzummo** [comment]
perhaps we can suppose a universal param that fires on the underlying widget for such kinds of events

**Comment by GordonSmith** [comment]
The showLegend(false) if its a C3 chart is what I was going to suggest doing.

**Comment by gnansu** [comment]
@mlzummo @GordonSmith thanks

**Comment by GordonSmith** [comment]
@mlzummo I am just testing this in master now and it seems that my fix does in fact work (the C3 legend is being hidden with the rest of the C3 chart:  
http://rawgit.com/hpcc-systems/Visualization/master/demos/dermatology.html?src/chart/MultiChartSurface&chartType=C3_COLUMN
(and turn on showLegend - then click on the menu in the surface title bar).

**Comment by mlzummo** [comment]
@GordonSmith did you test this with FireFox the issue was only present there

**Comment by GordonSmith** [comment]
Ahh yes ok that makes sense...  I notice that the C3 Axis doesn't get hidden either - gotta be a C3 issue I suspect.
