### ISSUE TITLE
Table widget doesn't display non-string content in cells

### ISSUE THREAD

**Issue by jbrundage** [hpcc-systems/Visualization#808]

**Comment by jbrundage** [comment]
This was resolved 5 days ago.

**Comment by jbrundage** [comment]
The fix is in 1.6.2:
https://github.com/hpcc-systems/Visualization/blob/candidate-1.6.2/src/other/Table.js#L311-L318

**Comment by GordonSmith** [comment]
@jbrundage This issue will be auto-closed once your commit makes it to master (IOW once I up-merge the current candidate-1.6.2)
