### ISSUE TITLE
HTML_Marshaller Uncaught Target can only be assigned once.

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#842]
HTML_Marshaller Uncaught Target can only be assigned once when opening up a second dashboard ...

**Comment by GordonSmith** [comment]
@mlzummo Is this still an issue?

**Comment by mlzummo** [comment]
@GordonSmith not since moving the HTML_Marshaller to be based on a grid as opposed to the the tab layout. I believe you are making a tabbed marshaller and im not sure if that will have the same issue
