### ISSUE TITLE
unitTest for Marshaller deserializing and click events along with it

### ISSUE THREAD

**Issue by mzummo** [hpcc-systems/Visualization#855]

**Comment by mlzummo** [comment]
@GordonSmith going to wait till we refactor the unitTests ... i cant add the new export features to amcharts until we get that done

**Comment by mlzummo** [comment]
@GordonSmith r on hold till 2.0 perhaps?

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
