### ISSUE TITLE
Fixed Header Table is "off"

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#869]
http://rawgit.com/GordonSmith/Visualization/ZN_GRAPH/demos/graph/index.html

**Comment by GordonSmith** [comment]
Closing until its ready to pull

**Comment by dtsnell4** [comment]
@GordonSmith just curious, do you want me to do a pr for this or are you taking care of it?

**Comment by GordonSmith** [comment]
@dtsnell4 Its assigned to you!

**Comment by GordonSmith** [comment]
FYI - Dan found issue in css for demo - unrelated to src folder.
