### ISSUE TITLE
Grid cells should split the class name into 2 classes

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#883]
cell__w11 should become : class="cell __w11" -< notice the space so that we can select the cell container with d3

![image](https://cloud.githubusercontent.com/assets/1057527/9693500/f6571c38-531e-11e5-85ab-d32471c6401f.png)

**Comment by mlzummo** [comment]
also noticed the grid created 2 cells with the same class "cell__w11" is that normal?

**Comment by mlzummo** [comment]
~309: add this?         rows.enter().append("div")
            .attr("class", "grid cell cell_" + this._id)
            .style("position", this.cellPosition())

**Comment by GordonSmith** [comment]
Yes its normal to have two cells with the same class like that (and it is done to prevent selectAll from selecting grids within grids) = solution is to change selectAll to ```selectAll("cell." + this.id()).data(...)```  Notice the "dot" in the selectAll, then you can have the space as needed.
