### ISSUE TITLE
ability to turn off grid lines/cell lines

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#884]

**Comment by GordonSmith** [comment]
@mlzummo I am assuming this is for the Grid (and not xyAxis?)

**Comment by mlzummo** [comment]
@GordonSmith yes

**Comment by GordonSmith** [comment]
@jbrundage Also I think the way we adjust the inner widget padding is a bit inconsistent across all the layouts (to start thinking about for a future issue)?

**Comment by jbrundage** [comment]
@GordonSmith Sounds good.

@mlzummo I'm assuming you're referring to the borders of the Grid cells?

**Comment by mlzummo** [comment]
yes
