### ISSUE TITLE
how will multiple checkbox/radio box values be returned for "events"

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#885]
right now i  am using a grid with marshaller to render multiple checkbox's and radio buttons in a form all with the same name ... having some issue's but still going to need a way to get the checkbox value such that a group of checkbox's all with check_name[] as the name will return an array of values for each one that is checked .... open to suggestions ...

**Comment by mlzummo** [comment]
had thought about redoing checkbox Input and Radio input such that multiple could be rendered and the input itself would return the value

**Comment by mlzummo** [comment]
@GordonSmith your thoughts on this please

**Comment by GordonSmith** [comment]
I would suggest doing a mock it up in plane HTML first so you know what your aiming for.
