### ISSUE TITLE
Pagination + Narrow Space

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#890]
We need some scheme where the pagination display is prevented from wrapping to a new line:
![image](https://cloud.githubusercontent.com/assets/966863/9730533/142cd5e8-560f-11e5-8392-599d6f3646d0.png)

Maybe a narrow mode which would look like:
[<<][<][[1] of 20][>][>>]

(the main issue with the wrapping is it affects the pagination calulation thus changing the page of number and is confusing to use).

**Comment by mlzummo** [comment]
@GordonSmith what about using a nowrap/css to make sure that the paginator does not wrap?

**Comment by GordonSmith** [comment]
I briefly tried that and failed miserably - but if it fixes it, its good with me.

**Comment by mlzummo** [comment]
also dont allow negative total page number count

**Comment by dtsnell4** [comment]
I'll work on this
