### ISSUE TITLE
Pagination Regression

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#895]
@jbrundage Latest theme changes removed some new pagination features.

**Comment by jbrundage** [comment]
Which pagination features were removed?

Does the problem occur here?
https://rawgit.com/hpcc-systems/Visualization/candidate-1.8.0/demos/dermatology.html?src/other/Table

**Comment by GordonSmith** [comment]
Its placement and yes - size page so you get a HScroll and you will see it...

**Comment by jbrundage** [comment]
@GordonSmith I can't replicate the issue you're talking about.

**Comment by mlzummo** [comment]
i can't either

**Comment by GordonSmith** [comment]
It only happened on the 1.8.0 branch:  http://rawgit.com/hpcc-systems/Visualization/candidate-1.8.0/demos/dermatology.html?src/other/Table&pagination=1

Resize your page until the HScroll appears - then drag it around - @mlzummo had fixed this already and then @jbrundage your theme fix for tables removed it again:
![image](https://cloud.githubusercontent.com/assets/966863/9756674/efb6078c-56d3-11e5-96f6-5d1f8e7356f6.png)

**Comment by jbrundage** [comment]
I'm still unable to experience this issue. The pagination controls don't move with the scroll-bar in my browser.
![image](https://cloud.githubusercontent.com/assets/1891935/9766285/1aa563cc-56e6-11e5-8893-16ff68672ca8.png)

**Comment by GordonSmith** [comment]
What URL Did you use for that?

**Comment by jbrundage** [comment]
The one you provided:
http://rawgit.com/hpcc-systems/Visualization/candidate-1.8.0/demos/dermatology.html?src/other/Table&pagination=1

**Comment by GordonSmith** [comment]
That because the fix got pulled:  https://github.com/hpcc-systems/Visualization/pull/896
