### ISSUE TITLE
Legend Widget:  Should Center Itself in available space.

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#900]
Primarily for legend - shrinkTofit + Center.

**Comment by jbrundage** [comment]
@GordonSmith Shouldn't the centering be handled by the individual widgets? Legend's tableDiv currently expands to the height of its container.

**Comment by GordonSmith** [comment]
@jbrundage - yes you are probably correct - I have updated this Issue accordingly!!!

**Comment by jbrundage** [comment]
@GordonSmith This is ready to be closed
