### ISSUE TITLE
Inefficient code - column filters in AMCharts can be simplified

### ISSUE THREAD

**Issue by jbrundage** [hpcc-systems/Visualization#903]

**Comment by mlzummo** [comment]
@jbrundage can you provide an example and i will refactor

**Comment by mlzummo** [comment]
also need to remove amcharts charts that are no longer separate charts

**Comment by GordonSmith** [comment]
@jbrundage Can you provide links to the code in question?

**Comment by jbrundage** [comment]
https://github.com/hpcc-systems/Visualization/blob/candidate-1.8.0/src/amchart/CommonFunnel.js#L110

https://github.com/hpcc-systems/Visualization/blob/candidate-1.8.0/src/amchart/CommonRadar.js#L174

https://github.com/hpcc-systems/Visualization/blob/candidate-1.8.0/src/amchart/CommonSerial.js#L494-L499
