### ISSUE TITLE
Column data formatting for table, how should the PP work for defining per col formats?

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#920]
should it be an array where the index corresponds with columns()?

@GordonSmith @jbrundage @dtsnell4 ...

@GordonSmith How would this work in relation to the DDL as well if at all?

**Comment by mlzummo** [comment]
same question for column alignment, also what should the default alignment be for say numbers, $, etc... i can make a function that reads the format string as well

**Comment by GordonSmith** [comment]
@mlzummo I will shortly be replacing the _columns + _data with a _db (database) - it will have the ability to set/get any properties associated with a column (now known as a "field")
