### ISSUE TITLE
build issue "css fix PR didnt work?"

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#926]
@GordonSmith 
https://travis-ci.org/hpcc-systems/Visualization/builds/80308622
https://travis-ci.org/hpcc-systems/Visualization/builds/80308350

**Comment by mlzummo** [comment]
https://travis-ci.org/hpcc-systems/Visualization/builds/80312077

**Comment by mlzummo** [comment]
https://travis-ci.org/hpcc-systems/Visualization/builds/80311109

**Comment by GordonSmith** [comment]
@mlzummo I restarted those builds...

**Comment by GordonSmith** [comment]
FYI I kicked off the master, 1.8.0, 1.6.6 and 1.6.4 builds again here:  https://github.com/hpcc-systems/Visualization/branches and only the 1.6.4 failed (which is expected).

**Comment by GordonSmith** [comment]
I think there was a tmp glitch in Travis - seems ok now in so far as the ones with errors are actual errors.
