### ISSUE TITLE
Table Widget selected row highlights is off

### ISSUE THREAD

**Issue by dtsnell4** [hpcc-systems/Visualization#936]
When showHeader is false, but fixedColumn is still true, when you click on a row to highlight/select it, the wrong fixed column row gets highlighted (one row below).

**Comment by dtsnell4** [comment]
@GordonSmith This code was also added in candidate 1.8 for the Show/Hide Fixed header issue.   https://github.com/hpcc-systems/Visualization/issues/860

**Comment by GordonSmith** [comment]
Closing resolved.
