### ISSUE TITLE
Table setting styles directly

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#937]
Does not play nice in IE.  Specifically places like:  https://github.com/hpcc-systems/Visualization/blob/master/src/other/Table.js#L434-L438

When you set a NULL like that in IE it actually uses the word null!  But when you use the d3.style() methods it removes the style when the value is null.

This is why I am seeing bad fonts here (I think):
![image](https://cloud.githubusercontent.com/assets/966863/9956035/596539f8-5ded-11e5-8ce6-94d9504f0075.png)

**Comment by dtsnell4** [comment]
@GordonSmith SHould this be for candidate-1.8.0?  This code was added to that candidate with J's PR here https://github.com/hpcc-systems/Visualization/pull/834  It doesn't exist in 1.6.x
