### ISSUE TITLE
New PropertyEditor

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#948]
1.  Select MultiChart
2.  Change ChartType 

The property editor does not update itself to show the properties for the newly select chart type.

**Comment by jbrundage** [comment]
I'll fix this right now...

**Comment by jbrundage** [comment]
@GordonSmith This is ready to be closed

**Comment by jbrundage** [comment]
@GordonSmith What needs to change about the Property Editor?
