### ISSUE TITLE
New user feedback on long responding charts

### ISSUE THREAD

**Issue by arjunachala** [hpcc-systems/Visualization#962]
It will be nice to have some visual cue that the chart is being rendered. Sometimes you click on a chart and the child chart takes a few seconds to respond. In the meantime there is no visual cue to the user that the chart is in the process of being rendered.

**Comment by mlzummo** [comment]
@arjunachala @GordonSmith  there are 2 functions that are overwritable widget.preUpdate and widget.postUpdate as well as the render(function(){}) callback that can be utilized for testing/running code when a widget is about to render and when its finished This can be handled outside the library I am not sure on Gordon's stance on something built into the library right now but DSP could use the Loading animation I've seen and plug it in.

**Comment by dtsnell4** [comment]
@GordonSmith Do you want this to be its own widget, or just build it into Widget.js to run by default?

**Comment by dtsnell4** [comment]
@GordonSmith rather common/Utility or api/ILoader of some sort?

**Comment by mlzummo** [comment]
.on("progress   on("timeout on("error    ...

**Comment by GordonSmith** [comment]
@dtsnell4 I think for any widget we should be able to show some sort of spinning "busy" image over the widget.  The following methods would be useful:
```
showBusy(boolean showHide)
pushBusy()
popBusy()
```
pushBusy would increment an internal busyCounter and show the busy image
popBusy would decrement an internal busyCounter and hide the busy image when that count hits 0

**Comment by mlzummo** [comment]
i honestly don't think this belongs in the lib, and @GordonSmith you've made it clear in the past that things like this might be best handled outside the library .. also rendering widgets is not what takes time (almost every case of long loading is due to marshaller/ or dashboard as a whole not indv. widgets or even the Hipie service itself taking time to run the query) ... also this universal spinning widget might not match the style they want in which case i can bet (becuase its already being done) that they will role there own spinners which will allow much more consistency through out there apps ... i think the focus needs to be on getting progess/error and timeout handling in the marshaller .... the rest is superfluous

**Comment by mlzummo** [comment]
i think this might be better served with an .on("progress", function() { (this would also pass the time that has lapsed) event system ... we have been talking about better event handling yet we avoid it at every step .... and i also think that this needs to be integrated into the marshaller which is where the focus needs to be atleast DSP (progrress/error and timeout handling) ... we really need to have a talk about why we might want to do this over that or vise versa

**Comment by mlzummo** [comment]
@GordonSmith what would determine when to increment the counter vs decrement it?

**Comment by GordonSmith** [comment]
There are two issues:
1.  The ability to show hide a busy indicator
2.  Showing the busy indicator for specific long running events.

This issue is more for 1 above and then we should open a new one for 2.

**Comment by mlzummo** [comment]
can't 1 be handled with a timer and render() callback? 

for your suggestion: at what interval will the increment or increment? what will cause it to decrement?

**Comment by dtsnell4** [comment]
@GordonSmith Sorry, but I am fairly confused.  I believe I can show a spinner on .enter() and remove it .postUpdate() easily enough, but what is incrementing/decrementing and when/where does it happen?

**Comment by GordonSmith** [comment]
Sometimes I may be doing 1,2, 3 or 4 lengthy "things" having the pushBusy and popBusy lets me trigger the busy image without worrying about which lengthy operations are starting / stopping etc.

**Comment by dtsnell4** [comment]
@GordonSmith ok, first question...  popBusy increments busyCounter...  should busyCounter simply be an integer that increments?  or should popBusy get passed an event, which pushes it to busyCounter which is an array that stores the events, in case you need to ref them later?  Or am I overanalyzing?

**Comment by GordonSmith** [comment]
Integer typically works fine.

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
