### ISSUE TITLE
Word Cloud Zoom

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#971]

**Comment by mlzummo** [comment]
have 2 issues so far implementing this:

1) the zoom in effect when it loads data is causing the d3 zoom bevaior  (d3.event.scale) to be out of sync on first mouse tick ... not sure how to fix...

2) cant zoom in on white space

**Comment by GordonSmith** [comment]
Look at the d3 transition events docs.

**Comment by GordonSmith** [comment]
Can youi add some details as to what the issue is?

**Comment by mlzummo** [comment]
element.transition().delay(1000).duration(750)
.attr("transform", "translate("+context._pos.x+","+context._pos.y+")scale(" + borderScale + ")") ;
 context.zoomListener.scale(borderScale).translate([context._pos.x,context._pos.y]);

**Comment by GordonSmith** [comment]
With reference to:  http://rawgit.com/hpcc-systems/Visualization/master/demos/dermatology.html?src/other/WordCloud could you add some steps to reproduce as I am no closer to understanding what the issue actually is.

**Comment by mlzummo** [comment]
word cloud zoom now works with respect to all issues i was having, and i dont see anything else wrong with it other than this: https://github.com/mlzummo/Visualization/blob/WORDCLOUD_ZOOM/src/other/WordCloud.js#L122-L124 

if you don't see an issue there, then there is none and this is ready to be pulled

**Comment by GordonSmith** [comment]
This is an issue report - and I am not "getting" what issue this is raising.

**Comment by mlzummo** [comment]
I am having to translate and scale twice ... once by using attr (with delay and duration) and a second time using the zoomlister event (to sync it) .. like i said if its not readily apparent i dont think its an issue i just think its the way it needs to be done ...

**Comment by GordonSmith** [comment]
Is your issue:  "When embedding the Word Cloud in a web page it fails to display correctly, unless I resize it twice"?

**Comment by mlzummo** [comment]
@GordonSmith can you go on chat ... (thats not the issue unless this is something you just experienced in which case i was not aware of it)
