### ISSUE TITLE
wiki download links dont work & suggestion

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#973]
http://viz.hpccsystems.com/v1.2.4/dist-amd/

doesnt work ....

also so we don't need to udpate the wiki all the time we should symlink "latest" to the latest stable release ex:

http://viz.hpccsystems.com/LATEST/dist-amd/

**Comment by GordonSmith** [comment]
1. That URL is not a download link - its an include link for pages (the download is on gitHub under releases).
2. That server is a CDN server not a web server...
