### ISSUE TITLE
hpcc column chart stacked property not rending correctly

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#974]

**Comment by mlzummo** [comment]
also the property name should be isStacked to keep consistency

**Comment by GordonSmith** [comment]
Needs to be sorted to ensure all are visible.

**Comment by GordonSmith** [comment]
HPCC Stacked is diffrerent to other stacked implementations (HPCC is more overlayed rather than stacked...

**Comment by GordonSmith** [comment]
Closing as dup of https://github.com/hpcc-systems/Visualization/issues/1424
