### ISSUE TITLE
Non-AMD order of files incorrect in demos?

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#977]
Layout needs to go before api because api/IToolTip requires AbsoluteLayout

    <meta charset="utf-8">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="//viz.hpccsystems.com/v1.6.6/dist/hpcc-viz.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>
    <script src="//cdn.rawgit.com/jeanlauliac/colorbrewer/v1.0.0/colorbrewer.js"></script>
    <script src="//viz.hpccsystems.com/v1.6.6/dist/hpcc-viz-common.js"></script>
    <script src="//viz.hpccsystems.com/v1.6.6/dist/hpcc-viz-layout.min.js"></script>
    <script src="//viz.hpccsystems.com/v1.6.6/dist/hpcc-viz-api.js"></script>
    <script src="//viz.hpccsystems.com/v1.6.6/dist/hpcc-viz-other.min.js"></script>
    <script src="//viz.hpccsystems.com/v1.6.6/dist/hpcc-viz-chart.min.js"></script>

**Comment by GordonSmith** [comment]
This list has to match the build order in the gulp file.

**Comment by GordonSmith** [comment]
@mlzummo Can you check if this is fixed with the removal of the inline tests?  If so this can probably be closed as fixed in?
