### ISSUE TITLE
2nd y-Axis (multi axis) PP's how will we handle?

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#990]
2nd y-Axis & x-Axis (multi axis) PP's (use an array or duplicate each PP that we want to apply to each axis indv.)?

**Comment by mlzummo** [comment]
also maybe we should use legend and the Axis Title Color/name to indicate what Data belongs to what Axis (since we will be using our own legend system in all the charts) and we can specify a universal way of declaring Axis Labels and Colors ....

**Comment by mlzummo** [comment]
also via the tooltip might be a good idea too

**Comment by GordonSmith** [comment]
Needs some thought - any suggestions?  Do we have data([]) and data2([])

**Comment by mlzummo** [comment]
@GordonSmith how will you render a chart with multiple "data" calls to the underlying widget? will we be accessing it via widgetArray?

**Comment by GordonSmith** [comment]
Work is underway for this.
