### ISSUE TITLE
Need for basic image widget

### ISSUE THREAD

**Issue by rpastrana** [hpcc-systems/Visualization#993]
Please provide  basic image widget with overlay support.

**Comment by GordonSmith** [comment]
@dtsnell4 Don't worry about the overlay (that will be in a separate widget), we just need a widget that displays an image.  Things to think about:
1.  Scaling + Aspect Ratios (should be able to scale to fit and maintain aspect ratio)
2.  Should support 100% size with scrollbars as well as scale to fit.
3.  A "projection" function (similar to mapping widgets):  Say you have a 1024x768 image and you display it in a 640x480 div.  Now when we put the widget into a layer and we want to overlay a "pin" on it at location 800x600 (origonal image coordinate) we should be able to pass that point into the projection function and get back the actual position on the page (in mapping we pass in a Lat/Long and get back a page position, here we pass in a x,y in orig image coordinates).
