### ISSUE TITLE
Google Bar, Scatter and Line cant be "required" twice on a page

### ISSUE THREAD

**Issue by jbrundage** [hpcc-systems/Visualization#995]
http://rawgit.com/hpcc-systems/Visualization/candidate-1.8.0/demos/dermatology.html?src/google/Bar

Go to the above link and toggle **S. Test** to see that it doesn't load the second instance of src/google/Bar

**Comment by mlzummo** [comment]
it will load 3rd and 4th though it seems

**Comment by mlzummo** [comment]
@GordonSmith can be tested via dermatology run serialization test and it wont run ... and then unclick and click again and it will run everytime after that .... is there a problem with the requirejs goog plugin?

**Comment by mlzummo** [comment]
only effects new 1.1 version of google visualization i believe

**Comment by mlzummo** [comment]
https://github.com/millermedeiros/requirejs-plugins/issues/69

**Comment by mlzummo** [comment]
wasnt able to reproduce outside of VIZ ... something to do with our dataFactories and anonymous functions ... and only happens after loading google visualization 1.1

**Comment by mlzummo** [comment]
Mismatched anonymous define() module:

**Comment by mlzummo** [comment]
if ( typeof define === "function" && define.amd && define.amd.jQuery ) {
    define( "jquery", [], function () { return jQuery; } );
}

using a named module above i dont know how that works (cant get it working) ... but maybe that might fix it?

**Comment by jbrundage** [comment]
@GordonSmith This is currently causing Travis CI to fail

**Comment by GordonSmith** [comment]
@jbrundage @mlzummo Nothing obvious I can spot (but I can reproduce) - the material charts are still in beta, so we may have no control over it (who issued this PR - did you know they were still beta?)

**Comment by mlzummo** [comment]
@GordonSmith I am not 100% sure but i dont think the issue is 100% google as i can only reproduce the issue when using the new DataFactory

**Comment by mlzummo** [comment]
also this is going to start effecting DSP so we need to fix this bug quickly

**Comment by dtsnell4** [comment]
I issued and I did not realize. https://github.com/hpcc-systems/Visualization/pull/927

**Comment by dtsnell4** [comment]
Should we revert back to old version and forgo dual y axis for now?

**Comment by mlzummo** [comment]
@dtsnell4 is there any reason we can't revert or did the new version provide a feature we needed?

**Comment by GordonSmith** [comment]
@jbrundage @mlzummo @dtsnell4 I think it may just be a async loading issue and that Line 1.1 needs corechart to be loaded first - investigating...

**Comment by mlzummo** [comment]
its no longer happening in dermatology

**Comment by jbrundage** [comment]
It's occasionally still happening in dermatology

**Comment by GordonSmith** [comment]
well it was nice that travis was catching it (even with the d3-cloud issue).

**Comment by mlzummo** [comment]
https://gist.github.com/Integralist/1599546 take a look at this

**Comment by mlzummo** [comment]
http://stackoverflow.com/questions/18332748/how-to-handle-requirejs-timeout-error

**Comment by mlzummo** [comment]
https://github.com/millermedeiros/requirejs-plugins/issues/45

**Comment by mlzummo** [comment]
http://techblog.realestate.com.au/loading-google-maps-with-requirejs/

**Comment by mlzummo** [comment]
i think i know how to fix this but its going to require a pretty big refactor

**Comment by mlzummo** [comment]
define(["d3", "../common/HTMLWidget", "async!http://www.google.com/jsapi"], factory);
...
google.load("visualization", 1.1, {"packages":["bar"]});
google.setOnLoadCallback(drawChart);
context._chart = new google.charts.Bar(domNode);

**Comment by mlzummo** [comment]
@GordonSmith bump

**Comment by GordonSmith** [comment]
That is effectively what ```goog!``` does:  https://github.com/GordonSmith/requirejs-plugins/blob/master/src/goog.js

**Comment by mlzummo** [comment]
nts: perhaps looks at r.js?
